# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
# tmp_dir = "/tmp/"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -o /tmp/bin/app ."
# Binary file yields from `cmd`.
bin = "/bin/main"
# Customize binary.
full_bin = "APP_ENV=local /tmp/bin/app http:serve --port=3000"
# Watch these filename extensions.
include_ext = ["go", "tpl", "tmpl", "html", "md", "json"]
# Ignore these filename extensions or directories.
exclude_dir = [
	"bin",
	"build",
	"frontend",
	"assets",
	"tmp",
	"node_modules",
	"quests",
	"vendor",
	"public",
	"_data",
	"data",
	"containers"
]
# Watch these directories if you specified.
include_dir = []
# Exclude files.
exclude_file = []
# This log file places in your tmp_dir.
log = "air.log"
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 100 # ms
# Stop running old binary when build errors occur.
stop_on_error = true
# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = true
# Delay after sending Interrupt signal
kill_delay = 10 # ms

[log]
# Show log time
time = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true
