package boot

import (
	"github.com/Akkadius/spire/http/crudcontrollers"
	"github.com/Akkadius/spire/http/routes"
	"github.com/google/wire"
)

type crudControllers struct {
	routes []routes.Controller
}

var httpCrudControllerSet = wire.NewSet(
	crudcontrollers.NewAaAbilityController,
	crudcontrollers.NewAaRankController,
	crudcontrollers.NewAccountController,
	crudcontrollers.NewAdventureDetailController,
	crudcontrollers.NewAdventureTemplateController,
	crudcontrollers.NewAdventureTemplateEntryController,
	crudcontrollers.NewAdventureTemplateEntryFlavorController,
	crudcontrollers.NewAlternateCurrencyController,
	crudcontrollers.NewBlockedSpellController,
	crudcontrollers.NewBugController,
	crudcontrollers.NewBugReportController,
	crudcontrollers.NewCharCreatePointAllocationController,
	crudcontrollers.NewCharacterAlternateAbilityController,
	crudcontrollers.NewCharacterAuraController,
	crudcontrollers.NewCharacterBandolierController,
	crudcontrollers.NewCharacterBindController,
	crudcontrollers.NewCharacterCorpseController,
	crudcontrollers.NewCharacterCurrencyController,
	crudcontrollers.NewCharacterDatumController,
	crudcontrollers.NewCharacterDisciplineController,
	crudcontrollers.NewCharacterExpeditionLockoutController,
	crudcontrollers.NewCharacterInspectMessageController,
	crudcontrollers.NewCharacterItemRecastController,
	crudcontrollers.NewCharacterLanguageController,
	crudcontrollers.NewCharacterLeadershipAbilityController,
	crudcontrollers.NewCharacterMaterialController,
	crudcontrollers.NewCharacterMemmedSpellController,
	crudcontrollers.NewCharacterPotionbeltController,
	crudcontrollers.NewCharacterSkillController,
	crudcontrollers.NewCharacterSpellController,
	crudcontrollers.NewContentFlagController,
	crudcontrollers.NewDataBucketController,
	crudcontrollers.NewDbStrController,
	crudcontrollers.NewDoorController,
	crudcontrollers.NewDynamicZoneController,
	crudcontrollers.NewEventlogController,
	crudcontrollers.NewExpeditionController,
	crudcontrollers.NewExpeditionLockoutController,
	crudcontrollers.NewExpeditionMemberController,
	crudcontrollers.NewFactionListController,
	crudcontrollers.NewFactionListModController,
	crudcontrollers.NewFishingController,
	crudcontrollers.NewForageController,
	crudcontrollers.NewGlobalLootController,
	crudcontrollers.NewGraveyardController,
	crudcontrollers.NewGridController,
	crudcontrollers.NewGroundSpawnController,
	crudcontrollers.NewGuildController,
	crudcontrollers.NewHackerController,
	crudcontrollers.NewInstanceListController,
	crudcontrollers.NewInstanceListPlayerController,
	crudcontrollers.NewItemController,
	crudcontrollers.NewLdonTrapEntryController,
	crudcontrollers.NewLdonTrapTemplateController,
	crudcontrollers.NewLoginAccountController,
	crudcontrollers.NewLoginApiTokenController,
	crudcontrollers.NewLoginServerAdminController,
	crudcontrollers.NewLoginServerListTypeController,
	crudcontrollers.NewLoginWorldServerController,
	crudcontrollers.NewLootdropController,
	crudcontrollers.NewLoottableController,
	crudcontrollers.NewNameFilterController,
	crudcontrollers.NewNpcEmoteController,
	crudcontrollers.NewNpcFactionController,
	crudcontrollers.NewNpcSpellController,
	crudcontrollers.NewNpcSpellsEffectController,
	crudcontrollers.NewNpcSpellsEffectsEntryController,
	crudcontrollers.NewNpcSpellsEntryController,
	crudcontrollers.NewNpcTypeController,
	crudcontrollers.NewNpcTypesTintController,
	crudcontrollers.NewObjectController,
	crudcontrollers.NewPlayerTitlesetController,
	crudcontrollers.NewReportController,
	crudcontrollers.NewRespawnTimeController,
	crudcontrollers.NewSaylinkController,
	crudcontrollers.NewServerScheduledEventController,
	crudcontrollers.NewSpawn2Controller,
	crudcontrollers.NewSpawnConditionController,
	crudcontrollers.NewSpawnConditionValueController,
	crudcontrollers.NewSpawnEventController,
	crudcontrollers.NewSpawngroupController,
	crudcontrollers.NewSpellsNewController,
	crudcontrollers.NewStartingItemController,
	crudcontrollers.NewTaskController,
	crudcontrollers.NewTasksetController,
	crudcontrollers.NewTitleController,
	crudcontrollers.NewTradeskillRecipeController,
	crudcontrollers.NewTradeskillRecipeEntryController,
	crudcontrollers.NewTrapController,
	crudcontrollers.NewTributeController,
	crudcontrollers.NewZoneController,
	crudcontrollers.NewZonePointController,
	provideCrudControllers,
)

func provideCrudControllers(
	aaAbilityController *crudcontrollers.AaAbilityController,
	aaRankController *crudcontrollers.AaRankController,
	accountController *crudcontrollers.AccountController,
	adventureDetailController *crudcontrollers.AdventureDetailController,
	adventureTemplateController *crudcontrollers.AdventureTemplateController,
	adventureTemplateEntryController *crudcontrollers.AdventureTemplateEntryController,
	adventureTemplateEntryFlavorController *crudcontrollers.AdventureTemplateEntryFlavorController,
	alternateCurrencyController *crudcontrollers.AlternateCurrencyController,
	blockedSpellController *crudcontrollers.BlockedSpellController,
	bugController *crudcontrollers.BugController,
	bugReportController *crudcontrollers.BugReportController,
	charCreatePointAllocationController *crudcontrollers.CharCreatePointAllocationController,
	characterAlternateAbilityController *crudcontrollers.CharacterAlternateAbilityController,
	characterAuraController *crudcontrollers.CharacterAuraController,
	characterBandolierController *crudcontrollers.CharacterBandolierController,
	characterBindController *crudcontrollers.CharacterBindController,
	characterCorpseController *crudcontrollers.CharacterCorpseController,
	characterCurrencyController *crudcontrollers.CharacterCurrencyController,
	characterDatumController *crudcontrollers.CharacterDatumController,
	characterDisciplineController *crudcontrollers.CharacterDisciplineController,
	characterExpeditionLockoutController *crudcontrollers.CharacterExpeditionLockoutController,
	characterInspectMessageController *crudcontrollers.CharacterInspectMessageController,
	characterItemRecastController *crudcontrollers.CharacterItemRecastController,
	characterLanguageController *crudcontrollers.CharacterLanguageController,
	characterLeadershipAbilityController *crudcontrollers.CharacterLeadershipAbilityController,
	characterMaterialController *crudcontrollers.CharacterMaterialController,
	characterMemmedSpellController *crudcontrollers.CharacterMemmedSpellController,
	characterPotionbeltController *crudcontrollers.CharacterPotionbeltController,
	characterSkillController *crudcontrollers.CharacterSkillController,
	characterSpellController *crudcontrollers.CharacterSpellController,
	contentFlagController *crudcontrollers.ContentFlagController,
	dataBucketController *crudcontrollers.DataBucketController,
	dbStrController *crudcontrollers.DbStrController,
	doorController *crudcontrollers.DoorController,
	dynamicZoneController *crudcontrollers.DynamicZoneController,
	eventlogController *crudcontrollers.EventlogController,
	expeditionController *crudcontrollers.ExpeditionController,
	expeditionLockoutController *crudcontrollers.ExpeditionLockoutController,
	expeditionMemberController *crudcontrollers.ExpeditionMemberController,
	factionListController *crudcontrollers.FactionListController,
	factionListModController *crudcontrollers.FactionListModController,
	fishingController *crudcontrollers.FishingController,
	forageController *crudcontrollers.ForageController,
	globalLootController *crudcontrollers.GlobalLootController,
	graveyardController *crudcontrollers.GraveyardController,
	gridController *crudcontrollers.GridController,
	groundSpawnController *crudcontrollers.GroundSpawnController,
	guildController *crudcontrollers.GuildController,
	hackerController *crudcontrollers.HackerController,
	instanceListController *crudcontrollers.InstanceListController,
	instanceListPlayerController *crudcontrollers.InstanceListPlayerController,
	itemController *crudcontrollers.ItemController,
	ldonTrapEntryController *crudcontrollers.LdonTrapEntryController,
	ldonTrapTemplateController *crudcontrollers.LdonTrapTemplateController,
	loginAccountController *crudcontrollers.LoginAccountController,
	loginApiTokenController *crudcontrollers.LoginApiTokenController,
	loginServerAdminController *crudcontrollers.LoginServerAdminController,
	loginServerListTypeController *crudcontrollers.LoginServerListTypeController,
	loginWorldServerController *crudcontrollers.LoginWorldServerController,
	lootdropController *crudcontrollers.LootdropController,
	loottableController *crudcontrollers.LoottableController,
	nameFilterController *crudcontrollers.NameFilterController,
	npcEmoteController *crudcontrollers.NpcEmoteController,
	npcFactionController *crudcontrollers.NpcFactionController,
	npcSpellController *crudcontrollers.NpcSpellController,
	npcSpellsEffectController *crudcontrollers.NpcSpellsEffectController,
	npcSpellsEffectsEntryController *crudcontrollers.NpcSpellsEffectsEntryController,
	npcSpellsEntryController *crudcontrollers.NpcSpellsEntryController,
	npcTypeController *crudcontrollers.NpcTypeController,
	npcTypesTintController *crudcontrollers.NpcTypesTintController,
	objectController *crudcontrollers.ObjectController,
	playerTitlesetController *crudcontrollers.PlayerTitlesetController,
	reportController *crudcontrollers.ReportController,
	respawnTimeController *crudcontrollers.RespawnTimeController,
	saylinkController *crudcontrollers.SaylinkController,
	serverScheduledEventController *crudcontrollers.ServerScheduledEventController,
	spawn2Controller *crudcontrollers.Spawn2Controller,
	spawnConditionController *crudcontrollers.SpawnConditionController,
	spawnConditionValueController *crudcontrollers.SpawnConditionValueController,
	spawnEventController *crudcontrollers.SpawnEventController,
	spawngroupController *crudcontrollers.SpawngroupController,
	spellsNewController *crudcontrollers.SpellsNewController,
	startingItemController *crudcontrollers.StartingItemController,
	taskController *crudcontrollers.TaskController,
	tasksetController *crudcontrollers.TasksetController,
	titleController *crudcontrollers.TitleController,
	tradeskillRecipeController *crudcontrollers.TradeskillRecipeController,
	tradeskillRecipeEntryController *crudcontrollers.TradeskillRecipeEntryController,
	trapController *crudcontrollers.TrapController,
	tributeController *crudcontrollers.TributeController,
	zoneController *crudcontrollers.ZoneController,
	zonePointController *crudcontrollers.ZonePointController,
) *crudControllers {
	return &crudControllers{
		routes: []routes.Controller{
			aaAbilityController,
			aaRankController,
			accountController,
			adventureDetailController,
			adventureTemplateController,
			adventureTemplateEntryController,
			adventureTemplateEntryFlavorController,
			alternateCurrencyController,
			blockedSpellController,
			bugController,
			bugReportController,
			charCreatePointAllocationController,
			characterAlternateAbilityController,
			characterAuraController,
			characterBandolierController,
			characterBindController,
			characterCorpseController,
			characterCurrencyController,
			characterDatumController,
			characterDisciplineController,
			characterExpeditionLockoutController,
			characterInspectMessageController,
			characterItemRecastController,
			characterLanguageController,
			characterLeadershipAbilityController,
			characterMaterialController,
			characterMemmedSpellController,
			characterPotionbeltController,
			characterSkillController,
			characterSpellController,
			contentFlagController,
			dataBucketController,
			dbStrController,
			doorController,
			dynamicZoneController,
			eventlogController,
			expeditionController,
			expeditionLockoutController,
			expeditionMemberController,
			factionListController,
			factionListModController,
			fishingController,
			forageController,
			globalLootController,
			graveyardController,
			gridController,
			groundSpawnController,
			guildController,
			hackerController,
			instanceListController,
			instanceListPlayerController,
			itemController,
			ldonTrapEntryController,
			ldonTrapTemplateController,
			loginAccountController,
			loginApiTokenController,
			loginServerAdminController,
			loginServerListTypeController,
			loginWorldServerController,
			lootdropController,
			loottableController,
			nameFilterController,
			npcEmoteController,
			npcFactionController,
			npcSpellController,
			npcSpellsEffectController,
			npcSpellsEffectsEntryController,
			npcSpellsEntryController,
			npcTypeController,
			npcTypesTintController,
			objectController,
			playerTitlesetController,
			reportController,
			respawnTimeController,
			saylinkController,
			serverScheduledEventController,
			spawn2Controller,
			spawnConditionController,
			spawnConditionValueController,
			spawnEventController,
			spawngroupController,
			spellsNewController,
			startingItemController,
			taskController,
			tasksetController,
			titleController,
			tradeskillRecipeController,
			tradeskillRecipeEntryController,
			trapController,
			tributeController,
			zoneController,
			zonePointController,
		},
	}
}
