/* tslint:disable */
/* eslint-disable */
/**
 * Spire
 * Spire API documentation
 *
 * The version of the OpenAPI document: 3.0
 * Contact: akkadius1@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModelsCharacterBind
 */
export interface ModelsCharacterBind {
    /**
     * 
     * @type {number}
     * @memberof ModelsCharacterBind
     */
    heading?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCharacterBind
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCharacterBind
     */
    instance_id?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCharacterBind
     */
    slot?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCharacterBind
     */
    x?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCharacterBind
     */
    y?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCharacterBind
     */
    z?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCharacterBind
     */
    zone_id?: number;
}


