/* tslint:disable */
/* eslint-disable */
/**
 * Spire
 * Spire API documentation
 *
 * The version of the OpenAPI document: 3.0
 * Contact: akkadius1@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModelsCompletedSharedTaskMember
 */
export interface ModelsCompletedSharedTaskMember {
    /**
     * 
     * @type {number}
     * @memberof ModelsCompletedSharedTaskMember
     */
    character_id?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCompletedSharedTaskMember
     */
    is_leader?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCompletedSharedTaskMember
     */
    shared_task_id?: number;
}


