import { ModelsAlternateCurrency } from './models-alternate-currency';
import { ModelsTaskActivity } from './models-task-activity';
import { ModelsTaskset } from './models-taskset';
export interface ModelsTask {
    alternate_currency?: ModelsAlternateCurrency;
    cashreward?: number;
    completion_emote?: string;
    description?: string;
    duration?: number;
    duration_code?: number;
    dz_template_id?: number;
    faction_amount?: number;
    faction_reward?: number;
    id?: number;
    level_spread?: number;
    lock_activity_id?: number;
    max_players?: number;
    maxlevel?: number;
    min_players?: number;
    minlevel?: number;
    repeatable?: number;
    replay_timer_group?: number;
    replay_timer_seconds?: number;
    request_timer_group?: number;
    request_timer_seconds?: number;
    reward?: string;
    reward_point_type?: number;
    reward_points?: number;
    rewardid?: number;
    rewardmethod?: number;
    task_activities?: Array<ModelsTaskActivity>;
    tasksets?: Array<ModelsTaskset>;
    title?: string;
    type?: number;
    xpreward?: number;
}
