/* tslint:disable */
/* eslint-disable */
/**
 * Spire
 * Spire API documentation
 *
 * The version of the OpenAPI document: 3.0
 * Contact: akkadius1@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModelsGuildMember
 */
export interface ModelsGuildMember {
    /**
     * 
     * @type {number}
     * @memberof ModelsGuildMember
     */
    alt?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsGuildMember
     */
    banker?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsGuildMember
     */
    char_id?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsGuildMember
     */
    guild_id?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsGuildMember
     */
    last_tribute?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsGuildMember
     */
    public_note?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsGuildMember
     */
    rank?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsGuildMember
     */
    total_tribute?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsGuildMember
     */
    tribute_enable?: number;
}


