/* tslint:disable */
/* eslint-disable */
/**
 * Spire
 * Spire API documentation
 *
 * The version of the OpenAPI document: 3.0
 * Contact: akkadius1@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModelsCharacterPeqzoneFlag
 */
export interface ModelsCharacterPeqzoneFlag {
    /**
     * 
     * @type {number}
     * @memberof ModelsCharacterPeqzoneFlag
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCharacterPeqzoneFlag
     */
    zone_id?: number;
}


