/* tslint:disable */
/* eslint-disable */
/**
 * Spire
 * Spire API documentation
 *
 * The version of the OpenAPI document: 3.0
 * Contact: akkadius1@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModelsExpedition
 */
export interface ModelsExpedition {
    /**
     * 
     * @type {number}
     * @memberof ModelsExpedition
     */
    add_replay_on_join?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsExpedition
     */
    dynamic_zone_id?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsExpedition
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsExpedition
     */
    is_locked?: number;
}


