/* tslint:disable */
/* eslint-disable */
/**
 * Spire
 * Spire API documentation
 *
 * The version of the OpenAPI document: 3.0
 * Contact: akkadius1@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ModelsAlternateCurrency } from './models-alternate-currency';
import { ModelsCharacterCorpseItem } from './models-character-corpse-item';
import { ModelsDiscoveredItem } from './models-discovered-item';
import { ModelsDoor } from './models-door';
import { ModelsFishing } from './models-fishing';
import { ModelsForage } from './models-forage';
import { ModelsGroundSpawn } from './models-ground-spawn';
import { ModelsItemTick } from './models-item-tick';
import { ModelsKeyring } from './models-keyring';
import { ModelsLootdropEntry } from './models-lootdrop-entry';
import { ModelsMerchantlist } from './models-merchantlist';
import { ModelsObject } from './models-object';
import { ModelsObjectContent } from './models-object-content';
import { ModelsStartingItem } from './models-starting-item';
import { ModelsTask } from './models-task';
import { ModelsTradeskillRecipeEntry } from './models-tradeskill-recipe-entry';
import { ModelsTributeLevel } from './models-tribute-level';

/**
 * 
 * @export
 * @interface ModelsItem
 */
export interface ModelsItem {
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    aagi?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    ac?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    accuracy?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    acha?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    adex?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    aint?: number;
    /**
     * 
     * @type {Array<ModelsAlternateCurrency>}
     * @memberof ModelsItem
     */
    alternate_currencies?: Array<ModelsAlternateCurrency>;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    artifactflag?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    asta?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    astr?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    attack?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    attuneable?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    augdistiller?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    augrestrict?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    augslot_1_type?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    augslot_1_unk_2?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    augslot_1_visible?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    augslot_2_type?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    augslot_2_unk_2?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    augslot_2_visible?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    augslot_3_type?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    augslot_3_unk_2?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    augslot_3_visible?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    augslot_4_type?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    augslot_4_unk_2?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    augslot_4_visible?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    augslot_5_type?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    augslot_5_unk_2?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    augslot_5_visible?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    augslot_6_type?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    augslot_6_unk_2?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    augslot_6_visible?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    augtype?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    avoidance?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    awis?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    backstabdmg?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    bagsize?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    bagslots?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    bagtype?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    bagwr?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    banedmgamt?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    banedmgbody?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    banedmgrace?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    banedmgraceamt?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    bardeffect?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    bardeffecttype?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    bardlevel?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    bardlevel_2?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsItem
     */
    bardname?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    bardtype?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    bardunk_1?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    bardunk_2?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    bardunk_3?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    bardunk_4?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    bardunk_5?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    bardunk_7?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    bardvalue?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    benefitflag?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    book?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    booktype?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    casttime?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    casttime_?: number;
    /**
     * 
     * @type {Array<ModelsCharacterCorpseItem>}
     * @memberof ModelsItem
     */
    character_corpse_items?: Array<ModelsCharacterCorpseItem>;
    /**
     * 
     * @type {string}
     * @memberof ModelsItem
     */
    charmfile?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsItem
     */
    charmfileid?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    clairvoyance?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    classes?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    clickeffect?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    clicklevel?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    clicklevel_2?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsItem
     */
    clickname?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    clicktype?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    clickunk_5?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsItem
     */
    clickunk_6?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    clickunk_7?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    color?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsItem
     */
    combateffects?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsItem
     */
    comment?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    cr?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsItem
     */
    created?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    damage?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    damageshield?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    deity?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    delay?: number;
    /**
     * 
     * @type {Array<ModelsDiscoveredItem>}
     * @memberof ModelsItem
     */
    discovered_items?: Array<ModelsDiscoveredItem>;
    /**
     * 
     * @type {Array<ModelsDoor>}
     * @memberof ModelsItem
     */
    doors?: Array<ModelsDoor>;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    dotshielding?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    dr?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    dsmitigation?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    elemdmgamt?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    elemdmgtype?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    elitematerial?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    endur?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    enduranceregen?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    epicitem?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    evoid?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    evoitem?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    evolvinglevel?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    evomax?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    expendablearrow?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    extradmgamt?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    extradmgskill?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    factionamt_1?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    factionamt_2?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    factionamt_3?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    factionamt_4?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    factionmod_1?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    factionmod_2?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    factionmod_3?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    factionmod_4?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    favor?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsItem
     */
    filename?: string;
    /**
     * 
     * @type {Array<ModelsFishing>}
     * @memberof ModelsItem
     */
    fishings?: Array<ModelsFishing>;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    focuseffect?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    focuslevel?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    focuslevel_2?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsItem
     */
    focusname?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    focustype?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    focusunk_1?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    focusunk_2?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    focusunk_3?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    focusunk_4?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    focusunk_5?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsItem
     */
    focusunk_6?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    focusunk_7?: number;
    /**
     * 
     * @type {Array<ModelsForage>}
     * @memberof ModelsItem
     */
    forages?: Array<ModelsForage>;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    fr?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    fvnodrop?: number;
    /**
     * 
     * @type {Array<ModelsGroundSpawn>}
     * @memberof ModelsItem
     */
    ground_spawns?: Array<ModelsGroundSpawn>;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    guildfavor?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    haste?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    healamt?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    heirloom?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    heroic_agi?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    heroic_cha?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    heroic_cr?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    heroic_dex?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    heroic_dr?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    heroic_fr?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    heroic_int?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    heroic_mr?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    heroic_pr?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    heroic_sta?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    heroic_str?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    heroic_svcorrup?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    heroic_wis?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    herosforgemodel?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    hp?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    icon?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsItem
     */
    idfile?: string;
    /**
     * 
     * @type {Array<ModelsItemTick>}
     * @memberof ModelsItem
     */
    item_ticks?: Array<ModelsItemTick>;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    itemclass?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    itemtype?: number;
    /**
     * 
     * @type {Array<ModelsKeyring>}
     * @memberof ModelsItem
     */
    keyrings?: Array<ModelsKeyring>;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    ldonprice?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    ldonsellbackrate?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    ldonsold?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    ldontheme?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    light?: number;
    /**
     * 
     * @type {Array<ModelsLootdropEntry>}
     * @memberof ModelsItem
     */
    lootdrop_entries?: Array<ModelsLootdropEntry>;
    /**
     * 
     * @type {string}
     * @memberof ModelsItem
     */
    lore?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsItem
     */
    lorefile?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    loregroup?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    magic?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    mana?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    manaregen?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    material?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    maxcharges?: number;
    /**
     * 
     * @type {Array<ModelsMerchantlist>}
     * @memberof ModelsItem
     */
    merchantlists?: Array<ModelsMerchantlist>;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    minstatus?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    mr?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsItem
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    nodrop?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    nopet?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    norent?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    notransfer?: number;
    /**
     * 
     * @type {Array<ModelsObjectContent>}
     * @memberof ModelsItem
     */
    object_contents?: Array<ModelsObjectContent>;
    /**
     * 
     * @type {Array<ModelsObject>}
     * @memberof ModelsItem
     */
    objects?: Array<ModelsObject>;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    pendingloreflag?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    placeable?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    pointtype?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    potionbelt?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    potionbeltslots?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    powersourcecapacity?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    pr?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    proceffect?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    proclevel?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    proclevel_2?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsItem
     */
    procname?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    procrate?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    proctype?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    procunk_1?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    procunk_2?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    procunk_3?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    procunk_4?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsItem
     */
    procunk_6?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    procunk_7?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    purity?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    questitemflag?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    races?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    range?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    recastdelay?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    recasttype?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    reclevel?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    recskill?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    regen?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    reqlevel?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    scriptfileid?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    scrolleffect?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    scrolllevel?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    scrolllevel_2?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsItem
     */
    scrollname?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    scrolltype?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    scrollunk_1?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    scrollunk_2?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    scrollunk_3?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    scrollunk_4?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    scrollunk_5?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsItem
     */
    scrollunk_6?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    scrollunk_7?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    sellrate?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsItem
     */
    serialization?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsItem
     */
    serialized?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    shielding?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    skillmodmax?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    skillmodtype?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    skillmodvalue?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    slots?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsItem
     */
    source?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    spelldmg?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    spellshield?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    stackable?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    stacksize?: number;
    /**
     * 
     * @type {Array<ModelsStartingItem>}
     * @memberof ModelsItem
     */
    starting_items?: Array<ModelsStartingItem>;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    strikethrough?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    stunresist?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    subtype?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    summonedflag?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    svcorruption?: number;
    /**
     * 
     * @type {Array<ModelsTask>}
     * @memberof ModelsItem
     */
    tasks?: Array<ModelsTask>;
    /**
     * 
     * @type {Array<ModelsTradeskillRecipeEntry>}
     * @memberof ModelsItem
     */
    tradeskill_recipe_entries?: Array<ModelsTradeskillRecipeEntry>;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    tradeskills?: number;
    /**
     * 
     * @type {Array<ModelsTributeLevel>}
     * @memberof ModelsItem
     */
    tribute_levels?: Array<ModelsTributeLevel>;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_012?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_013?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_014?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_033?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_054?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_059?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_060?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_120?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_121?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_123?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_124?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_127?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsItem
     */
    unk_132?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsItem
     */
    unk_134?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_137?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_142?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_147?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_152?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_157?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_193?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_214?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_220?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_221?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_223?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_224?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_225?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_226?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_227?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_228?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_229?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_230?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_231?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_232?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_233?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_234?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_236?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_237?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_238?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_239?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_240?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    unk_241?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsItem
     */
    updated?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsItem
     */
    verified?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    weight?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    worneffect?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    wornlevel?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    wornlevel_2?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsItem
     */
    wornname?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    worntype?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    wornunk_1?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    wornunk_2?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    wornunk_3?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    wornunk_4?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    wornunk_5?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsItem
     */
    wornunk_6?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsItem
     */
    wornunk_7?: number;
}


