/* tslint:disable */
/* eslint-disable */
/**
 * Spire
 * Spire API documentation
 *
 * The version of the OpenAPI document: 3.0
 * Contact: akkadius1@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModelsCharacterPetBuff
 */
export interface ModelsCharacterPetBuff {
    /**
     * 
     * @type {number}
     * @memberof ModelsCharacterPetBuff
     */
    caster_level?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsCharacterPetBuff
     */
    castername?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsCharacterPetBuff
     */
    char_id?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCharacterPetBuff
     */
    counters?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCharacterPetBuff
     */
    instrument_mod?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCharacterPetBuff
     */
    numhits?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCharacterPetBuff
     */
    pet?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCharacterPetBuff
     */
    rune?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCharacterPetBuff
     */
    slot?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCharacterPetBuff
     */
    spell_id?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCharacterPetBuff
     */
    ticsremaining?: number;
}


