package models

import (
	"github.com/volatiletech/null/v8"
)

type GlobalLoot struct {
	ID                     int         `json:"id" gorm:"Column:id"`
	Description            null.String `json:"description" gorm:"Column:description"`
	LoottableId            int         `json:"loottable_id" gorm:"Column:loottable_id"`
	Enabled                int8        `json:"enabled" gorm:"Column:enabled"`
	MinLevel               int         `json:"min_level" gorm:"Column:min_level"`
	MaxLevel               int         `json:"max_level" gorm:"Column:max_level"`
	Rare                   null.Int8   `json:"rare" gorm:"Column:rare"`
	Raid                   null.Int8   `json:"raid" gorm:"Column:raid"`
	Race                   null.String `json:"race" gorm:"Column:race"`
	Class                  null.String `json:"class" gorm:"Column:class"`
	Bodytype               null.String `json:"bodytype" gorm:"Column:bodytype"`
	Zone                   null.String `json:"zone" gorm:"Column:zone"`
	HotZone                null.Int8   `json:"hot_zone" gorm:"Column:hot_zone"`
	MinExpansion           int8        `json:"min_expansion" gorm:"Column:min_expansion"`
	MaxExpansion           int8        `json:"max_expansion" gorm:"Column:max_expansion"`
	ContentFlags           null.String `json:"content_flags" gorm:"Column:content_flags"`
	ContentFlagsDisabled   null.String `json:"content_flags_disabled" gorm:"Column:content_flags_disabled"`
	Loottable              *Loottable  `json:"loottable,omitempty" gorm:"foreignKey:loottable_id;references:id"`
}

func (GlobalLoot) TableName() string {
    return "global_loot"
}

func (GlobalLoot) Relationships() []string {
    return []string{
		"Loottable",
		"Loottable.LoottableEntries",
		"Loottable.LoottableEntries.Lootdrop",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.AlternateCurrencies",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.CharacterCorpseItems",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.DiscoveredItems",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Doors",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Doors.Item",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.Item",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.NpcType",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.NpcType.AlternateCurrency",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.NpcType.Loottable",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.NpcType.Merchantlists",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.NpcType.Merchantlists.Items",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.NpcType.Merchantlists.NpcTypes",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.NpcType.NpcEmotes",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.NpcType.NpcFactions",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.NpcType.NpcFactions.NpcFactionEntries",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.NpcType.NpcFactions.NpcFactionEntries.FactionList",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.NpcType.NpcSpell",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.NpcType.NpcSpell.NpcSpellsEntries",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.Aura",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.Aura.SpellsNew",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.BlockedSpells",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.Damageshieldtypes",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.Items",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.NpcSpellsEntries",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.SpellBuckets",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.SpellGlobals",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.NpcType.NpcTypesTint",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.NpcType.Spawnentries",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.NpcType.Spawnentries.NpcType",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.NpcType.Spawnentries.Spawngroup",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.NpcType.Spawnentries.Spawngroup.Spawn2",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.NpcType.Spawnentries.Spawngroup.Spawn2.Spawnentries",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.NpcType.Spawnentries.Spawngroup.Spawn2.Spawngroup",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Fishings.Zone",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Forages",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Forages.Item",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Forages.Zone",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.GroundSpawns",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.GroundSpawns.Zone",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.ItemTicks",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Keyrings",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.LootdropEntries",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Merchantlists",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Merchantlists.Items",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Merchantlists.NpcTypes",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Merchantlists.NpcTypes.AlternateCurrency",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Merchantlists.NpcTypes.Loottable",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Merchantlists.NpcTypes.Merchantlists",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Merchantlists.NpcTypes.NpcEmotes",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Merchantlists.NpcTypes.NpcFactions",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Merchantlists.NpcTypes.NpcFactions.NpcFactionEntries",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Merchantlists.NpcTypes.NpcFactions.NpcFactionEntries.FactionList",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Merchantlists.NpcTypes.NpcSpell",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Merchantlists.NpcTypes.NpcSpell.NpcSpellsEntries",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Merchantlists.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Merchantlists.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Aura",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Merchantlists.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Aura.SpellsNew",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Merchantlists.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.BlockedSpells",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Merchantlists.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Damageshieldtypes",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Merchantlists.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Merchantlists.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.NpcSpellsEntries",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Merchantlists.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.SpellBuckets",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Merchantlists.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.SpellGlobals",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Merchantlists.NpcTypes.NpcTypesTint",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Merchantlists.NpcTypes.Spawnentries",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Merchantlists.NpcTypes.Spawnentries.NpcType",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Merchantlists.NpcTypes.Spawnentries.Spawngroup",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Merchantlists.NpcTypes.Spawnentries.Spawngroup.Spawn2",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Merchantlists.NpcTypes.Spawnentries.Spawngroup.Spawn2.Spawnentries",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Merchantlists.NpcTypes.Spawnentries.Spawngroup.Spawn2.Spawngroup",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.ObjectContents",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Objects",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Objects.Item",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Objects.Zone",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.StartingItems",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.StartingItems.Item",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.StartingItems.Zone",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.Goallists",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.NpcType",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.NpcType.AlternateCurrency",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.NpcType.Loottable",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.NpcType.Merchantlists",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.NpcType.Merchantlists.Items",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.NpcType.Merchantlists.NpcTypes",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcEmotes",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcFactions",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcFactions.NpcFactionEntries",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcFactions.NpcFactionEntries.FactionList",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcSpell",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcSpell.NpcSpellsEntries",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.Aura",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.Aura.SpellsNew",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.BlockedSpells",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.Damageshieldtypes",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.Items",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.NpcSpellsEntries",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.SpellBuckets",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.SpellGlobals",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcTypesTint",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.NpcType.Spawnentries",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.NpcType.Spawnentries.NpcType",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.NpcType.Spawnentries.Spawngroup",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.NpcType.Spawnentries.Spawngroup.Spawn2",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.NpcType.Spawnentries.Spawngroup.Spawn2.Spawnentries",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.TaskActivities.NpcType.Spawnentries.Spawngroup.Spawn2.Spawngroup",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.Tasks.Tasksets",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.TradeskillRecipeEntries",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.TradeskillRecipeEntries.TradeskillRecipe",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item.TributeLevels",
		"Loottable.LoottableEntries.Lootdrop.LootdropEntries.Lootdrop",
		"Loottable.LoottableEntries.Lootdrop.LoottableEntries",
		"Loottable.LoottableEntries.Loottable",
		"Loottable.NpcTypes",
		"Loottable.NpcTypes.AlternateCurrency",
		"Loottable.NpcTypes.Loottable",
		"Loottable.NpcTypes.Merchantlists",
		"Loottable.NpcTypes.Merchantlists.Items",
		"Loottable.NpcTypes.Merchantlists.Items.AlternateCurrencies",
		"Loottable.NpcTypes.Merchantlists.Items.CharacterCorpseItems",
		"Loottable.NpcTypes.Merchantlists.Items.DiscoveredItems",
		"Loottable.NpcTypes.Merchantlists.Items.Doors",
		"Loottable.NpcTypes.Merchantlists.Items.Doors.Item",
		"Loottable.NpcTypes.Merchantlists.Items.Fishings",
		"Loottable.NpcTypes.Merchantlists.Items.Fishings.Item",
		"Loottable.NpcTypes.Merchantlists.Items.Fishings.NpcType",
		"Loottable.NpcTypes.Merchantlists.Items.Fishings.Zone",
		"Loottable.NpcTypes.Merchantlists.Items.Forages",
		"Loottable.NpcTypes.Merchantlists.Items.Forages.Item",
		"Loottable.NpcTypes.Merchantlists.Items.Forages.Zone",
		"Loottable.NpcTypes.Merchantlists.Items.GroundSpawns",
		"Loottable.NpcTypes.Merchantlists.Items.GroundSpawns.Zone",
		"Loottable.NpcTypes.Merchantlists.Items.ItemTicks",
		"Loottable.NpcTypes.Merchantlists.Items.Keyrings",
		"Loottable.NpcTypes.Merchantlists.Items.LootdropEntries",
		"Loottable.NpcTypes.Merchantlists.Items.LootdropEntries.Item",
		"Loottable.NpcTypes.Merchantlists.Items.LootdropEntries.Lootdrop",
		"Loottable.NpcTypes.Merchantlists.Items.LootdropEntries.Lootdrop.LootdropEntries",
		"Loottable.NpcTypes.Merchantlists.Items.LootdropEntries.Lootdrop.LoottableEntries",
		"Loottable.NpcTypes.Merchantlists.Items.LootdropEntries.Lootdrop.LoottableEntries.Lootdrop",
		"Loottable.NpcTypes.Merchantlists.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable",
		"Loottable.NpcTypes.Merchantlists.Items.Merchantlists",
		"Loottable.NpcTypes.Merchantlists.Items.ObjectContents",
		"Loottable.NpcTypes.Merchantlists.Items.Objects",
		"Loottable.NpcTypes.Merchantlists.Items.Objects.Item",
		"Loottable.NpcTypes.Merchantlists.Items.Objects.Zone",
		"Loottable.NpcTypes.Merchantlists.Items.StartingItems",
		"Loottable.NpcTypes.Merchantlists.Items.StartingItems.Item",
		"Loottable.NpcTypes.Merchantlists.Items.StartingItems.Zone",
		"Loottable.NpcTypes.Merchantlists.Items.Tasks",
		"Loottable.NpcTypes.Merchantlists.Items.Tasks.TaskActivities",
		"Loottable.NpcTypes.Merchantlists.Items.Tasks.TaskActivities.Goallists",
		"Loottable.NpcTypes.Merchantlists.Items.Tasks.TaskActivities.NpcType",
		"Loottable.NpcTypes.Merchantlists.Items.Tasks.Tasksets",
		"Loottable.NpcTypes.Merchantlists.Items.TradeskillRecipeEntries",
		"Loottable.NpcTypes.Merchantlists.Items.TradeskillRecipeEntries.TradeskillRecipe",
		"Loottable.NpcTypes.Merchantlists.Items.TributeLevels",
		"Loottable.NpcTypes.Merchantlists.NpcTypes",
		"Loottable.NpcTypes.NpcEmotes",
		"Loottable.NpcTypes.NpcFactions",
		"Loottable.NpcTypes.NpcFactions.NpcFactionEntries",
		"Loottable.NpcTypes.NpcFactions.NpcFactionEntries.FactionList",
		"Loottable.NpcTypes.NpcSpell",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Aura",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Aura.SpellsNew",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.BlockedSpells",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Damageshieldtypes",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.AlternateCurrencies",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.CharacterCorpseItems",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.DiscoveredItems",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Doors",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Doors.Item",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Fishings",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Fishings.Item",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Fishings.Zone",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Forages",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Forages.Item",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Forages.Zone",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.GroundSpawns",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.GroundSpawns.Zone",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.ItemTicks",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Keyrings",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.LootdropEntries",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Item",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LootdropEntries",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Lootdrop",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Merchantlists",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Merchantlists.Items",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.ObjectContents",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Objects",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Objects.Item",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Objects.Zone",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.StartingItems",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.StartingItems.Item",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.StartingItems.Zone",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Tasks",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Tasks.TaskActivities",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Tasks.TaskActivities.Goallists",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Tasks.TaskActivities.NpcType",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Tasks.Tasksets",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.TradeskillRecipeEntries",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.TradeskillRecipeEntries.TradeskillRecipe",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.TributeLevels",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.NpcSpellsEntries",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.SpellBuckets",
		"Loottable.NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.SpellGlobals",
		"Loottable.NpcTypes.NpcTypesTint",
		"Loottable.NpcTypes.Spawnentries",
		"Loottable.NpcTypes.Spawnentries.NpcType",
		"Loottable.NpcTypes.Spawnentries.Spawngroup",
		"Loottable.NpcTypes.Spawnentries.Spawngroup.Spawn2",
		"Loottable.NpcTypes.Spawnentries.Spawngroup.Spawn2.Spawnentries",
		"Loottable.NpcTypes.Spawnentries.Spawngroup.Spawn2.Spawngroup",
	}
}

func (GlobalLoot) Connection() string {
    return "eqemu_content"
}
