package models

import (
	"github.com/volatiletech/null/v8"
)

type Loottable struct {
	ID                     uint             `json:"id" gorm:"Column:id"`
	Name                   string           `json:"name" gorm:"Column:name"`
	Mincash                uint             `json:"mincash" gorm:"Column:mincash"`
	Maxcash                uint             `json:"maxcash" gorm:"Column:maxcash"`
	Avgcoin                uint             `json:"avgcoin" gorm:"Column:avgcoin"`
	Done                   int8             `json:"done" gorm:"Column:done"`
	MinExpansion           int8             `json:"min_expansion" gorm:"Column:min_expansion"`
	MaxExpansion           int8             `json:"max_expansion" gorm:"Column:max_expansion"`
	ContentFlags           null.String      `json:"content_flags" gorm:"Column:content_flags"`
	ContentFlagsDisabled   null.String      `json:"content_flags_disabled" gorm:"Column:content_flags_disabled"`
	LoottableEntries       []LoottableEntry `json:"loottable_entries,omitempty" gorm:"foreignKey:loottable_id;references:id"`
	NpcTypes               []NpcType        `json:"npc_types,omitempty" gorm:"foreignKey:loottable_id;references:id"`
}

func (Loottable) TableName() string {
    return "loottable"
}

func (Loottable) Relationships() []string {
    return []string{
		"LoottableEntries",
		"LoottableEntries.LootdropEntries",
		"LoottableEntries.LootdropEntries.Item",
		"LoottableEntries.LootdropEntries.Item.AlternateCurrencies",
		"LoottableEntries.LootdropEntries.Item.CharacterCorpseItems",
		"LoottableEntries.LootdropEntries.Item.DiscoveredItems",
		"LoottableEntries.LootdropEntries.Item.Doors",
		"LoottableEntries.LootdropEntries.Item.Doors.Item",
		"LoottableEntries.LootdropEntries.Item.Fishings",
		"LoottableEntries.LootdropEntries.Item.Fishings.Item",
		"LoottableEntries.LootdropEntries.Item.Fishings.NpcType",
		"LoottableEntries.LootdropEntries.Item.Fishings.NpcType.AlternateCurrency",
		"LoottableEntries.LootdropEntries.Item.Fishings.NpcType.Loottable",
		"LoottableEntries.LootdropEntries.Item.Fishings.NpcType.Merchantlists",
		"LoottableEntries.LootdropEntries.Item.Fishings.NpcType.Merchantlists.NpcType",
		"LoottableEntries.LootdropEntries.Item.Fishings.NpcType.NpcEmotes",
		"LoottableEntries.LootdropEntries.Item.Fishings.NpcType.NpcFactions",
		"LoottableEntries.LootdropEntries.Item.Fishings.NpcType.NpcFactions.NpcFactionEntries",
		"LoottableEntries.LootdropEntries.Item.Fishings.NpcType.NpcFactions.NpcFactionEntries.FactionList",
		"LoottableEntries.LootdropEntries.Item.Fishings.NpcType.NpcSpell",
		"LoottableEntries.LootdropEntries.Item.Fishings.NpcType.NpcSpell.NpcSpellsEntries",
		"LoottableEntries.LootdropEntries.Item.Fishings.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew",
		"LoottableEntries.LootdropEntries.Item.Fishings.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.Aura",
		"LoottableEntries.LootdropEntries.Item.Fishings.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.Aura.SpellsNew",
		"LoottableEntries.LootdropEntries.Item.Fishings.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.BlockedSpells",
		"LoottableEntries.LootdropEntries.Item.Fishings.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.Damageshieldtypes",
		"LoottableEntries.LootdropEntries.Item.Fishings.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.Items",
		"LoottableEntries.LootdropEntries.Item.Fishings.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.NpcSpellsEntries",
		"LoottableEntries.LootdropEntries.Item.Fishings.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.SpellBuckets",
		"LoottableEntries.LootdropEntries.Item.Fishings.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.SpellGlobals",
		"LoottableEntries.LootdropEntries.Item.Fishings.NpcType.NpcTypesTint",
		"LoottableEntries.LootdropEntries.Item.Fishings.NpcType.Spawnentries",
		"LoottableEntries.LootdropEntries.Item.Fishings.NpcType.Spawnentries.NpcType",
		"LoottableEntries.LootdropEntries.Item.Fishings.NpcType.Spawnentries.Spawngroup",
		"LoottableEntries.LootdropEntries.Item.Fishings.NpcType.Spawnentries.Spawngroup.Spawn2",
		"LoottableEntries.LootdropEntries.Item.Fishings.NpcType.Spawnentries.Spawngroup.Spawn2.Spawnentries",
		"LoottableEntries.LootdropEntries.Item.Fishings.NpcType.Spawnentries.Spawngroup.Spawn2.Spawngroup",
		"LoottableEntries.LootdropEntries.Item.Fishings.Zone",
		"LoottableEntries.LootdropEntries.Item.Forages",
		"LoottableEntries.LootdropEntries.Item.Forages.Item",
		"LoottableEntries.LootdropEntries.Item.Forages.Zone",
		"LoottableEntries.LootdropEntries.Item.GroundSpawns",
		"LoottableEntries.LootdropEntries.Item.GroundSpawns.Zone",
		"LoottableEntries.LootdropEntries.Item.ItemTicks",
		"LoottableEntries.LootdropEntries.Item.Keyrings",
		"LoottableEntries.LootdropEntries.Item.LootdropEntries",
		"LoottableEntries.LootdropEntries.Item.Merchantlists",
		"LoottableEntries.LootdropEntries.Item.Merchantlists.NpcType",
		"LoottableEntries.LootdropEntries.Item.Merchantlists.NpcType.AlternateCurrency",
		"LoottableEntries.LootdropEntries.Item.Merchantlists.NpcType.Loottable",
		"LoottableEntries.LootdropEntries.Item.Merchantlists.NpcType.Merchantlists",
		"LoottableEntries.LootdropEntries.Item.Merchantlists.NpcType.NpcEmotes",
		"LoottableEntries.LootdropEntries.Item.Merchantlists.NpcType.NpcFactions",
		"LoottableEntries.LootdropEntries.Item.Merchantlists.NpcType.NpcFactions.NpcFactionEntries",
		"LoottableEntries.LootdropEntries.Item.Merchantlists.NpcType.NpcFactions.NpcFactionEntries.FactionList",
		"LoottableEntries.LootdropEntries.Item.Merchantlists.NpcType.NpcSpell",
		"LoottableEntries.LootdropEntries.Item.Merchantlists.NpcType.NpcSpell.NpcSpellsEntries",
		"LoottableEntries.LootdropEntries.Item.Merchantlists.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew",
		"LoottableEntries.LootdropEntries.Item.Merchantlists.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.Aura",
		"LoottableEntries.LootdropEntries.Item.Merchantlists.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.Aura.SpellsNew",
		"LoottableEntries.LootdropEntries.Item.Merchantlists.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.BlockedSpells",
		"LoottableEntries.LootdropEntries.Item.Merchantlists.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.Damageshieldtypes",
		"LoottableEntries.LootdropEntries.Item.Merchantlists.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.Items",
		"LoottableEntries.LootdropEntries.Item.Merchantlists.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.NpcSpellsEntries",
		"LoottableEntries.LootdropEntries.Item.Merchantlists.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.SpellBuckets",
		"LoottableEntries.LootdropEntries.Item.Merchantlists.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.SpellGlobals",
		"LoottableEntries.LootdropEntries.Item.Merchantlists.NpcType.NpcTypesTint",
		"LoottableEntries.LootdropEntries.Item.Merchantlists.NpcType.Spawnentries",
		"LoottableEntries.LootdropEntries.Item.Merchantlists.NpcType.Spawnentries.NpcType",
		"LoottableEntries.LootdropEntries.Item.Merchantlists.NpcType.Spawnentries.Spawngroup",
		"LoottableEntries.LootdropEntries.Item.Merchantlists.NpcType.Spawnentries.Spawngroup.Spawn2",
		"LoottableEntries.LootdropEntries.Item.Merchantlists.NpcType.Spawnentries.Spawngroup.Spawn2.Spawnentries",
		"LoottableEntries.LootdropEntries.Item.Merchantlists.NpcType.Spawnentries.Spawngroup.Spawn2.Spawngroup",
		"LoottableEntries.LootdropEntries.Item.ObjectContents",
		"LoottableEntries.LootdropEntries.Item.Objects",
		"LoottableEntries.LootdropEntries.Item.Objects.Item",
		"LoottableEntries.LootdropEntries.Item.Objects.Zone",
		"LoottableEntries.LootdropEntries.Item.StartingItems",
		"LoottableEntries.LootdropEntries.Item.StartingItems.Item",
		"LoottableEntries.LootdropEntries.Item.StartingItems.Zone",
		"LoottableEntries.LootdropEntries.Item.Tasks",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities.Goallists",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities.NpcType",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities.NpcType.AlternateCurrency",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities.NpcType.Loottable",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities.NpcType.Merchantlists",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities.NpcType.Merchantlists.NpcType",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcEmotes",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcFactions",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcFactions.NpcFactionEntries",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcFactions.NpcFactionEntries.FactionList",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcSpell",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcSpell.NpcSpellsEntries",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.Aura",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.Aura.SpellsNew",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.BlockedSpells",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.Damageshieldtypes",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.Items",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.NpcSpellsEntries",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.SpellBuckets",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcSpell.NpcSpellsEntries.SpellsNew.SpellGlobals",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities.NpcType.NpcTypesTint",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities.NpcType.Spawnentries",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities.NpcType.Spawnentries.NpcType",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities.NpcType.Spawnentries.Spawngroup",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities.NpcType.Spawnentries.Spawngroup.Spawn2",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities.NpcType.Spawnentries.Spawngroup.Spawn2.Spawnentries",
		"LoottableEntries.LootdropEntries.Item.Tasks.TaskActivities.NpcType.Spawnentries.Spawngroup.Spawn2.Spawngroup",
		"LoottableEntries.LootdropEntries.Item.Tasks.Tasksets",
		"LoottableEntries.LootdropEntries.Item.TradeskillRecipeEntries",
		"LoottableEntries.LootdropEntries.Item.TradeskillRecipeEntries.TradeskillRecipe",
		"LoottableEntries.LootdropEntries.Item.TributeLevels",
		"LoottableEntries.LootdropEntries.Lootdrop",
		"LoottableEntries.LootdropEntries.Lootdrop.LootdropEntries",
		"LoottableEntries.LootdropEntries.Lootdrop.LoottableEntries",
		"LoottableEntries.Loottable",
		"NpcTypes",
		"NpcTypes.AlternateCurrency",
		"NpcTypes.Loottable",
		"NpcTypes.Merchantlists",
		"NpcTypes.Merchantlists.NpcType",
		"NpcTypes.NpcEmotes",
		"NpcTypes.NpcFactions",
		"NpcTypes.NpcFactions.NpcFactionEntries",
		"NpcTypes.NpcFactions.NpcFactionEntries.FactionList",
		"NpcTypes.NpcSpell",
		"NpcTypes.NpcSpell.NpcSpellsEntries",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Aura",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Aura.SpellsNew",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.BlockedSpells",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Damageshieldtypes",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.AlternateCurrencies",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.CharacterCorpseItems",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.DiscoveredItems",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Doors",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Doors.Item",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Fishings",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Fishings.Item",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Fishings.Zone",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Forages",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Forages.Item",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Forages.Zone",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.GroundSpawns",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.GroundSpawns.Zone",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.ItemTicks",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Keyrings",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.LootdropEntries",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Item",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LootdropEntries",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.LootdropEntries",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Merchantlists",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Merchantlists.NpcType",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.ObjectContents",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Objects",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Objects.Item",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Objects.Zone",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.StartingItems",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.StartingItems.Item",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.StartingItems.Zone",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Tasks",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Tasks.TaskActivities",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Tasks.TaskActivities.Goallists",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Tasks.TaskActivities.NpcType",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.Tasks.Tasksets",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.TradeskillRecipeEntries",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.TradeskillRecipeEntries.TradeskillRecipe",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.Items.TributeLevels",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.NpcSpellsEntries",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.SpellBuckets",
		"NpcTypes.NpcSpell.NpcSpellsEntries.SpellsNew.SpellGlobals",
		"NpcTypes.NpcTypesTint",
		"NpcTypes.Spawnentries",
		"NpcTypes.Spawnentries.NpcType",
		"NpcTypes.Spawnentries.Spawngroup",
		"NpcTypes.Spawnentries.Spawngroup.Spawn2",
		"NpcTypes.Spawnentries.Spawngroup.Spawn2.Spawnentries",
		"NpcTypes.Spawnentries.Spawngroup.Spawn2.Spawngroup",
	}
}

func (Loottable) Connection() string {
    return "eqemu_content"
}
