package models

import (
	"github.com/volatiletech/null/v8"
)

type NpcSpell struct {
	ID                       uint             `json:"id" gorm:"Column:id"`
	Name                     null.String      `json:"name" gorm:"Column:name"`
	ParentList               uint             `json:"parent_list" gorm:"Column:parent_list"`
	AttackProc               int16            `json:"attack_proc" gorm:"Column:attack_proc"`
	ProcChance               int8             `json:"proc_chance" gorm:"Column:proc_chance"`
	RangeProc                int16            `json:"range_proc" gorm:"Column:range_proc"`
	RprocChance              int16            `json:"rproc_chance" gorm:"Column:rproc_chance"`
	DefensiveProc            int16            `json:"defensive_proc" gorm:"Column:defensive_proc"`
	DprocChance              int16            `json:"dproc_chance" gorm:"Column:dproc_chance"`
	FailRecast               uint             `json:"fail_recast" gorm:"Column:fail_recast"`
	EngagedNoSpRecastMin     uint             `json:"engaged_no_sp_recast_min" gorm:"Column:engaged_no_sp_recast_min"`
	EngagedNoSpRecastMax     uint             `json:"engaged_no_sp_recast_max" gorm:"Column:engaged_no_sp_recast_max"`
	EngagedBSelfChance       uint8            `json:"engaged_b_self_chance" gorm:"Column:engaged_b_self_chance"`
	EngagedBOtherChance      uint8            `json:"engaged_b_other_chance" gorm:"Column:engaged_b_other_chance"`
	EngagedDChance           uint8            `json:"engaged_d_chance" gorm:"Column:engaged_d_chance"`
	PursueNoSpRecastMin      uint             `json:"pursue_no_sp_recast_min" gorm:"Column:pursue_no_sp_recast_min"`
	PursueNoSpRecastMax      uint             `json:"pursue_no_sp_recast_max" gorm:"Column:pursue_no_sp_recast_max"`
	PursueDChance            uint8            `json:"pursue_d_chance" gorm:"Column:pursue_d_chance"`
	IdleNoSpRecastMin        uint             `json:"idle_no_sp_recast_min" gorm:"Column:idle_no_sp_recast_min"`
	IdleNoSpRecastMax        uint             `json:"idle_no_sp_recast_max" gorm:"Column:idle_no_sp_recast_max"`
	IdleBChance              uint8            `json:"idle_b_chance" gorm:"Column:idle_b_chance"`
	NpcSpellsEntries         []NpcSpellsEntry `json:"npc_spells_entries,omitempty" gorm:"foreignKey:npc_spells_id;references:id"`
	NpcSpell                 *NpcSpell        `json:"npc_spell,omitempty" gorm:"foreignKey:parent_list;references:id"`
	BotSpellsEntries         []BotSpellsEntry `json:"bot_spells_entries,omitempty" gorm:"foreignKey:npc_spells_id;references:id"`
}

func (NpcSpell) TableName() string {
    return "npc_spells"
}

func (NpcSpell) Relationships() []string {
    return []string{
		"BotSpellsEntries",
		"BotSpellsEntries.NpcSpell",
		"BotSpellsEntries.SpellsNew",
		"BotSpellsEntries.SpellsNew.Aura",
		"BotSpellsEntries.SpellsNew.Aura.SpellsNew",
		"BotSpellsEntries.SpellsNew.BlockedSpells",
		"BotSpellsEntries.SpellsNew.BotSpellsEntries",
		"BotSpellsEntries.SpellsNew.Damageshieldtypes",
		"BotSpellsEntries.SpellsNew.Items",
		"BotSpellsEntries.SpellsNew.Items.AlternateCurrencies",
		"BotSpellsEntries.SpellsNew.Items.AlternateCurrencies.Item",
		"BotSpellsEntries.SpellsNew.Items.CharacterCorpseItems",
		"BotSpellsEntries.SpellsNew.Items.DiscoveredItems",
		"BotSpellsEntries.SpellsNew.Items.Doors",
		"BotSpellsEntries.SpellsNew.Items.Doors.Item",
		"BotSpellsEntries.SpellsNew.Items.Fishings",
		"BotSpellsEntries.SpellsNew.Items.Fishings.Item",
		"BotSpellsEntries.SpellsNew.Items.Fishings.NpcType",
		"BotSpellsEntries.SpellsNew.Items.Fishings.NpcType.AlternateCurrency",
		"BotSpellsEntries.SpellsNew.Items.Fishings.NpcType.AlternateCurrency.Item",
		"BotSpellsEntries.SpellsNew.Items.Fishings.NpcType.Loottable",
		"BotSpellsEntries.SpellsNew.Items.Fishings.NpcType.Loottable.LoottableEntries",
		"BotSpellsEntries.SpellsNew.Items.Fishings.NpcType.Loottable.LoottableEntries.Lootdrop",
		"BotSpellsEntries.SpellsNew.Items.Fishings.NpcType.Loottable.LoottableEntries.Lootdrop.LootdropEntries",
		"BotSpellsEntries.SpellsNew.Items.Fishings.NpcType.Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item",
		"BotSpellsEntries.SpellsNew.Items.Fishings.NpcType.Loottable.LoottableEntries.Lootdrop.LootdropEntries.Lootdrop",
		"BotSpellsEntries.SpellsNew.Items.Fishings.NpcType.Loottable.LoottableEntries.Lootdrop.LoottableEntries",
		"BotSpellsEntries.SpellsNew.Items.Fishings.NpcType.Loottable.LoottableEntries.Loottable",
		"BotSpellsEntries.SpellsNew.Items.Fishings.NpcType.Loottable.NpcTypes",
		"BotSpellsEntries.SpellsNew.Items.Fishings.NpcType.Merchantlists",
		"BotSpellsEntries.SpellsNew.Items.Fishings.NpcType.Merchantlists.Items",
		"BotSpellsEntries.SpellsNew.Items.Fishings.NpcType.Merchantlists.NpcTypes",
		"BotSpellsEntries.SpellsNew.Items.Fishings.NpcType.NpcEmotes",
		"BotSpellsEntries.SpellsNew.Items.Fishings.NpcType.NpcFactions",
		"BotSpellsEntries.SpellsNew.Items.Fishings.NpcType.NpcFactions.NpcFactionEntries",
		"BotSpellsEntries.SpellsNew.Items.Fishings.NpcType.NpcFactions.NpcFactionEntries.FactionList",
		"BotSpellsEntries.SpellsNew.Items.Fishings.NpcType.NpcSpell",
		"BotSpellsEntries.SpellsNew.Items.Fishings.NpcType.NpcTypesTint",
		"BotSpellsEntries.SpellsNew.Items.Fishings.NpcType.Spawnentries",
		"BotSpellsEntries.SpellsNew.Items.Fishings.NpcType.Spawnentries.NpcType",
		"BotSpellsEntries.SpellsNew.Items.Fishings.NpcType.Spawnentries.Spawngroup",
		"BotSpellsEntries.SpellsNew.Items.Fishings.NpcType.Spawnentries.Spawngroup.Spawn2",
		"BotSpellsEntries.SpellsNew.Items.Fishings.NpcType.Spawnentries.Spawngroup.Spawn2.Spawnentries",
		"BotSpellsEntries.SpellsNew.Items.Fishings.NpcType.Spawnentries.Spawngroup.Spawn2.Spawngroup",
		"BotSpellsEntries.SpellsNew.Items.Fishings.Zone",
		"BotSpellsEntries.SpellsNew.Items.Forages",
		"BotSpellsEntries.SpellsNew.Items.Forages.Item",
		"BotSpellsEntries.SpellsNew.Items.Forages.Zone",
		"BotSpellsEntries.SpellsNew.Items.GroundSpawns",
		"BotSpellsEntries.SpellsNew.Items.GroundSpawns.Zone",
		"BotSpellsEntries.SpellsNew.Items.ItemTicks",
		"BotSpellsEntries.SpellsNew.Items.Keyrings",
		"BotSpellsEntries.SpellsNew.Items.LootdropEntries",
		"BotSpellsEntries.SpellsNew.Items.LootdropEntries.Item",
		"BotSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop",
		"BotSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LootdropEntries",
		"BotSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries",
		"BotSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Lootdrop",
		"BotSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable",
		"BotSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.LoottableEntries",
		"BotSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes",
		"BotSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.AlternateCurrency",
		"BotSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.AlternateCurrency.Item",
		"BotSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.Loottable",
		"BotSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.Merchantlists",
		"BotSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.Merchantlists.Items",
		"BotSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.Merchantlists.NpcTypes",
		"BotSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.NpcEmotes",
		"BotSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.NpcFactions",
		"BotSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.NpcFactions.NpcFactionEntries",
		"BotSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.NpcFactions.NpcFactionEntries.FactionList",
		"BotSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.NpcSpell",
		"BotSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.NpcTypesTint",
		"BotSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.Spawnentries",
		"BotSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.Spawnentries.NpcType",
		"BotSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.Spawnentries.Spawngroup",
		"BotSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.Spawnentries.Spawngroup.Spawn2",
		"BotSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.Spawnentries.Spawngroup.Spawn2.Spawnentries",
		"BotSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.Spawnentries.Spawngroup.Spawn2.Spawngroup",
		"BotSpellsEntries.SpellsNew.Items.Merchantlists",
		"BotSpellsEntries.SpellsNew.Items.Merchantlists.Items",
		"BotSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes",
		"BotSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.AlternateCurrency",
		"BotSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.AlternateCurrency.Item",
		"BotSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Loottable",
		"BotSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Loottable.LoottableEntries",
		"BotSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Loottable.LoottableEntries.Lootdrop",
		"BotSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Loottable.LoottableEntries.Lootdrop.LootdropEntries",
		"BotSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item",
		"BotSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Loottable.LoottableEntries.Lootdrop.LootdropEntries.Lootdrop",
		"BotSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Loottable.LoottableEntries.Lootdrop.LoottableEntries",
		"BotSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Loottable.LoottableEntries.Loottable",
		"BotSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Loottable.NpcTypes",
		"BotSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Merchantlists",
		"BotSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.NpcEmotes",
		"BotSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.NpcFactions",
		"BotSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.NpcFactions.NpcFactionEntries",
		"BotSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.NpcFactions.NpcFactionEntries.FactionList",
		"BotSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.NpcSpell",
		"BotSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.NpcTypesTint",
		"BotSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Spawnentries",
		"BotSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Spawnentries.NpcType",
		"BotSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Spawnentries.Spawngroup",
		"BotSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Spawnentries.Spawngroup.Spawn2",
		"BotSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Spawnentries.Spawngroup.Spawn2.Spawnentries",
		"BotSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Spawnentries.Spawngroup.Spawn2.Spawngroup",
		"BotSpellsEntries.SpellsNew.Items.ObjectContents",
		"BotSpellsEntries.SpellsNew.Items.Objects",
		"BotSpellsEntries.SpellsNew.Items.Objects.Item",
		"BotSpellsEntries.SpellsNew.Items.Objects.Zone",
		"BotSpellsEntries.SpellsNew.Items.TradeskillRecipeEntries",
		"BotSpellsEntries.SpellsNew.Items.TradeskillRecipeEntries.TradeskillRecipe",
		"BotSpellsEntries.SpellsNew.Items.TributeLevels",
		"BotSpellsEntries.SpellsNew.NpcSpellsEntries",
		"BotSpellsEntries.SpellsNew.NpcSpellsEntries.SpellsNew",
		"BotSpellsEntries.SpellsNew.SpellBuckets",
		"BotSpellsEntries.SpellsNew.SpellGlobals",
		"NpcSpell",
		"NpcSpellsEntries",
		"NpcSpellsEntries.SpellsNew",
		"NpcSpellsEntries.SpellsNew.Aura",
		"NpcSpellsEntries.SpellsNew.Aura.SpellsNew",
		"NpcSpellsEntries.SpellsNew.BlockedSpells",
		"NpcSpellsEntries.SpellsNew.BotSpellsEntries",
		"NpcSpellsEntries.SpellsNew.BotSpellsEntries.NpcSpell",
		"NpcSpellsEntries.SpellsNew.BotSpellsEntries.SpellsNew",
		"NpcSpellsEntries.SpellsNew.Damageshieldtypes",
		"NpcSpellsEntries.SpellsNew.Items",
		"NpcSpellsEntries.SpellsNew.Items.AlternateCurrencies",
		"NpcSpellsEntries.SpellsNew.Items.AlternateCurrencies.Item",
		"NpcSpellsEntries.SpellsNew.Items.CharacterCorpseItems",
		"NpcSpellsEntries.SpellsNew.Items.DiscoveredItems",
		"NpcSpellsEntries.SpellsNew.Items.Doors",
		"NpcSpellsEntries.SpellsNew.Items.Doors.Item",
		"NpcSpellsEntries.SpellsNew.Items.Fishings",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.Item",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType.AlternateCurrency",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType.AlternateCurrency.Item",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType.Loottable",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType.Loottable.LoottableEntries",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType.Loottable.LoottableEntries.Lootdrop",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType.Loottable.LoottableEntries.Lootdrop.LootdropEntries",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType.Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType.Loottable.LoottableEntries.Lootdrop.LootdropEntries.Lootdrop",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType.Loottable.LoottableEntries.Lootdrop.LoottableEntries",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType.Loottable.LoottableEntries.Loottable",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType.Loottable.NpcTypes",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType.Merchantlists",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType.Merchantlists.Items",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType.Merchantlists.NpcTypes",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType.NpcEmotes",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType.NpcFactions",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType.NpcFactions.NpcFactionEntries",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType.NpcFactions.NpcFactionEntries.FactionList",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType.NpcSpell",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType.NpcTypesTint",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType.Spawnentries",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType.Spawnentries.NpcType",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType.Spawnentries.Spawngroup",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType.Spawnentries.Spawngroup.Spawn2",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType.Spawnentries.Spawngroup.Spawn2.Spawnentries",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.NpcType.Spawnentries.Spawngroup.Spawn2.Spawngroup",
		"NpcSpellsEntries.SpellsNew.Items.Fishings.Zone",
		"NpcSpellsEntries.SpellsNew.Items.Forages",
		"NpcSpellsEntries.SpellsNew.Items.Forages.Item",
		"NpcSpellsEntries.SpellsNew.Items.Forages.Zone",
		"NpcSpellsEntries.SpellsNew.Items.GroundSpawns",
		"NpcSpellsEntries.SpellsNew.Items.GroundSpawns.Zone",
		"NpcSpellsEntries.SpellsNew.Items.ItemTicks",
		"NpcSpellsEntries.SpellsNew.Items.Keyrings",
		"NpcSpellsEntries.SpellsNew.Items.LootdropEntries",
		"NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Item",
		"NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop",
		"NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LootdropEntries",
		"NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries",
		"NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Lootdrop",
		"NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable",
		"NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.LoottableEntries",
		"NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes",
		"NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.AlternateCurrency",
		"NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.AlternateCurrency.Item",
		"NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.Loottable",
		"NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.Merchantlists",
		"NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.Merchantlists.Items",
		"NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.Merchantlists.NpcTypes",
		"NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.NpcEmotes",
		"NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.NpcFactions",
		"NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.NpcFactions.NpcFactionEntries",
		"NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.NpcFactions.NpcFactionEntries.FactionList",
		"NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.NpcSpell",
		"NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.NpcTypesTint",
		"NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.Spawnentries",
		"NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.Spawnentries.NpcType",
		"NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.Spawnentries.Spawngroup",
		"NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.Spawnentries.Spawngroup.Spawn2",
		"NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.Spawnentries.Spawngroup.Spawn2.Spawnentries",
		"NpcSpellsEntries.SpellsNew.Items.LootdropEntries.Lootdrop.LoottableEntries.Loottable.NpcTypes.Spawnentries.Spawngroup.Spawn2.Spawngroup",
		"NpcSpellsEntries.SpellsNew.Items.Merchantlists",
		"NpcSpellsEntries.SpellsNew.Items.Merchantlists.Items",
		"NpcSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes",
		"NpcSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.AlternateCurrency",
		"NpcSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.AlternateCurrency.Item",
		"NpcSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Loottable",
		"NpcSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Loottable.LoottableEntries",
		"NpcSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Loottable.LoottableEntries.Lootdrop",
		"NpcSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Loottable.LoottableEntries.Lootdrop.LootdropEntries",
		"NpcSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Loottable.LoottableEntries.Lootdrop.LootdropEntries.Item",
		"NpcSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Loottable.LoottableEntries.Lootdrop.LootdropEntries.Lootdrop",
		"NpcSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Loottable.LoottableEntries.Lootdrop.LoottableEntries",
		"NpcSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Loottable.LoottableEntries.Loottable",
		"NpcSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Loottable.NpcTypes",
		"NpcSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Merchantlists",
		"NpcSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.NpcEmotes",
		"NpcSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.NpcFactions",
		"NpcSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.NpcFactions.NpcFactionEntries",
		"NpcSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.NpcFactions.NpcFactionEntries.FactionList",
		"NpcSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.NpcSpell",
		"NpcSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.NpcTypesTint",
		"NpcSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Spawnentries",
		"NpcSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Spawnentries.NpcType",
		"NpcSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Spawnentries.Spawngroup",
		"NpcSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Spawnentries.Spawngroup.Spawn2",
		"NpcSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Spawnentries.Spawngroup.Spawn2.Spawnentries",
		"NpcSpellsEntries.SpellsNew.Items.Merchantlists.NpcTypes.Spawnentries.Spawngroup.Spawn2.Spawngroup",
		"NpcSpellsEntries.SpellsNew.Items.ObjectContents",
		"NpcSpellsEntries.SpellsNew.Items.Objects",
		"NpcSpellsEntries.SpellsNew.Items.Objects.Item",
		"NpcSpellsEntries.SpellsNew.Items.Objects.Zone",
		"NpcSpellsEntries.SpellsNew.Items.TradeskillRecipeEntries",
		"NpcSpellsEntries.SpellsNew.Items.TradeskillRecipeEntries.TradeskillRecipe",
		"NpcSpellsEntries.SpellsNew.Items.TributeLevels",
		"NpcSpellsEntries.SpellsNew.NpcSpellsEntries",
		"NpcSpellsEntries.SpellsNew.SpellBuckets",
		"NpcSpellsEntries.SpellsNew.SpellGlobals",
	}
}

func (NpcSpell) Connection() string {
    return "eqemu_content"
}
