<template>
  <vue-form-generator
    v-if="model"
    :schema="schema"
    :model="model"
    @validated="onValidated"
    :options="formOptions"/>
</template>

<script>
export default {
  props: {
    model: {
      type: Object
    }
  },
  methods: {
    onValidated(isValid, errors) {
      console.log("Validation result: ", isValid, ", Errors:", errors);
    },
  },
  data() {
    return {
      schema: {
        groups: [
          {
            legend: "General",
            fields: "",
          },
          {
            legend: "Sky",
            fields: "",
          }
        ],
        fields:
          [
            {
              "featured": false,
              "inputType": "text",
              "label": "Short Name",
              "model": "short_name",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Id",
              "model": "id",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "File Name",
              "model": "file_name",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Long Name",
              "model": "long_name",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Map File Name",
              "model": "map_file_name",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Safe X",
              "model": "safe_x",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Safe Y",
              "model": "safe_y",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Safe Z",
              "model": "safe_z",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Graveyard Id",
              "model": "graveyard_id",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Min Level",
              "model": "min_level",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Min Status",
              "model": "min_status",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Zoneidnumber",
              "model": "zoneidnumber",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Version",
              "model": "version",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Timezone",
              "model": "timezone",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Maxclients",
              "model": "maxclients",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Ruleset",
              "model": "ruleset",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Note",
              "model": "note",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Underworld",
              "model": "underworld",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Minclip",
              "model": "minclip",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Maxclip",
              "model": "maxclip",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fog Minclip",
              "model": "fog_minclip",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fog Maxclip",
              "model": "fog_maxclip",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fog Blue",
              "model": "fog_blue",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fog Red",
              "model": "fog_red",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fog Green",
              "model": "fog_green",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Sky",
              "model": "sky",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Ztype",
              "model": "ztype",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Zone Exp Multiplier",
              "model": "zone_exp_multiplier",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Walkspeed",
              "model": "walkspeed",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Time Type",
              "model": "time_type",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fog Red1",
              "model": "fog_red1",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fog Green1",
              "model": "fog_green1",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fog Blue1",
              "model": "fog_blue1",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fog Minclip1",
              "model": "fog_minclip1",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fog Maxclip1",
              "model": "fog_maxclip1",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fog Red2",
              "model": "fog_red2",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fog Green2",
              "model": "fog_green2",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fog Blue2",
              "model": "fog_blue2",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fog Minclip2",
              "model": "fog_minclip2",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fog Maxclip2",
              "model": "fog_maxclip2",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fog Red3",
              "model": "fog_red3",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fog Green3",
              "model": "fog_green3",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fog Blue3",
              "model": "fog_blue3",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fog Minclip3",
              "model": "fog_minclip3",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fog Maxclip3",
              "model": "fog_maxclip3",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fog Red4",
              "model": "fog_red4",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fog Green4",
              "model": "fog_green4",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fog Blue4",
              "model": "fog_blue4",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fog Minclip4",
              "model": "fog_minclip4",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fog Maxclip4",
              "model": "fog_maxclip4",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fog Density",
              "model": "fog_density",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Flag Needed",
              "model": "flag_needed",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Canbind",
              "model": "canbind",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Cancombat",
              "model": "cancombat",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Canlevitate",
              "model": "canlevitate",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Castoutdoor",
              "model": "castoutdoor",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Hotzone",
              "model": "hotzone",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Insttype",
              "model": "insttype",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Shutdowndelay",
              "model": "shutdowndelay",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Peqzone",
              "model": "peqzone",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Expansion",
              "model": "expansion",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Suspendbuffs",
              "model": "suspendbuffs",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Rain Chance1",
              "model": "rain_chance1",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Rain Chance2",
              "model": "rain_chance2",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Rain Chance3",
              "model": "rain_chance3",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Rain Chance4",
              "model": "rain_chance4",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Rain Duration1",
              "model": "rain_duration1",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Rain Duration2",
              "model": "rain_duration2",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Rain Duration3",
              "model": "rain_duration3",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Rain Duration4",
              "model": "rain_duration4",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Snow Chance1",
              "model": "snow_chance1",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Snow Chance2",
              "model": "snow_chance2",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Snow Chance3",
              "model": "snow_chance3",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Snow Chance4",
              "model": "snow_chance4",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Snow Duration1",
              "model": "snow_duration1",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Snow Duration2",
              "model": "snow_duration2",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Snow Duration3",
              "model": "snow_duration3",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Snow Duration4",
              "model": "snow_duration4",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Gravity",
              "model": "gravity",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Type",
              "model": "type",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Skylock",
              "model": "skylock",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fast Regen Hp",
              "model": "fast_regen_hp",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fast Regen Mana",
              "model": "fast_regen_mana",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Fast Regen Endurance",
              "model": "fast_regen_endurance",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Npc Max Aggro Dist",
              "model": "npc_max_aggro_dist",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Max Movement Update Range",
              "model": "max_movement_update_range",
              "styleClasses": "col-4",
              "type": "input",
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Min Expansion",
              "model": "min_expansion",
              "styleClasses": "col-4",
              "type": "input"
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Max Expansion",
              "model": "max_expansion",
              "styleClasses": "col-4",
              "type": "input"
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Content Flags",
              "model": "content_flags",
              "styleClasses": "col-4",
              "type": "input"
            },
            {
              "featured": false,
              "inputType": "text",
              "label": "Content Flags Disabled",
              "model": "content_flags_disabled",
              "styleClasses": "col-4",
              "type": "input"
            }
          ]
      },

      formOptions: {
        validateAfterChanged: true,
        validateDebounceTime: 500,

        // validateAfterLoad: true,
        // validateAfterChanged: true
      }
    };
  }

}
</script>
