- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique AA Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Name
  model: name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Category
  model: category
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/aas/aa-categories" target="_blank">AA Category</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Classes
  model: classes
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/class-list" target="_blank">Classes</a> Bitmasks</p>
- disabled: false
  featured: false
  inputtype: text
  label: Races
  model: races
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/npc/race-list" target="_blank">Races</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Drakkin Heritage
  model: drakkin_heritage
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Drakkin Heritage: 127 = All</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Deities
  model: deities
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/deity-list" target="_blank">Deities</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Status
  model: status
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/status-levels" target="_blank">Minimum Status</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Type
  model: type
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/aas/aa-types" target="_blank">AA Type</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Charges
  model: charges
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Number of Charges</p>
- disabled: false
  featured: false
  inputtype: text
  label: Grant Only
  model: grant_only
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Grant Only Flag: 0 = No, 1 = Yes</p>'
- disabled: false
  featured: false
  inputtype: text
  label: First Rank Id
  model: first_rank_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>First Rank Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Enabled
  model: enabled
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Enabled: 0 = No, 1 = Yes</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Reset On Death
  model: reset_on_death
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
