- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="aa_ability.md" target="_blank">AA Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Upper Hotkey Sid
  model: upper_hotkey_sid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Upper Hotkey SID</p>
- disabled: false
  featured: false
  inputtype: text
  label: Lower Hotkey Sid
  model: lower_hotkey_sid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Lower Hotkey SID</p>
- disabled: false
  featured: false
  inputtype: text
  label: Title Sid
  model: title_sid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Title SID</p>
- disabled: false
  featured: false
  inputtype: text
  label: Desc Sid
  model: desc_sid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Description SID</p>
- disabled: false
  featured: false
  inputtype: text
  label: Cost
  model: cost
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Cost in AA Points</p>
- disabled: false
  featured: false
  inputtype: text
  label: Level Req
  model: level_req
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Level Required</p>
- disabled: false
  featured: false
  inputtype: text
  label: Spell
  model: spell
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="spells_new.md" target="_blank">Spell Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Spell Type
  model: spell_type
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/spells/spell-types" target="_blank">Spell Type</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Recast Time
  model: recast_time
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Recast Timer</p>
- disabled: false
  featured: false
  inputtype: text
  label: Expansion
  model: expansion
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/operation/expansion-list" target="_blank">Expansion Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Prev Id
  model: prev_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Previous Rank Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Next Id
  model: next_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Next Rank Identifier</p>
