- disabled: false
  featured: false
  inputtype: text
  label: Rank Id
  model: rank_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="aa_ranks.md" target="_blank">Rank Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Aa Id
  model: aa_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="aa_ability.md" target="_blank">AA Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Points
  model: points
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Cost in AA Points</p>
