- disabled: false
  featured: false
  inputtype: text
  label: Rank Id
  model: rank_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="aa_ranks.md" target="_blank">Rank Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Slot
  model: slot
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>AA Slot</p>
- disabled: false
  featured: false
  inputtype: text
  label: Effect Id
  model: effect_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/spells/spell-effect-ids" target="_blank">Spell Effect Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Base1
  model: base1
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>First Base Value</p>
- disabled: false
  featured: false
  inputtype: text
  label: Base2
  model: base2
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Second Base Value</p>
