- disabled: false
  featured: false
  inputtype: text
  label: P Accid
  model: p_accid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="account.md" target="_blank">Account Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: P Flag
  model: p_flag
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: P Value
  model: p_value
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Value</p>
