- disabled: false
  featured: false
  inputtype: text
  label: Accid
  model: accid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="account.md" target="_blank">Account Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Ip
  model: ip
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>IP Address</p>
- disabled: false
  featured: false
  inputtype: text
  label: Count
  model: count
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Number of times logged in from this IP</p>
- disabled: false
  featured: false
  inputtype: text
  label: Lastused
  model: lastused
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Timestamp of when account was last logged in</p>
