- disabled: false
  featured: false
  inputtype: text
  label: Account Id
  model: account_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="account.md" target="_blank">Account Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Reward Id
  model: reward_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="veteran_reward_templates.md" target="_blank">Veteran Reward Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Amount
  model: amount
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Amount</p>
