- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Account Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Name
  model: name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Charname
  model: charname
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Character name last logged in on this account.</p>
- disabled: false
  featured: false
  inputtype: text
  label: Sharedplat
  model: sharedplat
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Platinum in Shared Bank.</p>
- disabled: false
  featured: false
  inputtype: text
  label: Password
  model: password
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Private loginserver password.</p>
- disabled: false
  featured: false
  inputtype: text
  label: Status
  model: status
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/status-levels" target="_blank">Status</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Ls Id
  model: ls_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Lsaccount Id
  model: lsaccount_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Loginserver Account Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Gmspeed
  model: gmspeed
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>GM Speed: 0 = Disabled, 1 = Enabled</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Revoked
  model: revoked
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>OOC Revoked: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Karma
  model: karma
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Karma</p>
- disabled: false
  featured: false
  inputtype: text
  label: Minilogin Ip
  model: minilogin_ip
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Minilogin IP Address</p>
- disabled: false
  featured: false
  inputtype: text
  label: Hideme
  model: hideme
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Hide Me: 0 = Disabled, 1 = Enabled</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Rulesflag
  model: rulesflag
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Rules Flag</p>
- disabled: false
  featured: false
  inputtype: text
  label: Suspendeduntil
  model: suspendeduntil
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Time Suspension of the Account ends</p>
- disabled: false
  featured: false
  inputtype: text
  label: Time Creation
  model: time_creation
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Time Creation UNIX Timestamp</p>
- disabled: false
  featured: false
  inputtype: text
  label: Expansion
  model: expansion
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Expansion</p>
- disabled: false
  featured: false
  inputtype: text
  label: Ban Reason
  model: ban_reason
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Ban Reason</p>
- disabled: false
  featured: false
  inputtype: text
  label: Suspend Reason
  model: suspend_reason
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Suspension Reason</p>
