- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="adventure_details.md" target="_blank">Adventure Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Zone
  model: zone
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/zone-list" target="_blank">Zone Short Name</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Zone Version
  model: zone_version
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Zone Version</p>
- disabled: false
  featured: false
  inputtype: text
  label: Is Hard
  model: is_hard
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Hard: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Is Raid
  model: is_raid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Raid: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Min Level
  model: min_level
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Minimum Level</p>
- disabled: false
  featured: false
  inputtype: text
  label: Max Level
  model: max_level
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Maximum Level</p>
- disabled: false
  featured: false
  inputtype: text
  label: Type
  model: type
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Type</p>
- disabled: false
  featured: false
  inputtype: text
  label: Type Data
  model: type_data
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Type Data</p>
- disabled: false
  featured: false
  inputtype: text
  label: Type Count
  model: type_count
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Type Count</p>
- disabled: false
  featured: false
  inputtype: text
  label: Assa X
  model: assa_x
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Assassination X Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Assa Y
  model: assa_y
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Assassination Y Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Assa Z
  model: assa_z
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Assassination Z Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Assa H
  model: assa_h
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Assassination Heading Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Text
  model: text
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Text</p>
- disabled: false
  featured: false
  inputtype: text
  label: Duration
  model: duration
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Duration</p>
- disabled: false
  featured: false
  inputtype: text
  label: Zone In Time
  model: zone_in_time
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Zone In Duration</p>
- disabled: false
  featured: false
  inputtype: text
  label: Win Points
  model: win_points
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>LDoN Points for Winning</p>
- disabled: false
  featured: false
  inputtype: text
  label: Lose Points
  model: lose_points
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>LDoN Points for Losing</p>
- disabled: false
  featured: false
  inputtype: text
  label: Theme
  model: theme
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/ldon-themes" target="_blank">LDoN Theme</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Zone In Zone Id
  model: zone_in_zone_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/zone-list" target="_blank">Zone In Zone Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Zone In X
  model: zone_in_x
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Zone In X Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Zone In Y
  model: zone_in_y
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Zone In Y Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Zone In Object Id
  model: zone_in_object_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Zone In Object Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Dest X
  model: dest_x
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Destination X Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Dest Y
  model: dest_y
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Destination Y Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Dest Z
  model: dest_z
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Destination Z Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Dest H
  model: dest_h
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Destination Heading Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Graveyard Zone Id
  model: graveyard_zone_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/zone-list" target="_blank">Zone Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Graveyard X
  model: graveyard_x
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Graveyard X Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Graveyard Y
  model: graveyard_y
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Graveyard Y Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Graveyard Z
  model: graveyard_z
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Graveyard Z Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Graveyard Radius
  model: graveyard_radius
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Graveyard Radius</p>
