- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Entry Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Adventure Id
  model: adventure_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Adventure Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Instance Id
  model: instance_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="instance_list.md" target="_blank">Instance Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Count
  model: count
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Count</p>
- disabled: false
  featured: false
  inputtype: text
  label: Assassinate Count
  model: assassinate_count
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Assassinate Count</p>
- disabled: false
  featured: false
  inputtype: text
  label: Status
  model: status
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Status</p>
- disabled: false
  featured: false
  inputtype: text
  label: Time Created
  model: time_created
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Time Created UNIX Timestamp</p>
- disabled: false
  featured: false
  inputtype: text
  label: Time Zoned
  model: time_zoned
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Time Zoned UNIX Timestamp</p>
- disabled: false
  featured: false
  inputtype: text
  label: Time Completed
  model: time_completed
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Time Completed UNIX Timestamp</p>
