- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="adventure_details.md" target="_blank">Adventure Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Text
  model: text
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Text</p>
