- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="adventure_details.md" target="_blank">Adventure Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Template Id
  model: template_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="adventure_template.md" target="_blank">Template Identifier</a></p>
