- disabled: false
  featured: false
  inputtype: text
  label: Player Id
  model: player_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Guk Wins
  model: guk_wins
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Deepest Guk Wins</p>
- disabled: false
  featured: false
  inputtype: text
  label: Mir Wins
  model: mir_wins
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Miragul&rsquo;s Menagerie Wins</p>
- disabled: false
  featured: false
  inputtype: text
  label: Mmc Wins
  model: mmc_wins
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Mistmoore Catacombs Wins</p>
- disabled: false
  featured: false
  inputtype: text
  label: Ruj Wins
  model: ruj_wins
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Rujarkian Hills Wins</p>
- disabled: false
  featured: false
  inputtype: text
  label: Tak Wins
  model: tak_wins
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Takish-Hiz Wins</p>
- disabled: false
  featured: false
  inputtype: text
  label: Guk Losses
  model: guk_losses
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Deepest Guk Losses</p>
- disabled: false
  featured: false
  inputtype: text
  label: Mir Losses
  model: mir_losses
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Miragul&rsquo;s Menagerie Losses</p>
- disabled: false
  featured: false
  inputtype: text
  label: Mmc Losses
  model: mmc_losses
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Mistmoore Catacombs Losses</p>
- disabled: false
  featured: false
  inputtype: text
  label: Ruj Losses
  model: ruj_losses
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Rujarkian Hills Losses</p>
- disabled: false
  featured: false
  inputtype: text
  label: Tak Losses
  model: tak_losses
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Takish-Hiz Losses</p>
