- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/items/alternate-currencies" target="_blank">Alternate Currency Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Item Id
  model: item_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="items.md" target="_blank">Item Identifier</a></p>
