- disabled: false
  featured: false
  inputtype: text
  label: Type
  model: type
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Aura Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Npc Type
  model: npc_type
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="npc_types.md" target="_blank">NPC Type Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Name
  model: name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Spell Id
  model: spell_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="spells_new.md" target="_blank">Spell Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Distance
  model: distance
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Distance</p>
- disabled: false
  featured: false
  inputtype: text
  label: Aura Type
  model: aura_type
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/spells/aura-types" target="_blank">Aura Type</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Spawn Type
  model: spawn_type
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/spells/aura-spawn-types" target="_blank">Aura Spawn Type</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Movement
  model: movement
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/spells/aura-movement-types" target="_blank">Aura Movement Type</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Duration
  model: duration
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Duration</p>
- disabled: false
  featured: false
  inputtype: text
  label: Icon
  model: icon
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Icon</p>
- disabled: false
  featured: false
  inputtype: text
  label: Cast Time
  model: cast_time
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Cast Time</p>
