- disabled: false
  featured: false
  inputtype: text
  label: Ip Address
  model: ip_address
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="account_ip.md" target="_blank">IP Address</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Notes
  model: notes
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Ban reason</p>
