- disabled: false
  featured: false
  inputtype: text
  label: Level
  model: level
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Level</p>
- disabled: false
  featured: false
  inputtype: text
  label: Class
  model: class
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/class-list" target="_blank">Class Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Hp
  model: hp
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Health</p>
- disabled: false
  featured: false
  inputtype: text
  label: Mana
  model: mana
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Mana</p>
- disabled: false
  featured: false
  inputtype: text
  label: End
  model: end
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Endurance</p>
- disabled: false
  featured: false
  inputtype: text
  label: Unk1
  model: unk1
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unknown</p>
- disabled: false
  featured: false
  inputtype: text
  label: Unk2
  model: unk2
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unknown</p>
- disabled: false
  featured: false
  inputtype: text
  label: Hp Fac
  model: hp_fac
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Health Factor</p>
- disabled: false
  featured: false
  inputtype: text
  label: Mana Fac
  model: mana_fac
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Mana Factor</p>
- disabled: false
  featured: false
  inputtype: text
  label: End Fac
  model: end_fac
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Endurance Factor</p>
