- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Blocked Spells Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Spellid
  model: spellid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="spells_new.md" target="_blank">Spell Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Type
  model: type
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/spells/blocked-spell-types" target="_blank">Blocked Spell Type</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Zoneid
  model: zoneid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/zone-list" target="_blank">Zone Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: X
  model: x
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>X Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: "Y"
  model: "y"
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Y Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Z
  model: z
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Z Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: X Diff
  model: x_diff
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>X Radius</p>
- disabled: false
  featured: false
  inputtype: text
  label: Y Diff
  model: y_diff
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Y Radius</p>
- disabled: false
  featured: false
  inputtype: text
  label: Z Diff
  model: z_diff
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Z Radius</p>
- disabled: false
  featured: false
  inputtype: text
  label: Message
  model: message
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Message when blocked</p>
- disabled: false
  featured: false
  inputtype: text
  label: Description
  model: description
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Blocked spells description</p>
