- disabled: false
  featured: false
  inputtype: text
  label: Name
  model: name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Book Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Txtfile
  model: txtfile
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>The text in the book. <code>Represents line spaces,</code><code>is two line spaces,</code>&rdquo; is three line spaces, etc. (13 lines per book page)</p>
- disabled: false
  featured: false
  inputtype: text
  label: Language
  model: language
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/languages" target="_blank">Language</a></p>
