- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Bug Report Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Zone
  model: zone
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/zone-list" target="_blank">Zone Short Name</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Client Version Id
  model: client_version_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/client-version-bitmasks" target="_blank">Client Version Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Client Version Name
  model: client_version_name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/client-version-bitmasks" target="_blank">Client Version Name</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Account Id
  model: account_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="account.md" target="_blank">Account Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Character Id
  model: character_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Character Name
  model: character_name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Name</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Reporter Spoof
  model: reporter_spoof
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Reporter Spoof</p>
- disabled: false
  featured: false
  inputtype: text
  label: Category Id
  model: category_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Category Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Category Name
  model: category_name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Category Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Reporter Name
  model: reporter_name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Reporter Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Ui Path
  model: ui_path
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>UI Path</p>
- disabled: false
  featured: false
  inputtype: text
  label: Pos X
  model: pos_x
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Position X Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Pos Y
  model: pos_y
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Position Y Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Pos Z
  model: pos_z
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Position Z Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Heading
  model: heading
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Heading Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Time Played
  model: time_played
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Time Played in Seconds</p>
- disabled: false
  featured: false
  inputtype: text
  label: Target Id
  model: target_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Target Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Target Name
  model: target_name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Target Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Optional Info Mask
  model: optional_info_mask
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Optional Info Mask: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: ' Can Duplicate'
  model: _can_duplicate
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Can Duplicate: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: ' Crash Bug'
  model: _crash_bug
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Crash Bug</p>
- disabled: false
  featured: false
  inputtype: text
  label: ' Target Info'
  model: _target_info
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Target Info</p>
- disabled: false
  featured: false
  inputtype: text
  label: ' Character Flags'
  model: _character_flags
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Character Flags</p>
- disabled: false
  featured: false
  inputtype: text
  label: ' Unknown Value'
  model: _unknown_value
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unknown</p>
- disabled: false
  featured: false
  inputtype: text
  label: Bug Report
  model: bug_report
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Bug Report</p>
- disabled: false
  featured: false
  inputtype: text
  label: System Info
  model: system_info
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>System Information</p>
- disabled: false
  featured: false
  inputtype: text
  label: Report Datetime
  model: report_datetime
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Report Datetime</p>
- disabled: false
  featured: false
  inputtype: text
  label: Bug Status
  model: bug_status
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Bug Status</p>
- disabled: false
  featured: false
  inputtype: text
  label: Last Review
  model: last_review
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Last Review Datetime</p>
- disabled: false
  featured: false
  inputtype: text
  label: Last Reviewer
  model: last_reviewer
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Last Reviewer</p>
- disabled: false
  featured: false
  inputtype: text
  label: Reviewer Notes
  model: reviewer_notes
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Reviewer Notes</p>
