- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Bug Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Zone
  model: zone
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/zone-list" target="_blank">Zone Short Name</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Name
  model: name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Player Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Ui
  model: ui
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>UI</p>
- disabled: false
  featured: false
  inputtype: text
  label: X
  model: x
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>X Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: "Y"
  model: "y"
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Y Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Z
  model: z
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Z Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Type
  model: type
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Type</p>
- disabled: false
  featured: false
  inputtype: text
  label: Flag
  model: flag
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Flag</p>
- disabled: false
  featured: false
  inputtype: text
  label: Target
  model: target
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Target when reported</p>
- disabled: false
  featured: false
  inputtype: text
  label: Bug
  model: bug
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Bug reported</p>
- disabled: false
  featured: false
  inputtype: text
  label: Date
  model: date
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Date when reported</p>
- disabled: false
  featured: false
  inputtype: text
  label: Status
  model: status
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>[Account Status of Reporter](<a href="https://eqemu.gitbook.io/server/categories/player/status-levels" target="_blank">https://eqemu.gitbook.io/server/categories/player/status-levels</a></p>
