- disabled: false
  featured: false
  inputtype: text
  label: Charid
  model: charid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Buyslot
  model: buyslot
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Slot</p>
- disabled: false
  featured: false
  inputtype: text
  label: Itemid
  model: itemid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="items.md" target="_blank">Item Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Itemname
  model: itemname
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="items.md" target="_blank">Item Name</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Quantity
  model: quantity
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Quantity</p>
- disabled: false
  featured: false
  inputtype: text
  label: Price
  model: price
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Price</p>
