- disabled: false
  featured: false
  inputtype: text
  label: Corpse Id
  model: corpse_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_corpses.md" target="_blank">Corpse Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Equip Slot
  model: equip_slot
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Equipment Slot</p>
- disabled: false
  featured: false
  inputtype: text
  label: Item Id
  model: item_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="items.md" target="_blank">Item Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Charges
  model: charges
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Item Charges</p>
- disabled: false
  featured: false
  inputtype: text
  label: Aug 1
  model: aug_1
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Item Augment Slot 1</p>
- disabled: false
  featured: false
  inputtype: text
  label: Aug 2
  model: aug_2
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Item Augment Slot 2</p>
- disabled: false
  featured: false
  inputtype: text
  label: Aug 3
  model: aug_3
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Item Augment Slot 3</p>
- disabled: false
  featured: false
  inputtype: text
  label: Aug 4
  model: aug_4
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Item Augment Slot 4</p>
- disabled: false
  featured: false
  inputtype: text
  label: Aug 5
  model: aug_5
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Item Augment Slot 5</p>
- disabled: false
  featured: false
  inputtype: text
  label: Aug 6
  model: aug_6
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Item Augment Slot 6</p>
- disabled: false
  featured: false
  inputtype: text
  label: Attuned
  model: attuned
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Item Attuned: 0 = False, 1 = True</p>'
