- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Allocation Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Base Str
  model: base_str
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Base Strength</p>
- disabled: false
  featured: false
  inputtype: text
  label: Base Sta
  model: base_sta
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Base Stamina</p>
- disabled: false
  featured: false
  inputtype: text
  label: Base Dex
  model: base_dex
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Base Dexterity</p>
- disabled: false
  featured: false
  inputtype: text
  label: Base Agi
  model: base_agi
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Base Agility</p>
- disabled: false
  featured: false
  inputtype: text
  label: Base Int
  model: base_int
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Base Intelligence</p>
- disabled: false
  featured: false
  inputtype: text
  label: Base Wis
  model: base_wis
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Base Wisdom</p>
- disabled: false
  featured: false
  inputtype: text
  label: Base Cha
  model: base_cha
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Base Charisma</p>
- disabled: false
  featured: false
  inputtype: text
  label: Alloc Str
  model: alloc_str
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Allocated Strength</p>
- disabled: false
  featured: false
  inputtype: text
  label: Alloc Sta
  model: alloc_sta
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Allocated Stamina</p>
- disabled: false
  featured: false
  inputtype: text
  label: Alloc Dex
  model: alloc_dex
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Allocated Dexterity</p>
- disabled: false
  featured: false
  inputtype: text
  label: Alloc Agi
  model: alloc_agi
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Allocated Agility</p>
- disabled: false
  featured: false
  inputtype: text
  label: Alloc Int
  model: alloc_int
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Allocated Intelligence</p>
- disabled: false
  featured: false
  inputtype: text
  label: Alloc Wis
  model: alloc_wis
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Allocated Wisdom</p>
- disabled: false
  featured: false
  inputtype: text
  label: Alloc Cha
  model: alloc_cha
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Allocated Charisma</p>
