- disabled: false
  featured: false
  inputtype: text
  label: Character Id
  model: character_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Slot Id
  model: slot_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Buff Slot</p>
- disabled: false
  featured: false
  inputtype: text
  label: Spell Id
  model: spell_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="spells_new.md" target="_blank">Buff Spell Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Caster Level
  model: caster_level
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Caster Level</p>
- disabled: false
  featured: false
  inputtype: text
  label: Caster Name
  model: caster_name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Caster Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Ticsremaining
  model: ticsremaining
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Tics Remaining</p>
- disabled: false
  featured: false
  inputtype: text
  label: Counters
  model: counters
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Counters</p>
- disabled: false
  featured: false
  inputtype: text
  label: Numhits
  model: numhits
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Number of Hits</p>
- disabled: false
  featured: false
  inputtype: text
  label: Melee Rune
  model: melee_rune
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Melee Rune</p>
- disabled: false
  featured: false
  inputtype: text
  label: Magic Rune
  model: magic_rune
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Magic Rune</p>
- disabled: false
  featured: false
  inputtype: text
  label: Persistent
  model: persistent
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Persistent: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Dot Rune
  model: dot_rune
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Damage Over Time Rune</p>
- disabled: false
  featured: false
  inputtype: text
  label: Caston X
  model: caston_x
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>X Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Caston Y
  model: caston_y
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Y Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Caston Z
  model: caston_z
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Z Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: ExtraDIChance
  model: ExtraDIChance
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Extra DI Chance</p>
- disabled: false
  featured: false
  inputtype: text
  label: Instrument Mod
  model: instrument_mod
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Instrument Modifier</p>
