- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Bandolier Id
  model: bandolier_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Bandolier Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Bandolier Slot
  model: bandolier_slot
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Slot</p>
- disabled: false
  featured: false
  inputtype: text
  label: Item Id
  model: item_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="items.md" target="_blank">Item Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Icon
  model: icon
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Icon</p>
- disabled: false
  featured: false
  inputtype: text
  label: Bandolier Name
  model: bandolier_name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Name</p>
