- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Platinum
  model: platinum
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Platinum</p>
- disabled: false
  featured: false
  inputtype: text
  label: Gold
  model: gold
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Gold</p>
- disabled: false
  featured: false
  inputtype: text
  label: Silver
  model: silver
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Silver</p>
- disabled: false
  featured: false
  inputtype: text
  label: Copper
  model: copper
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Copper</p>
- disabled: false
  featured: false
  inputtype: text
  label: Platinum Bank
  model: platinum_bank
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Banked Platinum</p>
- disabled: false
  featured: false
  inputtype: text
  label: Gold Bank
  model: gold_bank
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Banked Gold</p>
- disabled: false
  featured: false
  inputtype: text
  label: Silver Bank
  model: silver_bank
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Banked Silver</p>
- disabled: false
  featured: false
  inputtype: text
  label: Copper Bank
  model: copper_bank
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Banked Copper</p>
- disabled: false
  featured: false
  inputtype: text
  label: Platinum Cursor
  model: platinum_cursor
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Cursor Platinum</p>
- disabled: false
  featured: false
  inputtype: text
  label: Gold Cursor
  model: gold_cursor
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Cursor Gold</p>
- disabled: false
  featured: false
  inputtype: text
  label: Silver Cursor
  model: silver_cursor
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Cursor Silver</p>
- disabled: false
  featured: false
  inputtype: text
  label: Copper Cursor
  model: copper_cursor
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Cursor Copper</p>
- disabled: false
  featured: false
  inputtype: text
  label: Radiant Crystals
  model: radiant_crystals
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Radiant Crystals</p>
- disabled: false
  featured: false
  inputtype: text
  label: Career Radiant Crystals
  model: career_radiant_crystals
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Career Radiant Crystals</p>
- disabled: false
  featured: false
  inputtype: text
  label: Ebon Crystals
  model: ebon_crystals
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Ebon Crystals</p>
- disabled: false
  featured: false
  inputtype: text
  label: Career Ebon Crystals
  model: career_ebon_crystals
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Career Ebon Crystals</p>
