- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Tier
  model: tier
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Tier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Tribute
  model: tribute
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Tribute</p>
