- disabled: false
  featured: false
  inputtype: text
  label: Allocation Id
  model: allocation_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="char_create_point_allocations.md" target="_blank">Allocation Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Race
  model: race
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/npc/race-list" target="_blank">Race</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Class
  model: class
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/class-list" target="_blank">Class</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Deity
  model: deity
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/deity-list" target="_blank">Deity</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Start Zone
  model: start_zone
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/zone-list" target="_blank">Start Zone Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Expansions Req
  model: expansions_req
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/operation/expansion-bitmasks" target="_blank">Expansions Required</a></p>
