- disabled: false
  featured: false
  inputtype: text
  label: Charid
  model: charid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Taskid
  model: taskid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="tasks.md" target="_blank">Task Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Slot
  model: slot
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Slot</p>
- disabled: false
  featured: false
  inputtype: text
  label: Type
  model: type
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/task-system-guide/task-types" target="_blank">Task Type</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Acceptedtime
  model: acceptedtime
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Accepted Time UNIX Timestamp</p>
