- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Corpse Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Charid
  model: charid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Charname
  model: charname
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Character Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Zone Id
  model: zone_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/zone-list" target="_blank">Zone Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Instance Id
  model: instance_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Instance Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: X
  model: x
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>X Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: "Y"
  model: "y"
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Y Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Z
  model: z
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Z Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Heading
  model: heading
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Heading Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Time Of Death
  model: time_of_death
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Time of Death</p>
- disabled: false
  featured: false
  inputtype: text
  label: Guild Consent Id
  model: guild_consent_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Is Rezzed
  model: is_rezzed
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Is Rezzed: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Is Buried
  model: is_buried
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Is Buried: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Was At Graveyard
  model: was_at_graveyard
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Was At Graveyard: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Is Locked
  model: is_locked
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Is Locked: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Exp
  model: exp
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Experience</p>
- disabled: false
  featured: false
  inputtype: text
  label: Size
  model: size
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Size</p>
- disabled: false
  featured: false
  inputtype: text
  label: Level
  model: level
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Level</p>
- disabled: false
  featured: false
  inputtype: text
  label: Race
  model: race
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/npc/race-list" target="_blank">Race</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Gender
  model: gender
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/npc/genders" target="_blank">Gender</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Class
  model: class
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/class-list" target="_blank">Class</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Deity
  model: deity
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/deity-list" target="_blank">Deity</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Texture
  model: texture
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/npc/textures" target="_blank">Texture</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Helm Texture
  model: helm_texture
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/npc/textures" target="_blank">Helm Texture</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Copper
  model: copper
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Copper</p>
- disabled: false
  featured: false
  inputtype: text
  label: Silver
  model: silver
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Silver</p>
- disabled: false
  featured: false
  inputtype: text
  label: Gold
  model: gold
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Gold</p>
- disabled: false
  featured: false
  inputtype: text
  label: Platinum
  model: platinum
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Platinum</p>
- disabled: false
  featured: false
  inputtype: text
  label: Hair Color
  model: hair_color
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Hair Color</p>
- disabled: false
  featured: false
  inputtype: text
  label: Beard Color
  model: beard_color
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Beard Color</p>
- disabled: false
  featured: false
  inputtype: text
  label: Eye Color 1
  model: eye_color_1
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Eye Color 1</p>
- disabled: false
  featured: false
  inputtype: text
  label: Eye Color 2
  model: eye_color_2
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Eye Color 2</p>
- disabled: false
  featured: false
  inputtype: text
  label: Hair Style
  model: hair_style
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Hair Style</p>
- disabled: false
  featured: false
  inputtype: text
  label: Face
  model: face
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Face</p>
- disabled: false
  featured: false
  inputtype: text
  label: Beard
  model: beard
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Beard</p>
- disabled: false
  featured: false
  inputtype: text
  label: Drakkin Heritage
  model: drakkin_heritage
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Drakkin Heritage</p>
- disabled: false
  featured: false
  inputtype: text
  label: Drakkin Tattoo
  model: drakkin_tattoo
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Drakkin Tattoo</p>
- disabled: false
  featured: false
  inputtype: text
  label: Drakkin Details
  model: drakkin_details
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Drakkin Details</p>
- disabled: false
  featured: false
  inputtype: text
  label: Wc 1
  model: wc_1
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Wear Change 1</p>
- disabled: false
  featured: false
  inputtype: text
  label: Wc 2
  model: wc_2
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Wear Change 2</p>
- disabled: false
  featured: false
  inputtype: text
  label: Wc 3
  model: wc_3
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Wear Change 3</p>
- disabled: false
  featured: false
  inputtype: text
  label: Wc 4
  model: wc_4
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Wear Change 4</p>
- disabled: false
  featured: false
  inputtype: text
  label: Wc 5
  model: wc_5
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Wear Change 5</p>
- disabled: false
  featured: false
  inputtype: text
  label: Wc 6
  model: wc_6
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Wear Change 6</p>
- disabled: false
  featured: false
  inputtype: text
  label: Wc 7
  model: wc_7
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Wear Change 7</p>
- disabled: false
  featured: false
  inputtype: text
  label: Wc 8
  model: wc_8
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Wear Change 8</p>
- disabled: false
  featured: false
  inputtype: text
  label: Wc 9
  model: wc_9
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Wear Change 9</p>
