- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Inspect Message
  model: inspect_message
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Inspect Message</p>
