- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Unique Character Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Slot
  model: slot
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Slot</p>
- disabled: false
  featured: false
  inputtype: text
  label: Spell Id
  model: spell_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="spells_new.md" target="_blank">Spell Identifier</a></p>
