- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Aa Id
  model: aa_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="aa_ability.md" target="_blank">AA Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Aa Value
  model: aa_value
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>AA Value</p>
- disabled: false
  featured: false
  inputtype: text
  label: Charges
  model: charges
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Charges</p>
