- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Slot
  model: slot
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Slot</p>
- disabled: false
  featured: false
  inputtype: text
  label: Blue
  model: blue
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Blue: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Green
  model: green
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Green: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Red
  model: red
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Red: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Use Tint
  model: use_tint
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Tint: 0 = None, 255 = MAx</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Color
  model: color
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Color</p>
