- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Recast Type
  model: recast_type
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Recast Type</p>
- disabled: false
  featured: false
  inputtype: text
  label: Timestamp
  model: timestamp
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Recast Timestamp</p>
