- disabled: false
  featured: false
  inputtype: text
  label: Char Id
  model: char_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Recipe Id
  model: recipe_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="tradeskill_recipe.md" target="_blank">Recipe Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Madecount
  model: madecount
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Made Count</p>
