- disabled: false
  featured: false
  inputtype: text
  label: Name
  model: name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Owner
  model: owner
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Owner Character Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Password
  model: password
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Password</p>
- disabled: false
  featured: false
  inputtype: text
  label: Minstatus
  model: minstatus
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/status-levels" target="_blank">Minimum Status</a></p>
