- disabled: false
  featured: false
  inputtype: text
  label: Command
  model: command
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Command Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Access
  model: access
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/status-levels" target="_blank">Required Status</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Aliases
  model: aliases
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Aliases</p>
