- disabled: false
  featured: false
  inputtype: text
  label: Charid
  model: charid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Completedtime
  model: completedtime
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Completed Time UNIX Timestamp</p>
- disabled: false
  featured: false
  inputtype: text
  label: Taskid
  model: taskid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="tasks.md" target="_blank">Task Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Activityid
  model: activityid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="task_activities.md" target="_blank">Activity Identifier</a></p>
