- disabled: false
  featured: false
  inputtype: text
  label: Spellid
  model: spellid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="spells_new.md" target="_blank">Spell Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Type
  model: type
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/spells/damage-shield-types" target="_blank">Damage Shield Type</a></p>
