- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Database String Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Type
  model: type
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Type</p>
- disabled: false
  featured: false
  inputtype: text
  label: Value
  model: value
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Value</p>
