- disabled: false
  featured: false
  inputtype: text
  label: Minute
  model: minute
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Minute</p>
- disabled: false
  featured: false
  inputtype: text
  label: Hour
  model: hour
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Hour</p>
- disabled: false
  featured: false
  inputtype: text
  label: Day
  model: day
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Day</p>
- disabled: false
  featured: false
  inputtype: text
  label: Month
  model: month
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Month</p>
- disabled: false
  featured: false
  inputtype: text
  label: Year
  model: year
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Year</p>
- disabled: false
  featured: false
  inputtype: text
  label: Realtime
  model: realtime
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Real Time</p>
