- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Event Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Accountname
  model: accountname
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="account.md" target="_blank">Account Name</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Accountid
  model: accountid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="account.md" target="_blank">Account Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Status
  model: status
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/status-levels" target="_blank">Status</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Charname
  model: charname
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Name</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Target
  model: target
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Target</p>
- disabled: false
  featured: false
  inputtype: text
  label: Time
  model: time
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>TIme Timestamp</p>
- disabled: false
  featured: false
  inputtype: text
  label: Descriptiontype
  model: descriptiontype
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Description Type</p>
- disabled: false
  featured: false
  inputtype: text
  label: Description
  model: description
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Description</p>
- disabled: false
  featured: false
  inputtype: text
  label: Event Nid
  model: event_nid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Event Identifier</p>
