- disabled: false
  featured: false
  inputtype: text
  label: Client Faction Id
  model: client_faction_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="faction_list.md" target="_blank">Client Faction Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Min
  model: min
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Minimum Faction</p>
- disabled: false
  featured: false
  inputtype: text
  label: Max
  model: max
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Maximum Faction</p>
- disabled: false
  featured: false
  inputtype: text
  label: Unk Hero1
  model: unk_hero1
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unknown</p>
- disabled: false
  featured: false
  inputtype: text
  label: Unk Hero2
  model: unk_hero2
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unknown</p>
- disabled: false
  featured: false
  inputtype: text
  label: Unk Hero3
  model: unk_hero3
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unknown</p>
