- disabled: false
  featured: false
  inputtype: text
  label: Char Id
  model: char_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Faction Id
  model: faction_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="faction_list.md" target="_blank">Faction Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Current Value
  model: current_value
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Current Value</p>
- disabled: false
  featured: false
  inputtype: text
  label: Temp
  model: temp
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Temporary: 0 = False, 1 = True</p>'
