- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Faction List Modifier Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Faction Id
  model: faction_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="faction_list.md" target="_blank">Faction Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Mod
  model: mod
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Modifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Mod Name
  model: mod_name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Modifier Name: r# = <a href="https://eqemu.gitbook.io/server/categories/npc/race-list" target="_blank">Race Identifier</a>, c# = <a href="https://eqemu.gitbook.io/server/categories/player/class-list" target="_blank">Class Identifier</a>, d# = <a href="https://eqemu.gitbook.io/server/categories/player/deity-list" target="_blank">Deity Identifier</a></p>'
