- disabled: false
  featured: false
  inputtype: text
  label: Name
  model: name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Name</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Account Id
  model: account_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="account.md" target="_blank">Account Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Ip Address
  model: ip_address
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="account_ip.md" target="_blank">IP Address</a></p>
