- disabled: false
  featured: false
  inputtype: text
  label: Listid
  model: listid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Goal List Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Entry
  model: entry
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Entry Identifier</p>
