- disabled: false
  featured: false
  inputtype: text
  label: Gridid
  model: gridid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="grid.md" target="_blank">Grid Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Zoneid
  model: zoneid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/zone-list" target="_blank">Zone Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Number
  model: number
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Waypoint Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: X
  model: x
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>X Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: "Y"
  model: "y"
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Y Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Z
  model: z
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Z Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Heading
  model: heading
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Heading Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Pause
  model: pause
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Pause in Seconds</p>
- disabled: false
  featured: false
  inputtype: text
  label: Centerpoint
  model: centerpoint
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
