- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Grid Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Zoneid
  model: zoneid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/zone-list" target="_blank">Zone Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Type
  model: type
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/npc/spawns/wander-types" target="_blank">Wander Type</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Type2
  model: type2
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/npc/spawns/pause-types" target="_blank">Pause Type</a></p>
