- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Ground Spawn Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Zoneid
  model: zoneid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/zone-list" target="_blank">Zone Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Version
  model: version
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Version: -1 For All</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Max X
  model: max_x
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Maximum X Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Max Y
  model: max_y
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Maximum Y Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Max Z
  model: max_z
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Maximum Z Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Min X
  model: min_x
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Minimum X Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Min Y
  model: min_y
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Minimum Y Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Heading
  model: heading
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Heading Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Name
  model: name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Item
  model: item
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="items.md" target="_blank">Item Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Max Allowed
  model: max_allowed
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Max Allowed</p>
- disabled: false
  featured: false
  inputtype: text
  label: Comment
  model: comment
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Comment</p>
- disabled: false
  featured: false
  inputtype: text
  label: Respawn Timer
  model: respawn_timer
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Respawn Timer in Seconds</p>
- disabled: false
  featured: false
  inputtype: text
  label: Min Expansion
  model: min_expansion
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Max Expansion
  model: max_expansion
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Content Flags
  model: content_flags
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Content Flags Disabled
  model: content_flags_disabled
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
