- disabled: false
  featured: false
  inputtype: text
  label: Groupid
  model: groupid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Group Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Charid
  model: charid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Name
  model: name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Ismerc
  model: ismerc
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Is Mercenary: 0 = False, 1 = True</p>'
