- disabled: false
  featured: false
  inputtype: text
  label: Guild Id
  model: guild_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="guilds.md" target="_blank">Guild Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Rank
  model: rank
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Rank Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Title
  model: title
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Title</p>
- disabled: false
  featured: false
  inputtype: text
  label: Can Hear
  model: can_hear
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Can Hear: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Can Speak
  model: can_speak
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Can Speak: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Can Invite
  model: can_invite
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Can Invite: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Can Remove
  model: can_remove
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Can Remove: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Can Promote
  model: can_promote
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Can Promote: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Can Demote
  model: can_demote
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Can Demote: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Can Motd
  model: can_motd
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Can MOTD: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Can Warpeace
  model: can_warpeace
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Can War Peace: 0 = False, 1 = True</p>'
