- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Guild Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Name
  model: name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Leader
  model: leader
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Minstatus
  model: minstatus
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/status-levels" target="_blank">Minimum Status</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Motd
  model: motd
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Message of the Day</p>
- disabled: false
  featured: false
  inputtype: text
  label: Tribute
  model: tribute
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Tribute</p>
- disabled: false
  featured: false
  inputtype: text
  label: Motd Setter
  model: motd_setter
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Channel
  model: channel
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Channel</p>
- disabled: false
  featured: false
  inputtype: text
  label: Url
  model: url
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Website URL</p>
