- disabled: false
  featured: false
  inputtype: text
  label: Guild1
  model: guild1
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="guilds.md" target="_blank">Unique Guild Identifier 1</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Guild2
  model: guild2
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="guilds.md" target="_blank">Unique Guild Identifier 2</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Relation
  model: relation
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
