- disabled: false
  featured: false
  inputtype: text
  label: Guildid
  model: guildid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="guilds.md" target="_blank">Guild Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Area
  model: area
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Area</p>
- disabled: false
  featured: false
  inputtype: text
  label: Slot
  model: slot
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Slot Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Itemid
  model: itemid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="items.md" target="_blank">Item Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Qty
  model: qty
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Quantity</p>
- disabled: false
  featured: false
  inputtype: text
  label: Donator
  model: donator
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Permissions
  model: permissions
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Permissions</p>
- disabled: false
  featured: false
  inputtype: text
  label: Whofor
  model: whofor
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Who For</p>
