- disabled: false
  featured: false
  inputtype: text
  label: Char Id
  model: char_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Guild Id
  model: guild_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="guilds.md" target="_blank">Guild Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Rank
  model: rank
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/guild-ranks" target="_blank">Rank</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Tribute Enable
  model: tribute_enable
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Tribute Enable: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Total Tribute
  model: total_tribute
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Total Tribute</p>
- disabled: false
  featured: false
  inputtype: text
  label: Last Tribute
  model: last_tribute
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Last Tribute</p>
- disabled: false
  featured: false
  inputtype: text
  label: Banker
  model: banker
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Banked: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Public Note
  model: public_note
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Public Note</p>
- disabled: false
  featured: false
  inputtype: text
  label: Alt
  model: alt
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Alt: 0 = False, 1 = True</p>'
