- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Hacker Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Account
  model: account
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="account.md" target="_blank">Account Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Name
  model: name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Name</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Hacked
  model: hacked
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Hacked</p>
- disabled: false
  featured: false
  inputtype: text
  label: Zone
  model: zone
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/zone-list" target="_blank">Zone Short Name</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Date
  model: date
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Date Timestamp</p>
