- disabled: false
  featured: false
  inputtype: text
  label: Filename
  model: filename
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="npc_types.md" target="_blank">NPC Type Name</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Race
  model: race
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/npc/race-list" target="_blank">Race</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Gender
  model: gender
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/npc/genders" target="_blank">Gender</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Texture
  model: texture
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/npc/textures" target="_blank">Texture</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Mountspeed
  model: mountspeed
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Mount Run Speed</p>
- disabled: false
  featured: false
  inputtype: text
  label: Notes
  model: notes
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Notes</p>
