- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="instance_list.md" target="_blank">Instance Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Charid
  model: charid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Identifier</a></p>
