- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Instance Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Zone
  model: zone
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/zone-list" target="_blank">Zone Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Version
  model: version
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Version</p>
- disabled: false
  featured: false
  inputtype: text
  label: Is Global
  model: is_global
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Is Global: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Start Time
  model: start_time
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Start Time UNIX Timestamp</p>
- disabled: false
  featured: false
  inputtype: text
  label: Duration
  model: duration
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Duration in Seconds</p>
- disabled: false
  featured: false
  inputtype: text
  label: Never Expires
  model: never_expires
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Never Expires: 0 = False, 1 = True</p>'
