- disabled: false
  featured: false
  inputtype: text
  label: Version
  model: version
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Inventory Version Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Step
  model: step
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Step</p>
- disabled: false
  featured: false
  inputtype: text
  label: Bot Step
  model: bot_step
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Bot Step</p>
