- disabled: false
  featured: false
  inputtype: text
  label: Exemption Id
  model: exemption_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Exemption Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Exemption Ip
  model: exemption_ip
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="account_ip.md" target="_blank">Exemption IP Address</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Exemption Amount
  model: exemption_amount
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Exemption Amount</p>
