- disabled: false
  featured: false
  inputtype: text
  label: It Itemid
  model: it_itemid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="items.md" target="_blank">Item Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: It Chance
  model: it_chance
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Chance: 0 = Never, 100 = Always</p>'
- disabled: false
  featured: false
  inputtype: text
  label: It Level
  model: it_level
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Level</p>
- disabled: false
  featured: false
  inputtype: text
  label: It Id
  model: it_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="spells_new.md" target="_blank">Spell Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: It Qglobal
  model: it_qglobal
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="quest_globals.md" target="_blank">Quest Global Identifier</a> (Deprecated)</p>
- disabled: false
  featured: false
  inputtype: text
  label: It Bagslot
  model: it_bagslot
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/inventory/inventory-slots" target="_blank">Bag Slot</a></p>
