- disabled: false
  featured: false
  inputtype: text
  label: Name
  model: name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Dynamics
  model: dynamics
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Dynamics</p>
