- disabled: false
  featured: false
  inputtype: text
  label: Launcher
  model: launcher
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Launcher</p>
- disabled: false
  featured: false
  inputtype: text
  label: Zone
  model: zone
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/zone-list" target="_blank">Zone Short Name</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Port
  model: port
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Port</p>
