- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique LDoN Trap Template Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Type
  model: type
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/trap-types" target="_blank">Trap Type</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Spell Id
  model: spell_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="spells_new.md" target="_blank">Spell Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Skill
  model: skill
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/skills" target="_blank">Skill</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Locked
  model: locked
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Locked: 0 = False, 1 = True</p>'
