- disabled: false
  featured: false
  inputtype: text
  label: Level
  model: level
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Level</p>
- disabled: false
  featured: false
  inputtype: text
  label: Exp Mod
  model: exp_mod
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Experience Modifier: 0.5 = 50%, 1 = 100%, 1.5 = 150%</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Aa Exp Mod
  model: aa_exp_mod
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>AA Experience Modifier: 0.5 = 50%, 1 = 100%, 1.5 = 150%</p>'
