- disabled: false
  featured: false
  inputtype: text
  label: Type
  model: type
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Type</p>
- disabled: false
  featured: false
  inputtype: text
  label: Name
  model: name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Comment
  model: comment
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Comment</p>
- disabled: false
  featured: false
  inputtype: text
  label: Fromlevel
  model: fromlevel
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>From Level</p>
- disabled: false
  featured: false
  inputtype: text
  label: Tolevel
  model: tolevel
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>To Level</p>
- disabled: false
  featured: false
  inputtype: text
  label: Classes
  model: classes
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/class-list" target="_blank">Classes</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Aacount
  model: aacount
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>AA Count</p>
- disabled: false
  featured: false
  inputtype: text
  label: Timezone
  model: timezone
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Time Zone</p>
- disabled: false
  featured: false
  inputtype: text
  label: Timeposted
  model: timeposted
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Time Posted UNIX Timestamp</p>
