- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Account Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Account Name
  model: account_name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="account.md" target="_blank">Account Name</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Account Password
  model: account_password
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Account Password</p>
- disabled: false
  featured: false
  inputtype: text
  label: Account Email
  model: account_email
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Account Email</p>
- disabled: false
  featured: false
  inputtype: text
  label: Source Loginserver
  model: source_loginserver
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Source Loginserver</p>
- disabled: false
  featured: false
  inputtype: text
  label: Last Ip Address
  model: last_ip_address
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="account_ip.md" target="_blank">Last IP Address</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Last Login Date
  model: last_login_date
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Last Login Date</p>
- disabled: false
  featured: false
  inputtype: text
  label: Created At
  model: created_at
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Created At Date</p>
- disabled: false
  featured: false
  inputtype: text
  label: Updated At
  model: updated_at
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Updated At Date</p>
