- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique World Server Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Long Name
  model: long_name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Long Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Short Name
  model: short_name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Short Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Tag Description
  model: tag_description
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Tag Description</p>
- disabled: false
  featured: false
  inputtype: text
  label: Login Server List Type Id
  model: login_server_list_type_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="login_server_list_types.md" target="_blank">List Type Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Last Login Date
  model: last_login_date
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Last Login Date</p>
- disabled: false
  featured: false
  inputtype: text
  label: Last Ip Address
  model: last_ip_address
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Last IP Address</p>
- disabled: false
  featured: false
  inputtype: text
  label: Login Server Admin Id
  model: login_server_admin_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="login_server_admins.md" target="_blank">Login Server Admin Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Is Server Trusted
  model: is_server_trusted
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Is Server Trusted: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Note
  model: note
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Note</p>
