- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique List Type Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Description
  model: description
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Description</p>
