- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Login API Token Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Token
  model: token
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Token Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Can Write
  model: can_write
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Can Write: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Can Read
  model: can_read
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Can Read: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Created At
  model: created_at
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Created At Date</p>
- disabled: false
  featured: false
  inputtype: text
  label: Updated At
  model: updated_at
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Updated At Date</p>
