- disabled: false
  featured: false
  inputtype: text
  label: Log Category Id
  model: log_category_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Log Category Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Log Category Description
  model: log_category_description
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Log Category Description</p>
- disabled: false
  featured: false
  inputtype: text
  label: Log To Console
  model: log_to_console
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Log to Console: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Log To File
  model: log_to_file
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Log to File: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Log To Gmsay
  model: log_to_gmsay
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Log to GMSay: 0 = False, 1 = True</p>'
