- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Loottable Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Name
  model: name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Mincash
  model: mincash
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Minimum Cash in Copper</p>
- disabled: false
  featured: false
  inputtype: text
  label: Maxcash
  model: maxcash
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Maximum Cash in Copper</p>
- disabled: false
  featured: false
  inputtype: text
  label: Avgcoin
  model: avgcoin
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Average Coin in Copper</p>
- disabled: false
  featured: false
  inputtype: text
  label: Done
  model: done
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Done: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Min Expansion
  model: min_expansion
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Max Expansion
  model: max_expansion
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Content Flags
  model: content_flags
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Content Flags Disabled
  model: content_flags_disabled
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
