- disabled: false
  featured: false
  inputtype: text
  label: Loottable Id
  model: loottable_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="loottable.md" target="_blank">Loottable Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Lootdrop Id
  model: lootdrop_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="lootdrop.md" target="_blank">Lootdrop Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Multiplier
  model: multiplier
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Multiplier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Droplimit
  model: droplimit
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Maximum Drops</p>
- disabled: false
  featured: false
  inputtype: text
  label: Mindrop
  model: mindrop
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Minimum Drops</p>
- disabled: false
  featured: false
  inputtype: text
  label: Probability
  model: probability
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Probability: 0 = Never, 100 = Always</p>'
