- disabled: false
  featured: false
  inputtype: text
  label: Msgid
  model: msgid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Message Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Charid
  model: charid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Timestamp
  model: timestamp
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>UNIX Timestamp</p>
- disabled: false
  featured: false
  inputtype: text
  label: From
  model: from
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">From Character Name</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Subject
  model: subject
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Subject</p>
- disabled: false
  featured: false
  inputtype: text
  label: Body
  model: body
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Body</p>
- disabled: false
  featured: false
  inputtype: text
  label: To
  model: to
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">To Character Name</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Status
  model: status
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/status-levels" target="_blank">Status</a></p>
