- disabled: false
  featured: false
  inputtype: text
  label: Merchantid
  model: merchantid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Merchant Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Slot
  model: slot
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Slot</p>
- disabled: false
  featured: false
  inputtype: text
  label: Item
  model: item
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="items.md" target="_blank">Item Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Faction Required
  model: faction_required
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Faction Required</p>
- disabled: false
  featured: false
  inputtype: text
  label: Level Required
  model: level_required
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Level Required</p>
- disabled: false
  featured: false
  inputtype: text
  label: Alt Currency Cost
  model: alt_currency_cost
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="alternate_currency.md" target="_blank">Alternate Currency Cost</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Classes Required
  model: classes_required
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/class-list" target="_blank">Classes Required</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Probability
  model: probability
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Probability: 0 = Never, 100 = Always</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Min Expansion
  model: min_expansion
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Max Expansion
  model: max_expansion
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Content Flags
  model: content_flags
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Content Flags Disabled
  model: content_flags_disabled
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
