- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Name Filter Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Name
  model: name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Name</p>
