- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique NPC Faction Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Name
  model: name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Primaryfaction
  model: primaryfaction
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="faction_list.md" target="_blank">Primary Faction Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Ignore Primary Assist
  model: ignore_primary_assist
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Ignore Primary Assist: 0 = False, &gt;0 = True</p>'
