- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique NPC Emote Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Emoteid
  model: emoteid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Emote Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: 'Event '
  model: event_
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/npc/emote-event-types" target="_blank">Emote Event Type Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Type
  model: type
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/npc/emote-types" target="_blank">Emote Type Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Text
  model: text
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Text</p>
