- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique NPC Type Tint Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Tint Set Name
  model: tint_set_name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Tint Set Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Red1h
  model: red1h
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Red for Helmet: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Grn1h
  model: grn1h
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Green for Helmet: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Blu1h
  model: blu1h
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Blue for Helmet: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Red2c
  model: red2c
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Red for Chest: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Grn2c
  model: grn2c
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Green for Chest: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Blu2c
  model: blu2c
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Blue for Chest: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Red3a
  model: red3a
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Red for Arms: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Grn3a
  model: grn3a
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Green for Arms: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Blu3a
  model: blu3a
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Blue for Arms: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Red4b
  model: red4b
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Red for Bracers: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Grn4b
  model: grn4b
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Green for Bracers: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Blu4b
  model: blu4b
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Blue for Bracers: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Red5g
  model: red5g
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Red for Hands: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Grn5g
  model: grn5g
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Green for Hands: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Blu5g
  model: blu5g
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Blue for Hands: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Red6l
  model: red6l
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Red for Legs: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Grn6l
  model: grn6l
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Green for Legs: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Blu6l
  model: blu6l
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Blue for Legs: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Red7f
  model: red7f
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Red for Feet: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Grn7f
  model: grn7f
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Green for Feet: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Blu7f
  model: blu7f
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Blue for Feet: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Red8x
  model: red8x
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Red for Unknown: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Grn8x
  model: grn8x
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Green for Unknown: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Blu8x
  model: blu8x
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Blue for Unknown: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Red9x
  model: red9x
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Red for Unknown: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Grn9x
  model: grn9x
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Green for Unknown: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Blu9x
  model: blu9x
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Blue for Unknown: 0 = None, 255 = Max</p>'
