- disabled: false
  featured: false
  inputtype: text
  label: Npc Faction Id
  model: npc_faction_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="npc_faction.md" target="_blank">NPC Faction Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Faction Id
  model: faction_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="faction_list.md" target="_blank">Faction Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Value
  model: value
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Value</p>
- disabled: false
  featured: false
  inputtype: text
  label: Npc Value
  model: npc_value
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>NPC Value: -1 = Attack, 0 = Neutral, 1 = Assist</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Temp
  model: temp
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Temeporary: 0 = Faction is permanent, player recieves a message, 1 = Faction is temporary, player does not recieve a message, 2 = Faction is temporary, player recieves a message, 3 = Faction is permanent, but player does not recieve a message.</p>'
