- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique NPC Spell Set Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Name
  model: name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>NPC Spell Set Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Parent List
  model: parent_list
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Inherit all the spells from this list, and merge them with our spells. Only one level of inheritance is allowed, so your parent&rsquo;s parent will not be included.</p>
- disabled: false
  featured: false
  inputtype: text
  label: Attack Proc
  model: attack_proc
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>The combat proc that an NPC with this spell set will add to their list of procs. <a href="spells_new.md" target="_blank">Spell Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Proc Chance
  model: proc_chance
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Proc Chance: 0 = Never, 100 = Always</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Range Proc
  model: range_proc
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>The ranged proc that an NPC with this spell set will add to their list of procs.</p>
- disabled: false
  featured: false
  inputtype: text
  label: Rproc Chance
  model: rproc_chance
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Ranged Proc Chance: 0 = Never, 100 = Always</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Defensive Proc
  model: defensive_proc
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>The defensive proc that an NPC with this spell set will add to their list of procs.</p>
- disabled: false
  featured: false
  inputtype: text
  label: Dproc Chance
  model: dproc_chance
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Defensive Proc Chance: 0 = Never, 100 = Always</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Fail Recast
  model: fail_recast
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Fail Recast</p>
- disabled: false
  featured: false
  inputtype: text
  label: Engaged No Sp Recast Min
  model: engaged_no_sp_recast_min
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Engaged No Sp Recast Max
  model: engaged_no_sp_recast_max
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Engaged B Self Chance
  model: engaged_b_self_chance
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Engaged B Other Chance
  model: engaged_b_other_chance
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Engaged D Chance
  model: engaged_d_chance
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Pursue No Sp Recast Min
  model: pursue_no_sp_recast_min
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Pursue No Sp Recast Max
  model: pursue_no_sp_recast_max
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Pursue D Chance
  model: pursue_d_chance
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Idle No Sp Recast Min
  model: idle_no_sp_recast_min
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Idle No Sp Recast Max
  model: idle_no_sp_recast_max
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Idle B Chance
  model: idle_b_chance
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
