- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Spell Effect Entry Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Npc Spells Effects Id
  model: npc_spells_effects_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="npc_spells_effects.md" target="_blank">NPC Spells Effects Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Spell Effect Id
  model: spell_effect_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/spells/spell-effect-ids" target="_blank">Spell Effect Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Minlevel
  model: minlevel
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Minimum Level</p>
- disabled: false
  featured: false
  inputtype: text
  label: Maxlevel
  model: maxlevel
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Maximum Level</p>
- disabled: false
  featured: false
  inputtype: text
  label: Se Base
  model: se_base
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Spell Effect Base</p>
- disabled: false
  featured: false
  inputtype: text
  label: Se Limit
  model: se_limit
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Spell Effect Limit</p>
- disabled: false
  featured: false
  inputtype: text
  label: Se Max
  model: se_max
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Spell Effect Maximum</p>
