- disabled: false
  featured: false
  inputtype: text
  label: Type
  model: type
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Type: 0 = Trash, 1 = Named, 2 = Raid</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Level
  model: level
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Level</p>
- disabled: false
  featured: false
  inputtype: text
  label: Ac
  model: ac
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Armor Class</p>
- disabled: false
  featured: false
  inputtype: text
  label: Hp
  model: hp
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Health</p>
- disabled: false
  featured: false
  inputtype: text
  label: Accuracy
  model: accuracy
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Accuracy</p>
- disabled: false
  featured: false
  inputtype: text
  label: Slow Mitigation
  model: slow_mitigation
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Slow Mitigation</p>
- disabled: false
  featured: false
  inputtype: text
  label: Attack
  model: attack
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Attack</p>
- disabled: false
  featured: false
  inputtype: text
  label: Strength
  model: strength
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Strength</p>
- disabled: false
  featured: false
  inputtype: text
  label: Stamina
  model: stamina
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Stamina</p>
- disabled: false
  featured: false
  inputtype: text
  label: Dexterity
  model: dexterity
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Dexterity</p>
- disabled: false
  featured: false
  inputtype: text
  label: Agility
  model: agility
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Agility</p>
- disabled: false
  featured: false
  inputtype: text
  label: Intelligence
  model: intelligence
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Intelligence</p>
- disabled: false
  featured: false
  inputtype: text
  label: Wisdom
  model: wisdom
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Wisdom</p>
- disabled: false
  featured: false
  inputtype: text
  label: Charisma
  model: charisma
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Charisma</p>
- disabled: false
  featured: false
  inputtype: text
  label: Magic Resist
  model: magic_resist
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Magic Resistance</p>
- disabled: false
  featured: false
  inputtype: text
  label: Cold Resist
  model: cold_resist
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Cold Resistance</p>
- disabled: false
  featured: false
  inputtype: text
  label: Fire Resist
  model: fire_resist
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Fire Resistance</p>
- disabled: false
  featured: false
  inputtype: text
  label: Poison Resist
  model: poison_resist
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Poison Resistance</p>
- disabled: false
  featured: false
  inputtype: text
  label: Disease Resist
  model: disease_resist
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Disease Resistance</p>
- disabled: false
  featured: false
  inputtype: text
  label: Corruption Resist
  model: corruption_resist
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Corruption Resistance</p>
- disabled: false
  featured: false
  inputtype: text
  label: Physical Resist
  model: physical_resist
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Physical Resistance</p>
- disabled: false
  featured: false
  inputtype: text
  label: Min Dmg
  model: min_dmg
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Minimum Damage</p>
- disabled: false
  featured: false
  inputtype: text
  label: Max Dmg
  model: max_dmg
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Maximum Damage</p>
- disabled: false
  featured: false
  inputtype: text
  label: Hp Regen Rate
  model: hp_regen_rate
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Health Regeneration Rate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Attack Delay
  model: attack_delay
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Attack Delay: Delay between the attack arounds in 10ths of a second.</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Spell Scale
  model: spell_scale
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Spell Scale: 50 = 50%, 100 = 100%, 150 = 150%</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Heal Scale
  model: heal_scale
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Heal Scale: 50 = 50%, 100 = 100%, 150 = 150%</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Special Abilities
  model: special_abilities
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Special Abilities</p>
