- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique NPC Spell Entry Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Npc Spells Id
  model: npc_spells_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="npc_spells.md" target="_blank">Unique NPC Spell Set Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Spellid
  model: spellid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="spells_new.md" target="_blank">Spell Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Type
  model: type
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/spells/spell-types" target="_blank">Spell Type Bitmask</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Minlevel
  model: minlevel
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Minimum Level</p>
- disabled: false
  featured: false
  inputtype: text
  label: Maxlevel
  model: maxlevel
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Maximum Level</p>
- disabled: false
  featured: false
  inputtype: text
  label: Manacost
  model: manacost
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Mana Cost</p>
- disabled: false
  featured: false
  inputtype: text
  label: Recast Delay
  model: recast_delay
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Recast Delay</p>
- disabled: false
  featured: false
  inputtype: text
  label: Priority
  model: priority
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Priority: 0 = Innate, 1 = Highest Priority, 5 = Lower Priority, 10 = Even Lower Priority</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Resist Adjust
  model: resist_adjust
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Resist Adjustment</p>
- disabled: false
  featured: false
  inputtype: text
  label: Min Hp
  model: min_hp
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Minimum Health Percentage</p>
- disabled: false
  featured: false
  inputtype: text
  label: Max Hp
  model: max_hp
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Maximum Health Percentage</p>
