- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Object Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Zoneid
  model: zoneid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/zone-list" target="_blank">Zone Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Version
  model: version
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Version: -1 For All</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Xpos
  model: xpos
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>X Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Ypos
  model: ypos
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Y Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Zpos
  model: zpos
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Z Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Heading
  model: heading
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Heading Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Itemid
  model: itemid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="items.md" target="_blank">Item Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Charges
  model: charges
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Charges</p>
- disabled: false
  featured: false
  inputtype: text
  label: Objectname
  model: objectname
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Object Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Type
  model: type
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/object-types" target="_blank">Type</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Icon
  model: icon
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Icon</p>
- disabled: false
  featured: false
  inputtype: text
  label: Unknown08
  model: unknown08
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unknown</p>
- disabled: false
  featured: false
  inputtype: text
  label: Unknown10
  model: unknown10
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unknown</p>
- disabled: false
  featured: false
  inputtype: text
  label: Unknown20
  model: unknown20
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unknown</p>
- disabled: false
  featured: false
  inputtype: text
  label: Unknown24
  model: unknown24
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unknown</p>
- disabled: false
  featured: false
  inputtype: text
  label: Unknown60
  model: unknown60
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unknown</p>
- disabled: false
  featured: false
  inputtype: text
  label: Unknown64
  model: unknown64
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unknown</p>
- disabled: false
  featured: false
  inputtype: text
  label: Unknown68
  model: unknown68
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unknown</p>
- disabled: false
  featured: false
  inputtype: text
  label: Unknown72
  model: unknown72
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unknown</p>
- disabled: false
  featured: false
  inputtype: text
  label: Unknown76
  model: unknown76
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unknown</p>
- disabled: false
  featured: false
  inputtype: text
  label: Unknown84
  model: unknown84
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unknown</p>
- disabled: false
  featured: false
  inputtype: text
  label: Size
  model: size
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Size</p>
- disabled: false
  featured: false
  inputtype: text
  label: Tilt X
  model: tilt_x
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Tilt X</p>
- disabled: false
  featured: false
  inputtype: text
  label: Tilt Y
  model: tilt_y
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Tilt Y</p>
- disabled: false
  featured: false
  inputtype: text
  label: Display Name
  model: display_name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Display Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Min Expansion
  model: min_expansion
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Max Expansion
  model: max_expansion
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Content Flags
  model: content_flags
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Content Flags Disabled
  model: content_flags_disabled
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
