- disabled: false
  featured: false
  inputtype: text
  label: Dib
  model: dib
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unknown</p>
- disabled: false
  featured: false
  inputtype: text
  label: Petid
  model: petid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Petition Entry Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Charname
  model: charname
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Name</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Accountname
  model: accountname
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="account.md" target="_blank">Account Name</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Lastgm
  model: lastgm
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Last GM</p>
- disabled: false
  featured: false
  inputtype: text
  label: Petitiontext
  model: petitiontext
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Petition Text</p>
- disabled: false
  featured: false
  inputtype: text
  label: Gmtext
  model: gmtext
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>GM Text</p>
- disabled: false
  featured: false
  inputtype: text
  label: Zone
  model: zone
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/zone-list" target="_blank">Zone Short Name</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Urgency
  model: urgency
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Urgency</p>
- disabled: false
  featured: false
  inputtype: text
  label: Charclass
  model: charclass
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/class-list" target="_blank">Character Class</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Charrace
  model: charrace
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/npc/race-list" target="_blank">Character Race</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Charlevel
  model: charlevel
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Character Level</p>
- disabled: false
  featured: false
  inputtype: text
  label: Checkouts
  model: checkouts
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Checkouts</p>
- disabled: false
  featured: false
  inputtype: text
  label: Unavailables
  model: unavailables
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unavailables</p>
- disabled: false
  featured: false
  inputtype: text
  label: Ischeckedout
  model: ischeckedout
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Is Checked Out: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Senttime
  model: senttime
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Sent Time UNIX Timestamp</p>
