- disabled: false
  featured: false
  inputtype: text
  label: Type
  model: type
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="npc_types.md" target="_blank">NPC Type Name</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Petpower
  model: petpower
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Pet Power</p>
- disabled: false
  featured: false
  inputtype: text
  label: NpcID
  model: npcID
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="npc_types.md" target="_blank">NPC Type Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Temp
  model: temp
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Temporary: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Petcontrol
  model: petcontrol
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Pet Control: 0 = No Control, 1 = No Attack Control, 2 = Full Control</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Petnaming
  model: petnaming
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Pet Naming: 0 = Soandsos Pet, 1 = Soandsos Familiar, 2 = Soandsos Warder, 3 = Random Naming (i.e. Gobaner), 4 = Keeps name from npc_types table</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Monsterflag
  model: monsterflag
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Monster Flag: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Equipmentset
  model: equipmentset
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="pet_equipmentset.md" target="_blank">Pet Equipment Set Identifier</a></p>
