- disabled: false
  featured: false
  inputtype: text
  label: Set Id
  model: set_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Pet Equipment Set Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Setname
  model: setname
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Pet Equipment Set Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Nested Set
  model: nested_set
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Nested Set Identifier</p>
