- disabled: false
  featured: false
  inputtype: text
  label: Zoneid
  model: zoneid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/zone-list" target="_blank">Zone Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Exploreid
  model: exploreid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="goallists.md" target="_blank">Explore Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Minx
  model: minx
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Minimum X Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Maxx
  model: maxx
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Maximum X Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Miny
  model: miny
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Minimum Y Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Maxy
  model: maxy
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Maximum Y Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Minz
  model: minz
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Minimum Z Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Maxz
  model: maxz
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Maximum Z Coordinate</p>
