- disabled: false
  featured: false
  inputtype: text
  label: Charid
  model: charid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Npcid
  model: npcid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="npc_types.md" target="_blank">NPC Type Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Zoneid
  model: zoneid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/zone-list" target="_blank">Zone Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Name
  model: name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Value
  model: value
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Value</p>
- disabled: false
  featured: false
  inputtype: text
  label: Expdate
  model: expdate
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Expiration Date UNIX Timestamp</p>
