- disabled: false
  featured: false
  inputtype: text
  label: Raidid
  model: raidid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Raid Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Loottype
  model: loottype
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Loot Type</p>
- disabled: false
  featured: false
  inputtype: text
  label: Locked
  model: locked
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Locked: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Motd
  model: motd
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Message of the Day</p>
