- disabled: false
  featured: false
  inputtype: text
  label: Gid
  model: gid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="group_id.md" target="_blank">Group Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Rid
  model: rid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="raid_details.md" target="_blank">Raid Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Marknpc
  model: marknpc
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Mark NPC: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Maintank
  model: maintank
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Main Tank: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Assist
  model: assist
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Assist: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Puller
  model: puller
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Puller: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Leadershipaa
  model: leadershipaa
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Leadership AA</p>
- disabled: false
  featured: false
  inputtype: text
  label: Mentoree
  model: mentoree
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Mentoree: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Mentor Percent
  model: mentor_percent
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Mentore Percent: 0 = None, 100 = Max</p>'
