- disabled: false
  featured: false
  inputtype: text
  label: Raidid
  model: raidid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="raid_details.md" target="_blank">Raid Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Charid
  model: charid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Character Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Groupid
  model: groupid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="group_id.md" target="_blank">Group Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: ' Class'
  model: _class
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/class-list" target="_blank">Class</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Level
  model: level
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Level</p>
- disabled: false
  featured: false
  inputtype: text
  label: Name
  model: name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Isgroupleader
  model: isgroupleader
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Is Group Leader: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Israidleader
  model: israidleader
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Is Raid Leader: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Islooter
  model: islooter
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Is Looter: 0 = False, 1 = True</p>'
