- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Report Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Name
  model: name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Reported
  model: reported
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Reported</p>
- disabled: false
  featured: false
  inputtype: text
  label: Reported Text
  model: reported_text
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Reported Text</p>
