- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Respawn Time Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Start
  model: start
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Start UNIX Timestamp</p>
- disabled: false
  featured: false
  inputtype: text
  label: Duration
  model: duration
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Duration in Seconds</p>
- disabled: false
  featured: false
  inputtype: text
  label: Instance Id
  model: instance_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="instance_list.md" target="_blank">Instance Identifier</a></p>
