- disabled: false
  featured: false
  inputtype: text
  label: Ruleset Id
  model: ruleset_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Rule Set Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Name
  model: name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Name</p>
