- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Saylink Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Phrase
  model: phrase
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Phrase</p>
