- disabled: false
  featured: false
  inputtype: text
  label: Acctid
  model: acctid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="account.md" target="_blank">Unique Account Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Slotid
  model: slotid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/inventory/inventory-slots" target="_blank">Slot Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Itemid
  model: itemid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="items.md" target="_blank">Item Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Charges
  model: charges
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Charges</p>
- disabled: false
  featured: false
  inputtype: text
  label: Augslot1
  model: augslot1
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Augment Slot 1</p>
- disabled: false
  featured: false
  inputtype: text
  label: Augslot2
  model: augslot2
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Augment Slot 2</p>
- disabled: false
  featured: false
  inputtype: text
  label: Augslot3
  model: augslot3
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Augment Slot 3</p>
- disabled: false
  featured: false
  inputtype: text
  label: Augslot4
  model: augslot4
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Augment Slot 4</p>
- disabled: false
  featured: false
  inputtype: text
  label: Augslot5
  model: augslot5
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Augment Slot 5</p>
- disabled: false
  featured: false
  inputtype: text
  label: Augslot6
  model: augslot6
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Augment Slot 6</p>
- disabled: false
  featured: false
  inputtype: text
  label: Custom Data
  model: custom_data
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Custom Data</p>
