- disabled: false
  featured: false
  inputtype: text
  label: SkillID
  model: skillID
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/skills" target="_blank">Skill Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Class
  model: class
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/class-list" target="_blank">Class</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Level
  model: level
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Level</p>
- disabled: false
  featured: false
  inputtype: text
  label: Cap
  model: cap
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Cap</p>
- disabled: false
  featured: false
  inputtype: text
  label: 'Class '
  model: class_
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unknown</p>
