- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Spawn Group Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Name
  model: name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Spawn Limit
  model: spawn_limit
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Spawn Limit</p>
- disabled: false
  featured: false
  inputtype: text
  label: Dist
  model: dist
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Distance</p>
- disabled: false
  featured: false
  inputtype: text
  label: Max X
  model: max_x
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Max X Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Min X
  model: min_x
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Min X Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Max Y
  model: max_y
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Max Y Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Min Y
  model: min_y
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Min Y Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Delay
  model: delay
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Roaming Delay</p>
- disabled: false
  featured: false
  inputtype: text
  label: Mindelay
  model: mindelay
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Minimum Delay</p>
- disabled: false
  featured: false
  inputtype: text
  label: Despawn
  model: despawn
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/npc/spawns/npc-despawn-types" target="_blank">Despawn Type</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Despawn Timer
  model: despawn_timer
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Despawn Timer in Seconds</p>
- disabled: false
  featured: false
  inputtype: text
  label: Wp Spawns
  model: wp_spawns
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
