- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Spawn Event Entry Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Zone
  model: zone
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/zone-list" target="_blank">Zone Short Name</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Cond Id
  model: cond_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="spawn_conditions.md" target="_blank">Spawn Condition Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Name
  model: name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Period
  model: period
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Period</p>
- disabled: false
  featured: false
  inputtype: text
  label: Next Minute
  model: next_minute
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Next Minute</p>
- disabled: false
  featured: false
  inputtype: text
  label: Next Hour
  model: next_hour
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Next Hour</p>
- disabled: false
  featured: false
  inputtype: text
  label: Next Day
  model: next_day
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Next Day</p>
- disabled: false
  featured: false
  inputtype: text
  label: Next Month
  model: next_month
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Next Month</p>
- disabled: false
  featured: false
  inputtype: text
  label: Next Year
  model: next_year
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Next Year</p>
- disabled: false
  featured: false
  inputtype: text
  label: Enabled
  model: enabled
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Enabled: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Action
  model: action
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/npc/spawns/action-types" target="_blank">Action Type</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Argument
  model: argument
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Argument: (Based on Action) 0 = Argument Value</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Strict
  model: strict
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Strict Date Criteria: 0 = False, 1 = True</p>'
