- disabled: false
  featured: false
  inputtype: text
  label: SpawngroupID
  model: spawngroupID
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="spawngroup.md" target="_blank">Unique Spawn Group Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: NpcID
  model: npcID
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="npc_types.md" target="_blank">NPC Type Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Chance
  model: chance
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Chance: 0 = Never, 100 = Always</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Condition Value Filter
  model: condition_value_filter
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
