- disabled: false
  featured: false
  inputtype: text
  label: Zone
  model: zone
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/zone-list" target="_blank">Zone Short Name</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Spawn Condition Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Value
  model: value
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Value</p>
- disabled: false
  featured: false
  inputtype: text
  label: Onchange
  model: onchange
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/npc/spawns/on-change-types" target="_blank">On Change Type</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Name
  model: name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Name</p>
