- disabled: false
  featured: false
  inputtype: text
  label: Spellid
  model: spellid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="spells_new.md" target="_blank">Unique Spell Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Spell Name
  model: spell_name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="spells_new.md" target="_blank">Spell Name</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Qglobal
  model: qglobal
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="quest_globals.md" target="_blank">Quest Global Name</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Value
  model: value
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Quest Global Value</p>
