- disabled: false
  featured: false
  inputtype: text
  label: Spellid
  model: spellid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="spells_new.md" target="_blank">Unique Spell Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Key
  model: key
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="data_buckets.md" target="_blank">Data Bucket Name</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Value
  model: value
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Data Bucket Value</p>
