- disabled: false
  featured: false
  inputtype: text
  label: X
  model: x
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>X Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: "Y"
  model: "y"
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Y Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Z
  model: z
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Z Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Heading
  model: heading
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Heading Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Zone Id
  model: zone_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/zone-list" target="_blank">Zone Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Bind Id
  model: bind_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Bind Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Player Choice
  model: player_choice
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Player Choice</p>
- disabled: false
  featured: false
  inputtype: text
  label: Player Class
  model: player_class
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/class-list" target="_blank">Player Class</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Player Deity
  model: player_deity
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/deity-list" target="_blank">Player Deity</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Player Race
  model: player_race
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/npc/race-list" target="_blank">Player Race</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Start Zone
  model: start_zone
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/zone-list" target="_blank">Zone Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Bind X
  model: bind_x
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Bind X Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Bind Y
  model: bind_y
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Bind Y Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Bind Z
  model: bind_z
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Bind Z Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Select Rank
  model: select_rank
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Select Rank: Always 50</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Min Expansion
  model: min_expansion
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Max Expansion
  model: max_expansion
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Content Flags
  model: content_flags
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Content Flags Disabled
  model: content_flags_disabled
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
