- disabled: false
  featured: false
  inputtype: text
  label: Taskid
  model: taskid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="tasks.md" target="_blank">Task Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Activityid
  model: activityid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Activity Identifier: Starts at 0</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Step
  model: step
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Step: 0 = Always Available, &gt;0 = Must Complete Previous</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Activitytype
  model: activitytype
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/task-system-guide/task-activity-types" target="_blank">Activity Type</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Target Name
  model: target_name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Target Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Item List
  model: item_list
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="items.md" target="_blank">Item Identifier List</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Skill List
  model: skill_list
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/skills" target="_blank">Skill Identifier List</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Spell List
  model: spell_list
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="spells_new.md" target="_blank">Spell Identifier List</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Description Override
  model: description_override
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Description Override</p>
- disabled: false
  featured: false
  inputtype: text
  label: Goalid
  model: goalid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Goal Identifier or <a href="goallists.md" target="_blank">Goal List Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Goalmethod
  model: goalmethod
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Goal Method: 0 = Single Value, 1 = List</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Goalcount
  model: goalcount
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Goal Count</p>
- disabled: false
  featured: false
  inputtype: text
  label: Delivertonpc
  model: delivertonpc
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Deliver To NPC: 0 = No Delivery NPC, &gt;0 = <a href="npc_types.md" target="_blank">NPC Type Identifier</a></p>'
- disabled: false
  featured: false
  inputtype: text
  label: Zones
  model: zones
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/zone-list" target="_blank">Zones List</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Optional
  model: optional
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Optional: 0 = False, 1 = True</p>'
