- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Task Set Entry Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Taskid
  model: taskid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="tasks.md" target="_blank">Task Identifier</a></p>
