- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Task Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Type
  model: type
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/task-system-guide/task-types" target="_blank">Task Type</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Duration
  model: duration
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Duration</p>
- disabled: false
  featured: false
  inputtype: text
  label: Duration Code
  model: duration_code
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/task-system-guide/task-duration-codes" target="_blank">Duration Code</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Title
  model: title
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Title</p>
- disabled: false
  featured: false
  inputtype: text
  label: Description
  model: description
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Description</p>
- disabled: false
  featured: false
  inputtype: text
  label: Reward
  model: reward
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Reward Description</p>
- disabled: false
  featured: false
  inputtype: text
  label: Rewardid
  model: rewardid
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="items.md" target="_blank">Reward Item Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Cashreward
  model: cashreward
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Cash Reward in Copper</p>
- disabled: false
  featured: false
  inputtype: text
  label: Xpreward
  model: xpreward
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Experience Reward</p>
- disabled: false
  featured: false
  inputtype: text
  label: Rewardmethod
  model: rewardmethod
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Reward Method: 0 = Single Item ID, 1 = List of Items, 2 = Quest Controlled</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Reward Radiant Crystals
  model: reward_radiant_crystals
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Reward Ebon Crystals
  model: reward_ebon_crystals
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Minlevel
  model: minlevel
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Minimum Level</p>
- disabled: false
  featured: false
  inputtype: text
  label: Maxlevel
  model: maxlevel
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Maximum Level</p>
- disabled: false
  featured: false
  inputtype: text
  label: Level Spread
  model: level_spread
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Min Players
  model: min_players
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Max Players
  model: max_players
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Repeatable
  model: repeatable
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Repeatable: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Faction Reward
  model: faction_reward
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Faction Reward</p>
- disabled: false
  featured: false
  inputtype: text
  label: Completion Emote
  model: completion_emote
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Completion Emote</p>
- disabled: false
  featured: false
  inputtype: text
  label: Replay Timer Seconds
  model: replay_timer_seconds
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Request Timer Seconds
  model: request_timer_seconds
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
