- disabled: false
  featured: false
  inputtype: text
  label: Time
  model: time
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Time</p>
- disabled: false
  featured: false
  inputtype: text
  label: Seller
  model: seller
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Seller</p>
- disabled: false
  featured: false
  inputtype: text
  label: Buyer
  model: buyer
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Buyer</p>
- disabled: false
  featured: false
  inputtype: text
  label: Itemname
  model: itemname
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="items.md" target="_blank">Item Name</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Quantity
  model: quantity
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Quantity</p>
- disabled: false
  featured: false
  inputtype: text
  label: Totalcost
  model: totalcost
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Total Cost</p>
- disabled: false
  featured: false
  inputtype: text
  label: Trantype
  model: trantype
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Transaction Type</p>
