- disabled: false
  featured: false
  inputtype: text
  label: Char Id
  model: char_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Unique Character Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Item Id
  model: item_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="items.md" target="_blank">Item Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Serialnumber
  model: serialnumber
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Serial Number</p>
- disabled: false
  featured: false
  inputtype: text
  label: Charges
  model: charges
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Charges</p>
- disabled: false
  featured: false
  inputtype: text
  label: Item Cost
  model: item_cost
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Item Cost</p>
- disabled: false
  featured: false
  inputtype: text
  label: Slot Id
  model: slot_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/inventory/inventory-slots" target="_blank">Slot Identifier</a></p>
