- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Trap Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Zone
  model: zone
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/zone-list" target="_blank">Zone Short Name</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Version
  model: version
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Version: -1 For All</p>'
- disabled: false
  featured: false
  inputtype: text
  label: X
  model: x
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>X Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: "Y"
  model: "y"
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Y Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Z
  model: z
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Z Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Chance
  model: chance
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Chance: 0 = None, 100 = Always</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Maxzdiff
  model: maxzdiff
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Max Z Difference</p>
- disabled: false
  featured: false
  inputtype: text
  label: Radius
  model: radius
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Trap Radius</p>
- disabled: false
  featured: false
  inputtype: text
  label: Effect
  model: effect
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/trap-types" target="_blank">Trap Type</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Effectvalue
  model: effectvalue
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Effect Value: (Based on Trap Type) 0 = <a href="spells_new.md" target="_blank">Spell Identifier</a>, 1 = Radius, 2 = <a href="npc_types.md" target="_blank">NPC Type Identifier</a>, 3 = <a href="npc_types.md" target="_blank">NPC Type Identifier</a>, 4 = Minimum Damage</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Effectvalue2
  model: effectvalue2
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Effect Value 2: (Based on Trap Type) 0 = Unused, 1 = (0 = Everything Will Aggro, 1 = Only KoS Will Agro), 2 = Number of NPCs, 3 = Number of NPCs, 4 = Maximum Damage</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Message
  model: message
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Message</p>
- disabled: false
  featured: false
  inputtype: text
  label: Skill
  model: skill
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/skills" target="_blank">Skill Required</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Level
  model: level
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Level</p>
- disabled: false
  featured: false
  inputtype: text
  label: Respawn Time
  model: respawn_time
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Respawn Timer in Seconds</p>
- disabled: false
  featured: false
  inputtype: text
  label: Respawn Var
  model: respawn_var
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Random Respawn Timer Variance in Seconds</p>
- disabled: false
  featured: false
  inputtype: text
  label: Triggered Number
  model: triggered_number
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Triggered Member</p>
- disabled: false
  featured: false
  inputtype: text
  label: Group
  model: group
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Group</p>
- disabled: false
  featured: false
  inputtype: text
  label: Despawn When Triggered
  model: despawn_when_triggered
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Despawn When Triggered: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Undetectable
  model: undetectable
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Undetectable: 0 = False, 1= True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Min Expansion
  model: min_expansion
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Max Expansion
  model: max_expansion
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Content Flags
  model: content_flags
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Content Flags Disabled
  model: content_flags_disabled
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
