- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Tribute Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Unknown
  model: unknown
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unknown</p>
- disabled: false
  featured: false
  inputtype: text
  label: Name
  model: name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Descr
  model: descr
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Description</p>
- disabled: false
  featured: false
  inputtype: text
  label: Isguild
  model: isguild
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Is Guild: 0 = false, 1 = True</p>'
