- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: User Id
  model: user_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Server Database Connection Id
  model: server_database_connection_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Active
  model: active
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Created By
  model: created_by
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Created At
  model: created_at
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Updated At
  model: updated_at
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Deleted At
  model: deleted_at
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
