- disabled: false
  featured: false
  inputtype: text
  label: Varname
  model: varname
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Variable Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Value
  model: value
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Value</p>
- disabled: false
  featured: false
  inputtype: text
  label: Information
  model: information
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Information</p>
- disabled: false
  featured: false
  inputtype: text
  label: Ts
  model: ts
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Timestamp</p>
