- disabled: false
  featured: false
  inputtype: text
  label: CharID
  model: charID
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="character_data.md" target="_blank">Unique Character Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: ZoneID
  model: zoneID
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/zone-list" target="_blank">Zone Identifier</a></p>
