- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Zone Point Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Zone
  model: zone
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/zone-list" target="_blank">Zone Short Name</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Version
  model: version
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Version</p>
- disabled: false
  featured: false
  inputtype: text
  label: Number
  model: number
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Represents the iterator field sent in the struct ZonePoint_Entry, zone points for the current zone are sent when client zones in (during Client::Handle_Connect_OP_ReqClientSpawn in client_packet.cpp). This number field must be unique and also could have a hardcoded equivalent in the client, eg. client is expecting a specific number value for a zone point or teleport/object pad, such as in Erudin (erudnext).</p>
- disabled: false
  featured: false
  inputtype: text
  label: "Y"
  model: "y"
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Y Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: X
  model: x
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>X Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Z
  model: z
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Z Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Heading
  model: heading
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Heading Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Target Y
  model: target_y
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Target Y Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Target X
  model: target_x
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Target X Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Target Z
  model: target_z
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Target Z Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Target Heading
  model: target_heading
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Target Heading Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Zoneinst
  model: zoneinst
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="instance_list.d" target="_blank">Instance Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Target Zone Id
  model: target_zone_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/zone-list" target="_blank">Target Zone Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Target Instance
  model: target_instance
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Target Instance Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: Buffer
  model: buffer
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Zone Point Buffer</p>
- disabled: false
  featured: false
  inputtype: text
  label: Client Version Mask
  model: client_version_mask
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/client-version-bitmasks" target="_blank">Client Version Mask</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Min Expansion
  model: min_expansion
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Max Expansion
  model: max_expansion
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Content Flags
  model: content_flags
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Content Flags Disabled
  model: content_flags_disabled
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Is Virtual
  model: is_virtual
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Height
  model: height
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Width
  model: width
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
