- disabled: false
  featured: false
  inputtype: text
  label: Short Name
  model: short_name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Short Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Id
  model: id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Unique Entry Identifier</p>
- disabled: false
  featured: false
  inputtype: text
  label: File Name
  model: file_name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>File Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Long Name
  model: long_name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Long Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Map File Name
  model: map_file_name
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Map File Name</p>
- disabled: false
  featured: false
  inputtype: text
  label: Safe X
  model: safe_x
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Safe X Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Safe Y
  model: safe_y
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Safe Y Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Safe Z
  model: safe_z
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Safe Z Coordinate</p>
- disabled: false
  featured: false
  inputtype: text
  label: Safe Heading
  model: safe_heading
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Graveyard Id
  model: graveyard_id
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="graveyard.md" target="_blank">Graveyard Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Min Level
  model: min_level
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Minimum Level</p>
- disabled: false
  featured: false
  inputtype: text
  label: Min Status
  model: min_status
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/player/status-levels" target="_blank">Minimum Status</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Zoneidnumber
  model: zoneidnumber
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/zones/zone-list" target="_blank">Unique Zone Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Version
  model: version
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Version</p>
- disabled: false
  featured: false
  inputtype: text
  label: Timezone
  model: timezone
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Timezone</p>
- disabled: false
  featured: false
  inputtype: text
  label: Maxclients
  model: maxclients
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Maximum Clients</p>
- disabled: false
  featured: false
  inputtype: text
  label: Ruleset
  model: ruleset
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="rule_sets.md" target="_blank">Ruleset Identifier</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Note
  model: note
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Note</p>
- disabled: false
  featured: false
  inputtype: text
  label: Underworld
  model: underworld
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Bottom Z to represent when the player is under the world</p>
- disabled: false
  featured: false
  inputtype: text
  label: Minclip
  model: minclip
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Minimum Clipping Distance</p>
- disabled: false
  featured: false
  inputtype: text
  label: Maxclip
  model: maxclip
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Maximum Clipping Distance</p>
- disabled: false
  featured: false
  inputtype: text
  label: Fog Minclip
  model: fog_minclip
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Fog Minimum Clipping Distance</p>
- disabled: false
  featured: false
  inputtype: text
  label: Fog Maxclip
  model: fog_maxclip
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Fog Maximum Clipping Distance</p>
- disabled: false
  featured: false
  inputtype: text
  label: Fog Blue
  model: fog_blue
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Fog Blue Level: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Fog Red
  model: fog_red
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Fog Red Level: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Fog Green
  model: fog_green
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Fog Green Level: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Sky
  model: sky
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Sky type the client will present as the backdrop</p>
- disabled: false
  featured: false
  inputtype: text
  label: Ztype
  model: ztype
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>This field is sent directly to the client on zone-in, most zones are set to 0, 1 or 255.</p>
- disabled: false
  featured: false
  inputtype: text
  label: Zone Exp Multiplier
  model: zone_exp_multiplier
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>This will multiply the XP to this percentage value (decimal based, 100% = 1.0)</p>
- disabled: false
  featured: false
  inputtype: text
  label: Walkspeed
  model: walkspeed
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Walkspeed in this zone</p>
- disabled: false
  featured: false
  inputtype: text
  label: Time Type
  model: time_type
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>This value varies depending on the zone but it is sent to the client on zone in. Most starting zones/newbie areas have this value set to 2, dungeons tyically have this set to 0, some zones break from the norm and have values greater than 2, (akanon = 3, blackburrow = 5, cazicthule = 5, crushbone = 5, erudnint = 4, kaladima = 3, etc.)</p>
- disabled: false
  featured: false
  inputtype: text
  label: Fog Red1
  model: fog_red1
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Fog Red Level 1: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Fog Green1
  model: fog_green1
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Fog Green Level 1: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Fog Blue1
  model: fog_blue1
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Fog Blue Level 1: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Fog Minclip1
  model: fog_minclip1
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Fog Minimum Clipping Distance 1</p>
- disabled: false
  featured: false
  inputtype: text
  label: Fog Maxclip1
  model: fog_maxclip1
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Fog Maximum Clipping Distance 1</p>
- disabled: false
  featured: false
  inputtype: text
  label: Fog Red2
  model: fog_red2
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Fog Red Level 2: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Fog Green2
  model: fog_green2
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Fog Green Level 2: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Fog Blue2
  model: fog_blue2
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Fog Blue Level 2: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Fog Minclip2
  model: fog_minclip2
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Fog Minimum Clipping Distance 2</p>
- disabled: false
  featured: false
  inputtype: text
  label: Fog Maxclip2
  model: fog_maxclip2
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Fog Maximum Clipping Distance 2</p>
- disabled: false
  featured: false
  inputtype: text
  label: Fog Red3
  model: fog_red3
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Fog Red Level 3: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Fog Green3
  model: fog_green3
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Fog Green Level 3: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Fog Blue3
  model: fog_blue3
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Fog Blue Level 3: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Fog Minclip3
  model: fog_minclip3
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Fog Minimum Clipping Distance 3</p>
- disabled: false
  featured: false
  inputtype: text
  label: Fog Maxclip3
  model: fog_maxclip3
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Fog Maximum Clipping Distance 4</p>
- disabled: false
  featured: false
  inputtype: text
  label: Fog Red4
  model: fog_red4
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Fog Red Level 4: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Fog Green4
  model: fog_green4
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Fog Green Level 4: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Fog Blue4
  model: fog_blue4
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Fog Blue Level 4: 0 = None, 255 = Max</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Fog Minclip4
  model: fog_minclip4
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Fog Minimum Clipping Distance 4</p>
- disabled: false
  featured: false
  inputtype: text
  label: Fog Maxclip4
  model: fog_maxclip4
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Fog Maximum Clipping Distance 4</p>
- disabled: false
  featured: false
  inputtype: text
  label: Fog Density
  model: fog_density
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>This is the intensity of the fog, this should be a number between 0-1, most commonly used is .1 or .33</p>
- disabled: false
  featured: false
  inputtype: text
  label: Flag Needed
  model: flag_needed
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="zone_flags.md" target="_blank">Flag Required</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Canbind
  model: canbind
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Can Bind: 0 = False, 1 = True (for Caster), 2 = True (for All)</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Cancombat
  model: cancombat
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Can Combat: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Canlevitate
  model: canlevitate
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Can Levitate: 0 = False, 1 = True (Does not affect those with #gm on)</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Castoutdoor
  model: castoutdoor
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Cast Outdoors: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Hotzone
  model: hotzone
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Hotzone: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Insttype
  model: insttype
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Instance Type</p>
- disabled: false
  featured: false
  inputtype: text
  label: Shutdowndelay
  model: shutdowndelay
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Shutdown Delay</p>
- disabled: false
  featured: false
  inputtype: text
  label: Peqzone
  model: peqzone
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>#peqzone: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Expansion
  model: expansion
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p><a href="https://eqemu.gitbook.io/server/categories/operation/expansion-list" target="_blank">Expansion</a></p>
- disabled: false
  featured: false
  inputtype: text
  label: Suspendbuffs
  model: suspendbuffs
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: '<p>Suspend Buffs: 0 = False, 1 = True</p>'
- disabled: false
  featured: false
  inputtype: text
  label: Rain Chance1
  model: rain_chance1
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Rain Chance 1</p>
- disabled: false
  featured: false
  inputtype: text
  label: Rain Chance2
  model: rain_chance2
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Rain Chance 2</p>
- disabled: false
  featured: false
  inputtype: text
  label: Rain Chance3
  model: rain_chance3
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Rain Chance 3</p>
- disabled: false
  featured: false
  inputtype: text
  label: Rain Chance4
  model: rain_chance4
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Rain Chance 4</p>
- disabled: false
  featured: false
  inputtype: text
  label: Rain Duration1
  model: rain_duration1
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Rain Duration 1</p>
- disabled: false
  featured: false
  inputtype: text
  label: Rain Duration2
  model: rain_duration2
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Rain Duration 2</p>
- disabled: false
  featured: false
  inputtype: text
  label: Rain Duration3
  model: rain_duration3
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Rain Duration 3</p>
- disabled: false
  featured: false
  inputtype: text
  label: Rain Duration4
  model: rain_duration4
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Rain Duration 4</p>
- disabled: false
  featured: false
  inputtype: text
  label: Snow Chance1
  model: snow_chance1
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Snow Chance 1</p>
- disabled: false
  featured: false
  inputtype: text
  label: Snow Chance2
  model: snow_chance2
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Snow Chance 2</p>
- disabled: false
  featured: false
  inputtype: text
  label: Snow Chance3
  model: snow_chance3
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Snow Chance 3</p>
- disabled: false
  featured: false
  inputtype: text
  label: Snow Chance4
  model: snow_chance4
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Snow Chance 4</p>
- disabled: false
  featured: false
  inputtype: text
  label: Snow Duration1
  model: snow_duration1
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Snow Duration 1</p>
- disabled: false
  featured: false
  inputtype: text
  label: Snow Duration2
  model: snow_duration2
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Snow Duration 2</p>
- disabled: false
  featured: false
  inputtype: text
  label: Snow Duration3
  model: snow_duration3
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Snow Duration 3</p>
- disabled: false
  featured: false
  inputtype: text
  label: Snow Duration4
  model: snow_duration4
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Snow Duration 4</p>
- disabled: false
  featured: false
  inputtype: text
  label: Gravity
  model: gravity
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Gravity</p>
- disabled: false
  featured: false
  inputtype: text
  label: Type
  model: type
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Type (0 = Unknown, 1 = Regular, 2 = Instanced, 3 = Hybrid, 4 = Raid, 5 = City)</p>
- disabled: false
  featured: false
  inputtype: text
  label: Skylock
  model: skylock
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Sky Lock</p>
- disabled: false
  featured: false
  inputtype: text
  label: Fast Regen Hp
  model: fast_regen_hp
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Fast Regen Health</p>
- disabled: false
  featured: false
  inputtype: text
  label: Fast Regen Mana
  model: fast_regen_mana
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Fast Regen Mana</p>
- disabled: false
  featured: false
  inputtype: text
  label: Fast Regen Endurance
  model: fast_regen_endurance
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Fast Regen Endurance</p>
- disabled: false
  featured: false
  inputtype: text
  label: Npc Max Aggro Dist
  model: npc_max_aggro_dist
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>NPC Max Aggro Distance</p>
- disabled: false
  featured: false
  inputtype: text
  label: Max Movement Update Range
  model: max_movement_update_range
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: <p>Max Movement Update Range</p>
- disabled: false
  featured: false
  inputtype: text
  label: Min Expansion
  model: min_expansion
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Max Expansion
  model: max_expansion
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Content Flags
  model: content_flags
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Content Flags Disabled
  model: content_flags_disabled
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
- disabled: false
  featured: false
  inputtype: text
  label: Underworld Teleport Index
  model: underworld_teleport_index
  readonly: false
  rows: ""
  styleclasses: col-12
  type: input
  help: ""
