export const AUG_TYPES = {
  "1": "(General: Single Stat)",
  "2": "(General: Multiple Stat)",
  "3": "(General: Spell Effect)",
  "4": "(Weapon: General)",
  "5": "(Weapon: Elemental Damage)",
  "6": "(Weapon: Base Damage)",
  "7": "(General: Group)",
  "8": "(General: Raid)",
  "9": "(General: Dragons Points)",
  "10": "(Crafted: Common)",
  "11": "(Crafted: Group)",
  "12": "(Crafted: Raid)",
  "13": "(Energeiac: Group)",
  "14": "(Energeiac: Raid)",
  "15": "(Emblem)",
  "16": "(Crafted: Group)",
  "17": "(Crafted: Raid)",
  "20": "(Ornamentation)",
  "21": "(Special Ornamentation)",
}
