export const AUG_TYPES = {
  1: { name: "(General: Single Stat)", mask: 1 },
  2: { name: "(General: Multiple Stat)", mask: 2 },
  3: { name: "(General: Spell Effect)", mask: 4 },
  4: { name: "(Weapon: General)", mask: 8 },
  5: { name: "(Weapon: Elemental Damage)", mask: 16 },
  6: { name: "(Weapon: Base Damage)", mask: 32 },
  7: { name: "(General: Group)", mask: 64 },
  8: { name: "(General: Raid)", mask: 128 },
  9: { name: "(General: Dragons Points)", mask: 256 },
  10: { name: "(Crafted: Common)", mask: 512 },
  11: { name: "(Crafted: Group)", mask: 1024 },
  12: { name: "(Crafted: Raid)", mask: 2048 },
  13: { name: "(Energeiac: Group)", mask: 4096 },
  14: { name: "(Energeiac: Raid)", mask: 8192 },
  15: { name: "(Emblem)", mask: 16384 },
  16: { name: "(Crafted: Group)", mask: 32768 },
  17: { name: "(Crafted: Raid)", mask: 65536 },
  20: { name: "(Ornamentation)", mask: 131072 },
  21: { name: "(Special Ornamentation)", mask: 262144 },
};
