export const BODYTYPES = {
  "0": "Unknown",
  "1": "Humanoid",
  "2": "Lycanthrope",
  "3": "Undead",
  "4": "Giant",
  "5": "Construct",
  "6": "Extra planar",
  "7": "Magical",
  "8": "Summoned undead",
  "9": "Unknown",
  "10": "Unknown",
  "11": "No target",
  "12": "Vampire",
  "13": "Atenha Ra",
  "14": "Greater Akheva",
  "15": "Khati Sha",
  "16": "Unknown",
  "17": "Unknown",
  "18": "Unknown",
  "19": "Zek",
  "20": "Unkownn",
  "21": "Animal",
  "22": "Insect",
  "23": "Monster",
  "24": "Summoned",
  "25": "Plant",
  "26": "Dragon",
  "27": "Summoned 2",
  "28": "Summoned 3",
  "29": "Unknown",
  "30": "Velious Dragon",
  "31": "Unknown",
  "32": "Dragon 3",
  "33": "Boxes",
  "34": "Discord Mob",
  "60": "No Target 2",
  "63": "Swarm pet",
  "67": "Special"
}
