export const DB_PLAYER_CLASSES_ALL = {
  1: { 'class': 'Warrior', short: 'WAR', mask: 1, icon: 4487},
  2: { 'class': 'Cleric', short: 'CLR', mask: 2, icon: 4477},
  3: { 'class': 'Paladin', short: 'PAL', mask: 4, icon: 4476},
  4: { 'class': 'Ranger', short: 'RNG', mask: 8, icon: 4471},
  5: { 'class': 'Shadow Knight', short: 'SHD', mask: 16, icon: 4483},
  6: { 'class': 'Druid', short: 'DRU', mask: 32, icon: 4481},
  7: { 'class': 'Monk', short: 'MNK', mask: 64, icon: 4475},
  8: { 'class': 'Bard', short: 'BRD', mask: 128, icon: 4464},
  9: { 'class': 'Rogue', short: 'ROG', mask: 256, icon: 4490},
  10: { 'class': 'Shaman', short: 'SHM', mask: 512, icon: 4491},
  11: { 'class': 'Necromancer', short: 'NEC', mask: 1024, icon: 4469},
  12: { 'class': 'Wizard', short: 'WIZ', mask: 2048, icon: 4482},
  13: { 'class': 'Magician', short: 'MAG', mask: 4096, icon: 4470},
  14: { 'class': 'Enchanter', short: 'ENC', mask: 8192, icon: 4488},
  15: { 'class': 'Beastlord', short: 'BST', mask: 16384, icon: 4489},
  16: { 'class': 'Berserker', short: 'BER', mask: 32768, icon: 4465},
};

export const DB_CLASSES_SHORT = {
  "16": "BER",
  "15": "BST",
  "14": "ENC",
  "13": "MAG",
  "12": "WIZ",
  "11": "NEC",
  "10": "SHM",
  "9": "ROG",
  "8": "BRD",
  "7": "MNK",
  "6": "DRU",
  "5": "SHD",
  "4": "RNG",
  "3": "PAL",
  "2": "CLR",
  "1": "WAR"
}

export const DB_PLAYER_CLASSES = {
  "1": "Warrior",
  "2": "Cleric",
  "3": "Paladin",
  "4": "Ranger",
  "5": "Shadow Knight",
  "6": "Druid",
  "7": "Monk",
  "8": "Bard",
  "9": "Rogue",
  "10": "Shaman",
  "11": "Necromancer",
  "12": "Wizard",
  "13": "Magician",
  "14": "Enchanter",
  "15": "Beastlord",
  "16": "Berserker",
};

export const DB_CLASSES = {
  "0": "Warrior",
  "1": "Warrior",
  "2": "Cleric",
  "3": "Paladin",
  "4": "Ranger",
  "5": "Shadow Knight",
  "6": "Druid",
  "7": "Monk",
  "8": "Bard",
  "9": "Rogue",
  "10": "Shaman",
  "11": "Necromancer",
  "12": "Wizard",
  "13": "Magician",
  "14": "Enchanter",
  "15": "Beastlord",
  "16": "Berserker",
  "17": "Banker",
  "20": "GM Warrior",
  "21": "GM Cleric",
  "22": "GM Paladin",
  "23": "GM Ranger",
  "24": "GM Shadow Knight",
  "25": "GM Druid",
  "26": "GM Monk",
  "27": "GM Bard",
  "28": "GM Rogue",
  "29": "GM Shaman",
  "30": "GM Necromancer",
  "31": "GM Wizard",
  "32": "GM Magician",
  "33": "GM Enchanter",
  "34": "GM Beastlord",
  "35": "GM Berserker",
  "40": "Banker",
  "41": "Shopkeeper",
  "59": "Discord Merchant",
  "60": "Adventure Recruiter",
  "61": "Adventure Merchant",
  "63": "Tribute Master",
  "64": "Guild Tribute Master",
  "66": "Guild Bank",
  "67": "Radiant Crystal Merchant",
  "68": "Ebon Crystal Merchant",
  "69": "Fellowships",
  "70": "Alternate Currency Merchant",
  "71": "Mercenary Merchant "
};

export const CLASSES = {
  "0": "Warrior",
  "1": "Cleric",
  "2": "Paladin",
  "3": "Ranger",
  "4": "Shadowknight",
  "5": "Druid",
  "6": "Monk",
  "7": "Bard",
  "8": "Rogue",
  "9": "Shaman",
  "10": "Necromancer",
  "11": "Wizard",
  "12": "Magician",
  "13": "Enchanter",
  "14": "Beastlord",
  "15": "Berserker"
}

export const DB_CLASSES_WEAR_SHORT = {
  "65535": "ALL",
  "32768": "BER",
  "16384": "BST",
  "8192": "ENC",
  "4096": "MAG",
  "2048": "WIZ",
  "1024": "NEC",
  "512": "SHM",
  "256": "ROG",
  "128": "BRD",
  "64": "MNK",
  "32": "DRU",
  "16": "SHD",
  "8": "RNG",
  "4": "PAL",
  "2": "CLR",
  "1": "WAR"
}

export const MERCHANT_CLASSES = [40, 41, 59, 61, 67, 68, 70];

