export const EXPANSION_ICONS_SMALL = {
  0: "original.gif",
  1: "kunarkicon.gif",
  2: "veliousicon.gif",
  3: "luclinicon.gif",
  4: "powericon.gif",
  5: "ykeshaicon.gif",
  6: "ldonicon.gif",
  7: "gatesicon.gif",
  8: "omensicon.gif",
  9: "donicon.gif",
  10: "dodicon.png",
  11: "poricon.png",
  12: "serpsicon.gif",
  13: "buried.gif",
  14: "secrets.gif",
  15: "seedsofdestruction.gif",
  16: "underfoot.gif",
  17: "thule.gif",
  18: "alaris.gif",
  19: "fear.gif",
  20: "calloftheforsaken.gif",
  21: "darkenedsea.gif",
  22: "brokenmirror.gif",
  23: "empires.gif",
  24: "scale.gif",
  25: "burning.gif",
  26: "torment.gif",
}

