export const EXPANSION_NAMES = [
  "Classic",
  "The Ruins of Kunark",
  "The Scars of Velious",
  "The Shadows of Luclin",
  "The Planes of Power",
  "The Legacy of Ykesha",
  "Lost Dungeons of Norrath",
  "Gates of Discord",
  "Omens of War",
  "Dragons of Norrath",
  "Depths of Darkhollow",
  "Prophecy of Ro",
  "The Serpent's Spine",
  "The Buried Sea",
  "Secrets of Faydwer",
  "Seeds of Destruction",
  "Underfoot",
  "House of Thule",
  "Veil of Alaris",
  "Rain of Fear",
  "Call of the Forsaken",
  "The Darkened Sea",
  "The Broken Mirror",
  "Empires of Kunark",
  "Ring of Scale",
  "The Burning Lands",
  "Torment of Velious",
]
