export const ITEM_DB_SLOTS = {
  "4194304": "Power Source",
  "2097152": "Ammo",
  "1048576": "Waist",
  "524288": "Feet",
  "262144": "Legs",
  "131072": "Chest",
  "98304": "Fingers",
  "65536": "Finger",
  "32768": "Finger",
  "16384": "Secondary",
  "8192": "Primary",
  "4096": "Hands",
  "2048": "Range",
  "1536": "Wrists",
  "1024": "Wrist",
  "512": "Wrist",
  "256": "Back",
  "128": "Arms",
  "64": "Shoulders",
  "32": "Neck",
  "18": "Ears",
  "16": "Ear",
  "8": "Face",
  "4": "Head",
  "2": "Ear",
  "1": "Charm"
}

export const DB_ITEM_TYPES = {
  "0": "1HS",
  "1": "2HS",
  "2": "Piercing",
  "3": "1HB",
  "4": "2HB",
  "5": "Archery",
  "6": "Unknown",
  "7": "Throwing range items",
  "8": "Shield",
  "9": "Unknown",
  "10": "Armor",
  "11": "Gems",
  "12": "Lockpicks",
  "13": "Unknown",
  "14": "Food",
  "15": "Drink",
  "16": "Light",
  "17": "Combinable",
  "18": "Bandages",
  "19": "Throwing",
  "20": "Scroll",
  "21": "Potion",
  "22": "Unknown",
  "23": "Wind Instrument",
  "24": "Stringed Instrument",
  "25": "Brass Instrument",
  "26": "Percussion Instrument",
  "27": "Arrow",
  "28": "Unknown",
  "29": "Jewelry",
  "30": "Skull",
  "31": "Tome",
  "32": "Note",
  "33": "Key",
  "34": "Coin",
  "35": "2H Piercing",
  "36": "Fishing Pole",
  "37": "Fishing Bait",
  "38": "Alcohol",
  "39": "Key (bis)",
  "40": "Compass",
  "41": "Unknown",
  "42": "Poison",
  "43": "Unknown",
  "44": "Unknown",
  "45": "Martial",
  "46": "Unknown",
  "47": "Unknown",
  "48": "Unknown",
  "49": "Unknown",
  "50": "Unknown",
  "51": "Unknown",
  "52": "Charm",
  "53": "Unknown",
  "54": "Augmentation"
}

export const DB_ITEM_CLASS = {
  0: "Common Item",
  1: "Container",
  2: "Book",
}

export const DB_ITEM_MATERIAL = {
  0: "Cloth",
  1: "Leather",
  2: "Chain",
  3: "Plate",
  4: "Monk",
  5: "Unknown",
  6: "Unknown",
  7: "Kunark",
  8: "Unknown",
  10: "Red Robe",
  11: "Black Robe",
  12: "Yellow Robe",
  13: "Blue Robe",
  14: "Green Robe",
  15: "Purple Robe",
  16: "White Robe",
  17: "Velious",
  18: "Velious",
  19: "Velious",
  20: "Velious",
  21: "Velious",
  22: "Velious",
  23: "Cloth",
  24: "Unknown",
}

export const DB_ITEM_AUG_RESTRICT = {
  "0": "None",
  "1": "Armor Only",
  "2": "Weapons Only",
  "3": "1H Weapons Only",
  "4": "2H Weapons Only",
  "5": "1H Slash Only",
  "6": "1H Blunt Only",
  "7": "Piercing Only",
  "8": "Hand To Hand Only",
  "9": "2H Slash Only",
  "10": "2H Blunt Only",
  "11": "2H Pierce Only",
  "12": "Bows Only"
}

export const DB_ITEM_DEITIES = {
  "65536": "Veeshan",
  "32768": "Tunare",
  "16384": "The Tribunal",
  "8192": "Solusek Ro",
  "4096": "Rodcet Nife",
  "2048": "Rallos Zek",
  "1024": "Quellious",
  "512": "Prexus",
  "256": "Mithaniel Marr",
  "128": "Karana",
  "64": "Innoruuk",
  "32": "Bristlebane",
  "16": "Erollisi Marr",
  "8": "Cazic Thule",
  "4": "Brell Serilis",
  "2": "Bertoxxulous"
}

export const DB_BAG_TYPES = {
  0: 'None',
  1: 'Large Bag',
  2: 'Quiver',
  3: 'Belt Pouch',
  4: 'Wrist Pouch',
  5: 'Backpack',
  6: 'Small Box',
  7: 'Box of Abu-Kar',
  8: 'Crude Fur Bandolier',
  9: 'Kobold Shaman\'s Pouch',
  10: 'Collapsible Toolbox',
  11: 'Sage\'s Box of Research',
  12: 'Marble Mortar and Pestle',
  13: 'Cage of Transmutation',
  14: 'Collapsible Mixing Bowl',
  15: 'Collapsible Spit',
  16: 'Collapsible Sewing Kit',
  17: 'New Tanaan Forge',
  18: 'Feir`Dal Fletching Kit',
  19: 'Portable Drink Barrel',
  20: 'Kejekan Tool Kit',
  21: 'New Tanaan Pottery Wheel',
  22: 'New Tanaan Kiln',
  29: 'Concordance of Research',
  30: 'Spacial Distortion',
  46: 'Tackle Box',
  51: 'Trader\'s Satchel',
  53: 'Augmentation Sealer',
  54: 'Ice Cream Churn',
  55: 'Fan Faire Celebration Shield Ornamentation',
  56: 'Ornamentation Stripping Tool',
  57: 'Urthron\'s Ultimate Unattuner',
  58: 'Trademaster\'s Component Satchel',
  59: 'Collector\'s Dimensional Case',
}

export const ITEM_SIZE = {
  0: "Tiny",
  1: "Small",
  2: "Medium",
  3: "Large",
  4: "Giant",
}

export const ITEM_ELEMENTS = {
  "0": "Unknown",
  "1": "Magic",
  "2": "Fire",
  "3": "Cold",
  "4": "Poison",
  "5": "Disease",
  "6": "Corruption"
}

export const BOOK_TYPES = {
  '-1': 'Old Parchment',
  0: 'None',
  1: 'Tattered Note',
  2: 'Fell Blade Guild Note',
  3: 'Bloodsoaked Note',
  4: 'Water-Stained Ancient Tome',
  5: 'Conium\'s Notebook Part One',
  6: 'The Stone Frum Pazt Vol.I',
  7: 'False Orders',
  8: 'Stupendous Tome',
  9: 'Leathers of the Vale',
  10: 'Old Delivered Book',
  11: 'Liber Brassica Felix v 6',
  12: 'Bloodstained Journal Vol 1',
  13: 'Guktan Warrior Recruit Letter',
  14: 'Foreman Naug\'s Unsigned Report',
  15: 'Elegant Pates',
  16: 'Leatherbound Journal',
  17: 'Dusty Kobold Scroll',
  18: 'The Charasis Tome',
  19: 'Liber Brassica Felix v 3',
  20: 'Liber Brassica Felix v 2',
  21: 'Tattered Note',
  22: 'Singed Scroll',
  23: 'Scroll of Flayed Goblin Skin',
  25: 'Ancient Text',
}
