export const DB_SKILLS = {
  "0": "1H_BLUNT",
  "1": "1H_SLASHING",
  "2": "2H_BLUNT",
  "3": "2H_SLASHING",
  "4": "ABJURATION",
  "5": "ALTERATION",
  "6": "APPLY_POISON",
  "7": "ARCHERY",
  "8": "BACKSTAB",
  "9": "BIND_WOUND",
  "10": "BASH",
  "11": "BLOCKSKILL",
  "12": "BRASS_INSTRUMENTS",
  "13": "CHANNELING",
  "14": "CONJURATION",
  "15": "DEFENSE",
  "16": "DISARM",
  "17": "DISARM_TRAPS",
  "18": "DIVINATION",
  "19": "DODGE",
  "20": "DOUBLE_ATTACK",
  "21": "DRAGON_PUNCH",
  "22": "DUEL_WIELD",
  "23": "EAGLE_STRIKE",
  "24": "EVOCATION",
  "25": "FEIGN_DEATH",
  "26": "FLYING_KICK",
  "27": "FORAGE",
  "28": "HAND_TO_HAND",
  "29": "HIDE",
  "30": "KICK",
  "31": "MEDITATE",
  "32": "MEND",
  "33": "OFFENSE",
  "34": "PARRY",
  "35": "PICK_LOCK",
  "36": "PIERCING",
  "37": "RIPOSTE",
  "38": "ROUND_KICK",
  "39": "SAFE_FALL",
  "40": "SENSE_HEADING",
  "41": "SINGING",
  "42": "SNEAK",
  "43": "SPECIALIZE_ABJURE",
  "44": "SPECIALIZE_ALTERATION",
  "45": "SPECIALIZE_CONJURATION",
  "46": "SPECIALIZE_DIVINATION",
  "47": "SPECIALIZE_EVOCATION",
  "48": "PICK_POCKETS",
  "49": "STRINGED_INSTRUMENTS",
  "50": "SWIMMING",
  "51": "THROWING",
  "52": "CLICKY",
  "53": "TRACKING",
  "54": "WIND_INSTRUMENTS",
  "55": "FISHING",
  "56": "POISON_MAKING",
  "57": "TINKERING",
  "58": "RESEARCH",
  "59": "ALCHEMY",
  "60": "BAKING",
  "61": "TAILORING",
  "62": "SENSE_TRAPS",
  "63": "BLACKSMITHING",
  "64": "FLETCHING",
  "65": "BREWING",
  "66": "ALCOHOL_TOLERANCE",
  "67": "BEGGING",
  "68": "JEWELRY_MAKING",
  "69": "POTTERY",
  "70": "PERCUSSION_INSTRUMENTS",
  "71": "INTIMIDATION",
  "72": "BERSERKING",
  "73": "TAUNT"
}

export const DB_ITEM_SKILLS = {
  "0": "One Hand Slash",
  "1": "Two Hands Slash",
  "2": "Piercing",
  "3": "One Hand Blunt",
  "4": "Two Hands Blunt",
  "45": "Hand to hand"
}

export const ITEM_WEAPONS = {
  "0": "1HS",
  "1": "2HS",
  "2": "1HP",
  "3": "1HB",
  "4": "2HB",
  "35": "2HP",
}

export const DB_BARD_SKILLS = {
  "23": "Wind",
  "24": "Strings",
  "25": "Brass",
  "26": "Percussions",
  "51": "All instruments"
}
