export const SPA_DEFINITIONS = {
  0: {
    spa: 'SE_CurrentHP',
    effectName: 'Current HP',
    implemented: 1,
    isBuff: 1,
    description: 'Hit Points',
    base: 'amount',
    limit: 'target restriction id',
    value: 'max amount (use positive value)',
    bonusCalc: '',
    notes: 'Negative base value for damage | Positive base value for healing'
  },
  1: {
    spa: 'SE_ArmorClass',
    effectName: 'AC',
    implemented: 1,
    isBuff: 1,
    description: 'Stat',
    base: 'amount',
    limit: 'none',
    value: 'amount',
    bonusCalc: '',
    notes: ''
  },
  2: {
    spa: 'SE_ATK',
    effectName: 'ATK',
    implemented: 1,
    isBuff: 1,
    description: 'Stat',
    base: 'amount',
    limit: 'none',
    value: 'amount',
    bonusCalc: '',
    notes: ''
  },
  3: {
    spa: 'SE_MovementSpeed',
    effectName: 'Movement Rate',
    implemented: 1,
    isBuff: 1,
    description: 'Movement',
    base: 'amount',
    limit: 'none',
    value: 'amount',
    bonusCalc: '',
    notes: ''
  },
  4: {
    spa: 'SE_STR',
    effectName: 'STR',
    implemented: 1,
    isBuff: 1,
    description: 'Stat',
    base: 'amount',
    limit: 'none',
    value: 'amount',
    bonusCalc: '',
    notes: ''
  },
  5: {
    spa: 'SE_DEX',
    effectName: 'DEX',
    implemented: 1,
    isBuff: 1,
    description: 'Stat',
    base: 'amount',
    limit: 'none',
    value: 'amount',
    bonusCalc: '',
    notes: ''
  },
  6: {
    spa: 'SE_AGI',
    effectName: 'AGI',
    implemented: 1,
    isBuff: 1,
    description: 'Stat',
    base: 'amount',
    limit: 'none',
    value: 'amount',
    bonusCalc: '',
    notes: ''
  },
  7: {
    spa: 'SE_STA',
    effectName: 'STA',
    implemented: 1,
    isBuff: 1,
    description: 'Stat',
    base: 'amount',
    limit: 'none',
    value: 'amount',
    bonusCalc: '',
    notes: ''
  },
  8: {
    spa: 'SE_INT',
    effectName: 'INT',
    implemented: 1,
    isBuff: 1,
    description: 'Stat',
    base: 'amount',
    limit: 'none',
    value: 'amount',
    bonusCalc: '',
    notes: ''
  },
  9: {
    spa: 'SE_WIS',
    effectName: 'WIS',
    implemented: 1,
    isBuff: 1,
    description: 'Stat',
    base: 'amount',
    limit: 'none',
    value: 'amount',
    bonusCalc: '',
    notes: ''
  },
  10: {
    spa: 'SE_CHA',
    effectName: 'CHA',
    implemented: 1,
    isBuff: 1,
    description: 'Stat',
    base: 'amount',
    limit: 'none',
    value: 'amount',
    bonusCalc: '',
    notes: ''
  },
  11: {
    spa: 'SE_AttackSpeed',
    effectName: 'Melee Speed',
    implemented: 1,
    isBuff: 1,
    description: 'Melee Speed',
    base: 'percent haste or slow',
    limit: 'none',
    value: 'none',
    bonusCalc: 'Highest',
    notes: 'Base greater than 100 for haste (120 = 20 pct haste) |  Base less than 100 for slow (80 = 20 pct slow)'
  },
  12: {
    spa: 'SE_Invisibility',
    effectName: 'Invisibility: Unstable',
    implemented: 1,
    isBuff: 1,
    description: 'Invisibility',
    base: 'invisibility level',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Invisibility level determines what level of see invisible can detect it.'
  },
  13: {
    spa: 'SE_SeeInvis',
    effectName: 'See Invisible',
    implemented: 1,
    isBuff: 1,
    description: 'Invisibility',
    base: 'see invisible level',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'See Invisible level determines what level of invisible it can see.'
  },
  14: {
    spa: 'SE_WaterBreathing',
    effectName: 'SE_WaterBreathing',
    implemented: 1,
    isBuff: 1,
    description: 'Beneficial Uncategorized',
    base: '1 (increase for stacking overwrite)',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  15: {
    spa: 'SE_CurrentMana',
    effectName: 'Mana',
    implemented: 1,
    isBuff: 1,
    description: 'Mana',
    base: 'amount',
    limit: 'none',
    value: 'max amount (use positive value)',
    bonusCalc: '',
    notes: ''
  },
  16: {
    spa: 'SE_NPCFrenzy',
    effectName: 'NPC Frenzy',
    implemented: 0,
    isBuff:,
    description: 'Unused',
    base: '',
    limit: '',
    value: '',
    bonusCalc: '',
    notes: ''
  },
  17: {
    spa: 'SE_NPCAwareness',
    effectName: 'NPC Awareness',
    implemented: 0,
    isBuff:,
    description: 'Unused',
    base: '',
    limit: '',
    value: '',
    bonusCalc: '',
    notes: ''
  },
  18: {
    spa: 'SE_Lull',
    effectName: 'Pacify',
    implemented: 1,
    isBuff: 1,
    description: 'Aggro',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  19: {
    spa: 'SE_AddFaction',
    effectName: 'NPC Faction',
    implemented: 1,
    isBuff: 1,
    description: 'Faction',
    base: 'amount',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  20: {
    spa: 'SE_Blind',
    effectName: 'Blindness',
    implemented: 1,
    isBuff: 1,
    description: 'Detrimental Uncategorized',
    base: '1 (increase for stacking overwrite)',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  21: {
    spa: 'SE_Stun',
    effectName: 'Stun',
    implemented: 1,
    isBuff: 0,
    description: 'Stun',
    base: 'duration ms',
    limit: 'pvp duration ms',
    value: 'max target level',
    bonusCalc: '',
    notes: ''
  },
  22: {
    spa: 'SE_Charm',
    effectName: 'Charm',
    implemented: 1,
    isBuff: 1,
    description: 'Charm',
    base: 'Unknown set to 1',
    limit: 'none',
    value: 'max target level',
    bonusCalc: '',
    notes: ''
  },
  23: {
    spa: 'SE_Fear',
    effectName: 'Fear',
    implemented: 1,
    isBuff: 1,
    description: 'Detrimental Uncategorized',
    base: 'Unknown set to 1',
    limit: 'none',
    value: 'max target level',
    bonusCalc: '',
    notes: ''
  },
  24: {
    spa: 'SE_Stamina',
    effectName: 'Stamina Loss',
    implemented: 1,
    isBuff: 1,
    description: 'Beneficial Uncategorized',
    base: 'amount',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Positive value will reduce endurance upkeep | Negative value will increase endurance upkeep | Live no longer uses this spell effect for endurance regeneration.'
  },
  25: {
    spa: 'SE_BindAffinity',
    effectName: 'Bind Affinity',
    implemented: 1,
    isBuff: 1,
    description: 'Bind',
    base: 'bind id (Set to 1, 2, or 3)',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Bind id allows you set alternate bind points. Bind Point ID (1=Primary, 2=Secondary 3=Tertiary)'
  },
  26: {
    spa: 'SE_Gate',
    effectName: 'Gate',
    implemented: 1,
    isBuff: 0,
    description: 'Teleport',
    base: 'success chance',
    limit: 'bind id  (2 or 3)',
    value: 'none',
    bonusCalc: '',
    notes: 'If limit is not set, you will gate to primary bind location. Bind Point ID (1=Primary, 2=Secondary 3=Tertiary)'
  },
  27: {
    spa: 'SE_CancelMagic',
    effectName: 'Dispel Magic',
    implemented: 1,
    isBuff: 0,
    description: 'Dispel',
    base: 'chance level modifier',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Success chance is based on level difference of caster and caster of the buff, base value raises the casters level by the base amount.'
  },
  28: {
    spa: 'SE_InvisVsUndead',
    effectName: 'Invisibility to Undead: Unstable',
    implemented: 1,
    isBuff: 1,
    description: 'Invisibility',
    base: 'invisibility level',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Invisibility level determines what level of see invisible can detect it.'
  },
  29: {
    spa: 'SE_InvisVsAnimals',
    effectName: 'Invisibility to Animals: Unstable',
    implemented: 1,
    isBuff: 1,
    description: 'Invisibility',
    base: 'invisibility level',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Invisibility level determines what level of see invisible can detect it.'
  },
  30: {
    spa: 'SE_ChangeFrenzyRad',
    effectName: 'NPC Aggro Radius',
    implemented: 1,
    isBuff: 1,
    description: 'Aggro',
    base: 'amount',
    limit: 'none',
    value: 'max target level',
    bonusCalc: '',
    notes: ''
  },
  31: {
    spa: 'SE_Mez',
    effectName: 'Mesmerize',
    implemented: 1,
    isBuff: 1,
    description: 'Detrimental Uncategorized',
    base: '1 (increase for stacking overwrite)',
    limit: 'none',
    value: 'max target level',
    bonusCalc: '',
    notes: 'Higher value of stacking type will always override the lower value. Used if you want one type of mez to overrite another.'
  },
  32: {
    spa: 'SE_SummonItem',
    effectName: 'Summon Item',
    implemented: 1,
    isBuff: 0,
    description: 'Summon',
    base: 'item id',
    limit: 'none',
    value: 'stack amount',
    bonusCalc: '',
    notes: ''
  },
  33: {
    spa: 'SE_SummonPet',
    effectName: 'Summon Pet',
    implemented: 1,
    isBuff: 0,
    description: 'Pet',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Set \'Teleport Zone\' field to be the same as \'type\' field in of the pet you want in the pets table.'
  },
  34: {
    spa: 'SE_Confuse',
    effectName: 'Confuse',
    implemented: 0,
    isBuff:,
    description: 'Unused',
    base: '',
    limit: '',
    value: '',
    bonusCalc: '',
    notes: ''
  },
  35: {
    spa: 'SE_DiseaseCounter',
    effectName: 'Disease Counter',
    implemented: 1,
    isBuff: 1,
    description: 'Cures',
    base: 'amount',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Set to positive values for potency of detrimental spells | Set to negative value for potency of cure spells.'
  },
  36: {
    spa: 'SE_PoisonCounter',
    effectName: 'Poison Counter',
    implemented: 1,
    isBuff: 1,
    description: 'Cures',
    base: 'amount',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Set to positive values for potency of detrimental spells | Set to negative value for potency of cure spells.'
  },
  37: {
    spa: 'SE_DetectHostile',
    effectName: 'Detect Hostile',
    implemented: 0,
    isBuff:,
    description: 'Unused',
    base: '',
    limit: '',
    value: '',
    bonusCalc: '',
    notes: ''
  },
  38: {
    spa: 'SE_DetectMagic',
    effectName: 'Detect Magic',
    implemented: 0,
    isBuff:,
    description: 'Unused',
    base: '',
    limit: '',
    value: '',
    bonusCalc: '',
    notes: ''
  },
  39: {
    spa: 'SE_TwinCastBlocker',
    effectName: 'Twincast Blocker',
    implemented: 1,
    isBuff: 1,
    description: 'Stacking',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  40: {
    spa: 'SE_DivineAura',
    effectName: 'Invulnerability',
    implemented: 1,
    isBuff: 1,
    description: 'Beneficial Uncategorized',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: 'Bool',
    notes: ''
  },
  41: {
    spa: 'SE_Destroy',
    effectName: 'Destroy',
    implemented: 1,
    isBuff: 0,
    description: 'Hit Points',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  42: {
    spa: 'SE_ShadowStep',
    effectName: 'Shadow Step',
    implemented: 1,
    isBuff: 1,
    description: 'Movement Speed',
    base: 'Unknown (Seen 1 to 50)',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'This effect is handled by the client. Changing the base value does not appear to have any affect.'
  },
  43: {
    spa: 'SE_Berserk',
    effectName: 'Berserk',
    implemented: 1,
    isBuff: 1,
    description: 'Offensive Bonus',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: 'Bool',
    notes: 'This is an unused live spell effect. Custom Spell Effect may be subject to change if live reuses the SPA.'
  },
  44: {
    spa: 'SE_Lycanthropy',
    effectName: 'Stacking:  Delayed Heal Marker',
    implemented: 1,
    isBuff: 1,
    description: 'Stacking',
    base: '',
    limit: '',
    value: '',
    bonusCalc: '',
    notes: ''
  },
  45: {
    spa: 'SE_Vampirism',
    effectName: 'Vampirism',
    implemented: 1,
    isBuff: 1,
    description: 'Offensive Bonus',
    base: 'Percentage',
    limit: 'none',
    value: 'none',
    bonusCalc: 'Additive',
    notes: 'This is an unused live spell effect. Custom Spell Effect may be subject to change if live reuses the SPA.'
  },
  46: {
    spa: 'SE_ResistFire',
    effectName: 'Fire Resist',
    implemented: 1,
    isBuff: 1,
    description: 'Resist',
    base: 'amout',
    limit: 'none',
    value: 'max amount',
    bonusCalc: '',
    notes: ''
  },
  47: {
    spa: 'SE_ResistCold',
    effectName: 'Cold Resist',
    implemented: 1,
    isBuff: 1,
    description: 'Resist',
    base: 'amout',
    limit: 'none',
    value: 'max amount',
    bonusCalc: '',
    notes: ''
  },
  48: {
    spa: 'SE_ResistPoison',
    effectName: 'Poison Resist',
    implemented: 1,
    isBuff: 1,
    description: 'Resist',
    base: 'amout',
    limit: 'none',
    value: 'max amount',
    bonusCalc: '',
    notes: ''
  },
  49: {
    spa: 'SE_ResistDisease',
    effectName: 'Disease Resist',
    implemented: 1,
    isBuff: 1,
    description: 'Resist',
    base: 'amout',
    limit: 'none',
    value: 'max amount',
    bonusCalc: '',
    notes: ''
  },
  50: {
    spa: 'SE_ResistMagic',
    effectName: 'Magic Resist',
    implemented: 1,
    isBuff: 1,
    description: 'Resist',
    base: 'amout',
    limit: 'none',
    value: 'max amount',
    bonusCalc: '',
    notes: ''
  },
  51: {
    spa: 'SE_DetectTraps',
    effectName: 'Detect Traps',
    implemented: 0,
    isBuff:,
    description: 'Unused',
    base: '',
    limit: '',
    value: '',
    bonusCalc: '',
    notes: ''
  },
  52: {
    spa: 'SE_SenseDead',
    effectName: 'Detect Undead',
    implemented: 1,
    isBuff: 0,
    description: 'Tracking',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  53: {
    spa: 'SE_SenseSummoned',
    effectName: 'Detect Summoned',
    implemented: 1,
    isBuff: 0,
    description: 'Tracking',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  54: {
    spa: 'SE_SenseAnimals',
    effectName: 'Detect Animals',
    implemented: 1,
    isBuff: 0,
    description: 'Tracking',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  55: {
    spa: 'SE_Rune',
    effectName: 'Rune',
    implemented: 1,
    isBuff: 1,
    description: 'Rune',
    base: 'amount',
    limit: 'none',
    value: 'max amount',
    bonusCalc: '',
    notes: ''
  },
  56: {
    spa: 'SE_TrueNorth',
    effectName: 'True North',
    implemented: 1,
    isBuff: 0,
    description: 'Tracking',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  57: {
    spa: 'SE_Levitate',
    effectName: 'Levitation',
    implemented: 1,
    isBuff: 1,
    description: 'Beneficial Uncategorized',
    base: '1 (increase for stacking overwrite)',
    limit: 'levitate while moving (Set to 1)',
    value: 'none',
    bonusCalc: '',
    notes: 'Levitate while moving is seen on Live \'Flying Mounts\''
  },
  58: {
    spa: 'SE_Illusion',
    effectName: 'Illusion',
    implemented: 1,
    isBuff: 1,
    description: 'Beneficial Uncategorized',
    base: 'race id or gender id',
    limit: 'texture id (see notes)',
    value: 'helmet id (see notes)',
    bonusCalc: '',
    notes: 'Illusions have complicated rules. See https://docs.eqemu.io/server/categories/spells/illusion-spell-guidelines'
  },
  59: {
    spa: 'SE_DamageShield',
    effectName: 'Damage Shield',
    implemented: 1,
    isBuff: 1,
    description: 'Damage Shield',
    base: 'amount',
    limit: 'none',
    value: 'max amount',
    bonusCalc: '',
    notes: ''
  },
  60: {
    spa: 'SE_TransferItem',
    effectName: 'Transfer Item',
    implemented: 0,
    isBuff:,
    description: 'not used',
    base: '',
    limit: '',
    value: '',
    bonusCalc: '',
    notes: ''
  },
  61: {
    spa: 'SE_Identify',
    effectName: 'Identify',
    implemented: 1,
    isBuff: 0,
    description: 'Beneficial Uncategorized',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'To use, hold item on cursor and cast spell on self or target. The \'lore\' field from items table is displayed in chat window.'
  },
  62: {
    spa: 'SE_ItemID',
    effectName: 'Item ID',
    implemented: 0,
    isBuff:,
    description: 'Unused',
    base: '',
    limit: '',
    value: '',
    bonusCalc: '',
    notes: ''
  },
  63: {
    spa: 'SE_WipeHateList',
    effectName: 'Memblur',
    implemented: 1,
    isBuff: 1,
    description: 'Memory Blur',
    base: 'percent chance',
    limit: 'none',
    value: 'unknown',
    bonusCalc: '',
    notes: 'Actual chance to memory blur is much higher than the spells base value, caster level and CHA modifiers are added get the final calculated percent chance'
  },
  64: {
    spa: 'SE_SpinTarget',
    effectName: 'Spin Stun',
    implemented: 1,
    isBuff: 0,
    description: 'Stun',
    base: 'duration ms',
    limit: 'pvp duration ms',
    value: 'max target level',
    bonusCalc: '',
    notes: ''
  },
  65: {
    spa: 'SE_InfraVision',
    effectName: 'Infravision',
    implemented: 1,
    isBuff: 1,
    description: 'Vision',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  66: {
    spa: 'SE_UltraVision',
    effectName: 'Ultravision',
    implemented: 1,
    isBuff: 1,
    description: 'Vision',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  67: {
    spa: 'SE_EyeOfZomm',
    effectName: 'Eye Of Zomm',
    implemented: 1,
    isBuff: 1,
    description: 'Vision',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Set \'Teleport Zone\' field to be the same as \'type\' field in of the pet you want in the pets table.'
  },
  68: {
    spa: 'SE_ReclaimPet',
    effectName: 'Reclaim Energy',
    implemented: 1,
    isBuff: 0,
    description: 'Mana',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  69: {
    spa: 'SE_TotalHP',
    effectName: 'Max HP',
    implemented: 1,
    isBuff: 1,
    description: 'Hit Points',
    base: 'amount',
    limit: 'none',
    value: 'max amount',
    bonusCalc: '',
    notes: ''
  },
  70: {
    spa: 'SE_CorpseBomb',
    effectName: 'Corpse Bomb',
    implemented: 0,
    isBuff:,
    description: 'Unused',
    base: '',
    limit: '',
    value: '',
    bonusCalc: '',
    notes: 'Set \'Teleport Zone\' field to be the same as \'type\' field in of the pet you want in the pets table.'
  },
  71: {
    spa: 'SE_NecPet',
    effectName: 'Create Undead Pet',
    implemented: 1,
    isBuff: 0,
    description: 'Pet',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  72: {
    spa: 'SE_PreserveCorpse',
    effectName: 'Preserve Corpse',
    implemented: 0,
    isBuff:,
    description: 'Unused',
    base: '',
    limit: '',
    value: '',
    bonusCalc: '',
    notes: ''
  },
  73: {
    spa: 'SE_BindSight',
    effectName: 'Bind Sight',
    implemented: 1,
    isBuff: 1,
    description: 'Vision',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  74: {
    spa: 'SE_FeignDeath',
    effectName: 'Feign Death',
    implemented: 1,
    isBuff: 0,
    description: 'Beneficial Uncategorized',
    base: 'success chance',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  75: {
    spa: 'SE_VoiceGraft',
    effectName: 'Voice Graft',
    implemented: 1,
    isBuff: 0,
    description: 'Utility Uncategorized',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  76: {
    spa: 'SE_Sentinel',
    effectName: 'Sentinel',
    implemented: 1,
    isBuff: 0,
    description: 'Not Implemented',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Not implemented on EQEMU'
  },
  77: {
    spa: 'SE_LocateCorpse',
    effectName: 'Locate Corpse',
    implemented: 1,
    isBuff: 0,
    description: 'Tracking',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  78: {
    spa: 'SE_AbsorbMagicAtt',
    effectName: 'Spell Rune',
    implemented: 1,
    isBuff: 1,
    description: 'Rune',
    base: 'amount',
    limit: 'none',
    value: 'max amount',
    bonusCalc: '',
    notes: ''
  },
  79: {
    spa: 'SE_CurrentHPOnce',
    effectName: 'Current HP Once',
    implemented: 1,
    isBuff: 1,
    description: 'Hit points',
    base: 'amount',
    limit: 'target restriction id',
    value: 'max amount',
    bonusCalc: '',
    notes: 'Negative base value for damage | Positive base value for healing'
  },
  80: {
    spa: 'SE_EnchantLight',
    effectName: 'Enchant Light',
    implemented: 0,
    isBuff: 0,
    description: 'Unused',
    base: '',
    limit: '',
    value: '',
    bonusCalc: '',
    notes: ''
  },
  81: {
    spa: 'SE_Revive',
    effectName: 'Resurrect',
    implemented: 1,
    isBuff: 0,
    description: 'Corpse',
    base: 'percentage exp',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  82: {
    spa: 'SE_SummonPC',
    effectName: 'Summon Player',
    implemented: 1,
    isBuff: 0,
    description: 'Utility Uncategorized',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  83: {
    spa: 'SE_Teleport',
    effectName: 'Teleport',
    implemented: 1,
    isBuff: 0,
    description: 'Teleport',
    base: 'coordinate(x,y,z,h)',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Set \'Teleport Zone\' field to zone short name OR set to \'same\' to teleport within same zone. To set all xyzh cooridinates, you have use the following. Use this effectid  only once in first effect slot . Cooridinates defined as effect_base_value1=x effect_base_value2=y effect_base_value3=z effect_base_value4=h'
  },
  84: {
    spa: 'SE_TossUp',
    effectName: 'Gravity Flux',
    implemented: 1,
    isBuff: 0,
    description: 'Detrimental Uncategorized',
    base: 'distance (negative)',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  85: {
    spa: 'SE_WeaponProc',
    effectName: 'Add Melee Proc',
    implemented: 1,
    isBuff: 1,
    description: 'Procs',
    base: 'spellid',
    limit: 'rate modifer',
    value: '',
    bonusCalc: '',
    notes: ''
  },
  86: {
    spa: 'SE_Harmony',
    effectName: 'Reaction Radius',
    implemented: 1,
    isBuff: 1,
    description: 'Aggro',
    base: 'amount',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  87: {
    spa: 'SE_MagnifyVision',
    effectName: 'Magnification',
    implemented: 1,
    isBuff: 1,
    description: 'Vision',
    base: 'amount',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  88: {
    spa: 'SE_Succor',
    effectName: 'Evacuate',
    implemented: 1,
    isBuff: 0,
    description: 'Teleport',
    base: 'coordinate(x,y,z,h)',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Set \'Teleport Zone\' field to zone short name OR set to \'same\' to evac within same zone. To set all xyzh cooridinates, you have use the following. Use this effectid only once in first effect slot . Cooridinates defined as effect_base_value1=x effect_base_value2=y effect_base_value3=z effect_base_value4=h'
  },
  89: {
    spa: 'SE_ModelSize',
    effectName: 'Player Size',
    implemented: 1,
    isBuff: 0,
    description: 'Utility Uncategorized',
    base: 'percent shrink or grow',
    limit: 'model size',
    value: 'unknown',
    bonusCalc: '',
    notes: 'Base greater than 100 for growth (120 = 20 pct growth) |  Base less than 100 for shrink (80 = 20 pct shrink) | To set to a specific model size, set base to 100 or 0 and then set limit to model size value.'
  },
  90: {
    spa: 'SE_Cloak',
    effectName: 'Ignore Pet',
    implemented: 0,
    isBuff:,
    description: 'Not Implemented',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Not implemented on EQEMU'
  },
  91: {
    spa: 'SE_SummonCorpse',
    effectName: 'Summon Corpse',
    implemented: 1,
    isBuff: 0,
    description: 'Corpse',
    base: 'max target level',
    limit: '',
    value: '',
    bonusCalc: '',
    notes: ''
  },
  92: {
    spa: 'SE_InstantHate',
    effectName: 'Hate',
    implemented: 1,
    isBuff: 0,
    description: 'Aggro',
    base: 'amount',
    limit: '',
    value: 'max amount',
    bonusCalc: '',
    notes: 'Positive value increases hate. | Negative value decreases hate.'
  },
  93: {
    spa: 'SE_StopRain',
    effectName: 'Control Weather',
    implemented: 1,
    isBuff: 0,
    description: 'Utility Uncategorized',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  94: {
    spa: 'SE_NegateIfCombat',
    effectName: 'Make Fragile',
    implemented: 1,
    isBuff: 1,
    description: 'Restriction',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  95: {
    spa: 'SE_Sacrifice',
    effectName: 'Sacrifice',
    implemented: 1,
    isBuff: 0,
    description: 'Utility Uncategorized',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  96: {
    spa: 'SE_Silence',
    effectName: 'Silence',
    implemented: 1,
    isBuff: 1,
    description: 'Silence',
    base: '1 (increase for stacking overwrite)',
    limit: 'none',
    value: 'unknown',
    bonusCalc: '',
    notes: ''
  },
  97: {
    spa: 'SE_ManaPool',
    effectName: 'Max Mana',
    implemented: 1,
    isBuff: 1,
    description: 'Mana',
    base: 'amount',
    limit: 'none',
    value: 'max amount',
    bonusCalc: '',
    notes: ''
  },
  98: {
    spa: 'SE_AttackSpeed2',
    effectName: 'Melee Speed: Does not exceed cap',
    implemented: 1,
    isBuff: 1,
    description: 'Melee Speed',
    base: 'percent haste or slow',
    limit: 'none',
    value: 'none',
    bonusCalc: 'Highest',
    notes: 'Base greater than 100 for haste (120 = 20 pct haste) |  Base less than 100 for slow (80 = 20 pct slow)'
  },
  99: {
    spa: 'SE_Root',
    effectName: 'Root',
    implemented: 1,
    isBuff: 1,
    description: 'Movement Speed',
    base: '-10000',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  100: {
    spa: 'SE_HealOverTime',
    effectName: 'Heal Over Time',
    implemented: 1,
    isBuff: 1,
    description: 'Hit Points',
    base: 'amount',
    limit: 'target restriction id',
    value: 'max amount',
    bonusCalc: '',
    notes: ''
  },
  101: {
    spa: 'SE_CompleteHeal',
    effectName: 'Complete Heal: With Recast Blocker Buff',
    implemented: 1,
    isBuff: 1,
    description: 'Hit Points',
    base: 'heal amount multiplier',
    limit: 'none',
    value: 'max heal amount multipler',
    bonusCalc: '',
    notes: ''
  },
  102: {
    spa: 'SE_Fearless',
    effectName: 'Fear Immunity',
    implemented: 1,
    isBuff: 1,
    description: 'Resist',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: 'Bool',
    notes: ''
  },
  103: {
    spa: 'SE_CallPet',
    effectName: 'Summon Pet',
    implemented: 1,
    isBuff: 0,
    description: 'Pet',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  104: {
    spa: 'SE_Translocate',
    effectName: 'Translocate',
    implemented: 1,
    isBuff: 0,
    description: 'Teleport',
    base: 'coordinate(x,y,z,h) or Bind Point ID',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Set \'Teleport Zone\' field to zone short name OR set to \'same\' to evac within same zone. To set all xyzh cooridinates, you have use the following. Use this effectid only once in first effect slot . If \'Teleport_Zone\' field is not set, then will send to  bind point id, set base value to Bind Point ID (1=Primary, 2=Secondary 3=Tertiary)'
  },
  105: {
    spa: 'SE_AntiGate',
    effectName: 'Inhibit Gate',
    implemented: 1,
    isBuff: 0,
    description: 'Teleport',
    base: 'Seen 1 to 3',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Unclear what base value determines. May be related to Bind Point IDs.'
  },
  106: {
    spa: 'SE_SummonBSTPet',
    effectName: 'Summon Warder',
    implemented: 1,
    isBuff: 0,
    description: 'Pet',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Set \'Teleport Zone\' field to be the same as \'type\' field in of the pet you want in the pets table.'
  },
  107: {
    spa: 'SE_AlterNPCLevel',
    effectName: 'Alter NPC Level',
    implemented: 1,
    isBuff: 0,
    description: 'Utility Uncategorized',
    base: 'amount',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'This is a no longer used on live. Custom Spell Effect may be subject to change if live reuses the SPA.'
  },
  108: {
    spa: 'SE_Familiar',
    effectName: 'Summon Familiar',
    implemented: 1,
    isBuff: 0,
    description: 'Pet',
    base: '0 or 1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Set \'Teleport Zone\' field to be the same as \'type\' field in of the pet you want in the pets table.'
  },
  109: {
    spa: 'SE_SummonItemIntoBag',
    effectName: 'Summon into Bag',
    implemented: 1,
    isBuff: 0,
    description: 'Summon',
    base: 'item id',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'To use this the first effectid must be SPA 32 SE_SummonItem and this must be a bag such as Phantom Satchel ID 17310. Then use this effectid to summon items that will go into that bag.'
  },
  110: {
    spa: 'SE_IncreaseArchery',
    effectName: 'Archery (not used)',
    implemented: 0,
    isBuff:,
    description: 'Not used',
    base: '',
    limit: '',
    value: '',
    bonusCalc: '',
    notes: ''
  },
  111: {
    spa: 'SE_ResistAll',
    effectName: 'All Resists',
    implemented: 1,
    isBuff: 1,
    description: 'Resists',
    base: 'amount',
    limit: 'none',
    value: 'max amount',
    bonusCalc: '',
    notes: ''
  },
  112: {
    spa: 'SE_CastingLevel',
    effectName: 'Casting Level',
    implemented: 1,
    isBuff: 1,
    description: 'Casting',
    base: 'amount',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  113: {
    spa: 'SE_SummonHorse',
    effectName: 'Summon Mount',
    implemented: 1,
    isBuff: 1,
    description: 'Summon',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Set \'Teleport Zone\' field to be the same as \'filename\' field in of the mount you want in the horses table.'
  },
  114: {
    spa: 'SE_ChangeAggro',
    effectName: 'Hate Multiplier',
    implemented: 1,
    isBuff: 1,
    description: 'Aggro',
    base: 'percent hate modifer',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  115: {
    spa: 'SE_Hunger',
    effectName: 'Food',
    implemented: 1,
    isBuff: 1,
    description: 'Beneficial Uncategorized',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Set to positive values for potency of detrimental spells | Set to negative value for potency of cure spells.'
  },
  116: {
    spa: 'SE_CurseCounter',
    effectName: 'Curse Counter',
    implemented: 1,
    isBuff: 1,
    description: 'Cures',
    base: 'amount',
    limit: '',
    value: '',
    bonusCalc: '',
    notes: ''
  },
  117: {
    spa: 'SE_MagicWeapon',
    effectName: 'Make Weapons Magical',
    implemented: 1,
    isBuff: 1,
    description: 'Beneficial Uncategorized',
    base: '1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  118: {
    spa: 'SE_Amplification',
    effectName: 'Singing Amplification',
    implemented: 1,
    isBuff: 1,
    description: 'Songs',
    base: 'percent',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Recasting this effect will cause it to focus itself, increasing its potency.'
  },
  119: {
    spa: 'SE_AttackSpeed3',
    effectName: 'Melee Speed: Overhaste',
    implemented: 1,
    isBuff: 1,
    description: 'Melee Speed',
    base: 'percent haste or slow',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Base greater than 100 for haste (120 = 20 pct haste) |  Base less than 100 for slow (80 = 20 pct slow)'
  },
  120: {
    spa: 'SE_HealRate',
    effectName: 'Incoming Healing Effectiveness',
    implemented: 1,
    isBuff: 1,
    description: 'Healing Modifer',
    base: 'percent healing',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  121: {
    spa: 'SE_ReverseDS',
    effectName: 'Reverse Damage Shield',
    implemented: 1,
    isBuff: 1,
    description: 'Damage Shield',
    base: 'amount',
    limit: '',
    value: '',
    bonusCalc: '',
    notes: 'Negative value will cause the reverse damage shield to heal.'
  },
  122: {
    spa: 'SE_ReduceSkill',
    effectName: 'Reduce Skill',
    implemented: 0,
    isBuff: 1,
    description: 'Not Implemented',
    base: 'pending',
    limit: 'pending',
    value: 'pending',
    bonusCalc: '',
    notes: 'not implemented'
  },
  123: {
    spa: 'SE_Screech',
    effectName: 'Stacking:  Screech',
    implemented: 1,
    isBuff: 1,
    description: 'Stacking',
    base: '1 or -1',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  124: {
    spa: 'SE_ImprovedDamage',
    effectName: 'Focus: Spell Damage',
    implemented: 1,
    isBuff: 1,
    description: 'Focus',
    base: 'min percent',
    limit: 'none',
    value: 'max percent',
    bonusCalc: '',
    notes: 'Use random effectiveness if base and max value are defined, where base is always lower end and max the higher end of the random range. If random value not wanted, then only set a base value.'
  },
  125: {
    spa: 'SE_ImprovedHeal',
    effectName: 'Focus: Healing',
    implemented: 1,
    isBuff: 1,
    description: 'Focus',
    base: 'min percent',
    limit: 'none',
    value: 'max percent',
    bonusCalc: '',
    notes: 'Use random effectiveness if base and max value are defined, where base is always lower end and max the higher end of the random range. If random value not wanted, then only set a base value.'
  },
  126: {
    spa: 'SE_SpellResistReduction',
    effectName: 'Focus: Spell Resist Rate',
    implemented: 1,
    isBuff: 1,
    description: 'Focus',
    base: 'min percent',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  127: {
    spa: 'SE_IncreaseSpellHaste',
    effectName: 'Focus: Spell Cast Time',
    implemented: 1,
    isBuff: 1,
    description: 'Focus',
    base: 'percent',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  128: {
    spa: 'SE_IncreaseSpellDuration',
    effectName: 'Focus: Spell Duration',
    implemented: 1,
    isBuff: 1,
    description: 'Focus',
    base: 'percent',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  129: {
    spa: 'SE_IncreaseRange',
    effectName: 'Focus: Spell Range',
    implemented: 1,
    isBuff: 1,
    description: 'Focus',
    base: 'percent',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  130: {
    spa: 'SE_SpellHateMod',
    effectName: 'Focus: Spell and Bash Hate',
    implemented: 1,
    isBuff: 1,
    description: 'Focus',
    base: 'min percent',
    limit: 'none',
    value: 'max percent',
    bonusCalc: '',
    notes: 'Use random effectiveness if base and max value are defined, where base is always lower end and max the higher end of the random range. If random value not wanted, then only set a base value. | Special case: For bash hate to be focused, need to add focus limit SPA 137 and set it to 999.'
  },
  131: {
    spa: 'SE_ReduceReagentCost',
    effectName: 'Focus: Chance of Using Reagent',
    implemented: 1,
    isBuff: 1,
    description: 'Focus',
    base: 'min percent',
    limit: 'none',
    value: 'max percent',
    bonusCalc: '',
    notes: 'Use random effectiveness if base and max value are defined, where base is always lower end and max the higher end of the random range. If random value not wanted, then only set a base value.'
  },
  132: {
    spa: 'SE_ReduceManaCost',
    effectName: 'Focus: Spell Mana Cost',
    implemented: 1,
    isBuff: 1,
    description: 'Focus',
    base: 'min percent',
    limit: 'none',
    value: 'max percent',
    bonusCalc: '',
    notes: 'Use random effectiveness if base and max value are defined, where base is always lower end and max the higher end of the random range. If random value not wanted, then only set a base value.'
  },
  133: {
    spa: 'SE_FcStunTimeMod',
    effectName: 'Focus: Spell Stun Duration',
    implemented: 1,
    isBuff: 1,
    description: 'Focus',
    base: 'percent',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  134: {
    spa: 'SE_LimitMaxLevel',
    effectName: 'Limit:  Max Level',
    implemented: 1,
    isBuff: 1,
    description: 'Limit',
    base: 'max level',
    limit: 'effectiviness percent',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  135: {
    spa: 'SE_LimitResist',
    effectName: 'Limit:  Resist',
    implemented: 1,
    isBuff: 1,
    description: 'Limit',
    base: 'resist type',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Include set value to positive | Exclude set value to negative'
  },
  136: {
    spa: 'SE_LimitTarget',
    effectName: 'Limit:  Target',
    implemented: 1,
    isBuff: 1,
    description: 'Limit',
    base: 'target type',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Include set value to positive | Exclude set value to negative'
  },
  137: {
    spa: 'SE_LimitEffect',
    effectName: 'Limit:  Effect',
    implemented: 1,
    isBuff: 1,
    description: 'Limit',
    base: 'spell effect ID',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Include set value to positive | Exclude set value to negative'
  },
  138: {
    spa: 'SE_LimitSpellType',
    effectName: 'Limit:  SpellType',
    implemented: 1,
    isBuff: 1,
    description: 'Limit',
    base: '0=Detrimental,  1=Beneficial',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  139: {
    spa: 'SE_LimitSpell',
    effectName: 'Limit:  Spell',
    implemented: 1,
    isBuff: 1,
    description: 'Limit',
    base: 'spell ID',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Include set value to positive | Exclude set value to negative'
  },
  140: {
    spa: 'SE_LimitMinDur',
    effectName: 'Limit:  Min Duration',
    implemented: 1,
    isBuff: 1,
    description: 'Limit',
    base: 'tics',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Set duration in tics, 1 tick is 6 seconds of game time'
  },
  141: {
    spa: 'SE_LimitInstant',
    effectName: 'Limit:  Instant spells only',
    implemented: 1,
    isBuff: 1,
    description: 'Limit',
    base: '0=Exclude if Instant, 1=Allow only if Instant',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  142: {
    spa: 'SE_LimitMinLevel',
    effectName: 'Limit:  Min Level',
    implemented: 1,
    isBuff: 1,
    description: 'Limit',
    base: 'level',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  143: {
    spa: 'SE_LimitCastTimeMin',
    effectName: 'Limit:  Min Cast Time',
    implemented: 1,
    isBuff: 1,
    description: 'Limit',
    base: 'milliseconds',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  144: {
    spa: 'SE_LimitCastTimeMax',
    effectName: 'Limit:  Max Cast Time',
    implemented: 1,
    isBuff: 1,
    description: 'Limit',
    base: 'milliseconds',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  145: {
    spa: 'SE_Teleport2',
    effectName: 'Banish',
    implemented: 1,
    isBuff: 0,
    description: 'Teleport',
    base: 'coordinate(x,y,z,h)',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Set \'Teleport Zone\' field to zone short name  OR set to \'same\' to teleport within same zone. To set all xyzh cooridinates, you have use the following. Use this effectid only once in first effect slot . Cooridinates defined as effect_base_value1=x effect_base_value2=y effect_base_value3=z effect_base_value4=h'
  },
  146: {
    spa: 'SE_ElectricityResist',
    effectName: 'Portal Locations',
    implemented: 0,
    isBuff: 0,
    description: 'Not Implementd',
    base: 'pending',
    limit: 'pending',
    value: 'pending',
    bonusCalc: '',
    notes: ''
  },
  147: {
    spa: 'SE_PercentalHeal',
    effectName: 'Percent HP Heal',
    implemented: 1,
    isBuff: 0,
    description: 'Hit Points',
    base: 'percentage',
    limit: 'none',
    value: 'max amount of hit points',
    bonusCalc: '',
    notes: 'Negative base value for damage | Positive base value for healing'
  },
  148: {
    spa: 'SE_StackingCommand_Block',
    effectName: 'Stacking:  Block',
    implemented: 1,
    isBuff: 0,
    description: 'Stacking',
    base: '',
    limit: '',
    value: '',
    bonusCalc: '',
    notes: ''
  },
  149: {
    spa: 'SE_StackingCommand_Overwrite',
    effectName: 'Stacking:  Overwrite',
    implemented: 1,
    isBuff: 0,
    description: 'Stacking',
    base: '',
    limit: '',
    value: '',
    bonusCalc: '',
    notes: ''
  },
  150: {
    spa: 'SE_DeathSave',
    effectName: 'Death Save',
    implemented: 1,
    isBuff: 1,
    description: 'Death Save',
    base: '1 = 300 HP Healed,  2 = 8000 HP Healed',
    limit: 'min target level to apply override heal amount',
    value: 'override heal amount',
    bonusCalc: '',
    notes: 'If max value is set as heal amount this value will be used instead as the heal amount if the owner of the buff is the mininum level specified in limit field. Chance to receive a heal is determined by the owner of the buffs Charisma. [Chance = ((Charisma * 3) +1) / 10) ] . SPA 277 gives a second chance to be healed if you fail.'
  },
  151: {
    spa: 'SE_SuspendPet',
    effectName: 'Suspend Pet',
    implemented: 1,
    isBuff: 0,
    description: 'Pet',
    base: 'save type',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Save Types, 0 = save pet with no buffs or equipment, 1 = save pet with no buffs or equipment, 2 = unknown.  SPA 308 allows for suspended pets to be resummoned after zoning.'
  },
  152: {
    spa: 'SE_TemporaryPets',
    effectName: 'Summon a Pet Swarm',
    implemented: 1,
    isBuff: 0,
    description: 'Pet',
    base: 'amount of pets',
    limit: 'none',
    value: 'duration seconds',
    bonusCalc: '',
    notes: 'Set \'Teleport Zone\' field to be the same as \'type\' field in of the pet you want in the pets table.'
  },
  153: {
    spa: 'SE_BalanceHP',
    effectName: 'Balance Party HP',
    implemented: 1,
    isBuff: 0,
    description: 'Hit Points',
    base: 'percent modifier',
    limit: 'max HP taken from player',
    value: 'none',
    bonusCalc: '',
    notes: 'Positive base value increases damage being  distrubuted | Negative base value decreases the damage being distributed'
  },
  154: {
    spa: 'SE_DispelDetrimental',
    effectName: 'Dispel Detrimental',
    implemented: 1,
    isBuff: 0,
    description: 'Dispel',
    base: 'percent chance x 10',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Actual percent chance is calculated as base / 10'
  },
  155: {
    spa: 'SE_SpellCritDmgIncrease',
    effectName: 'Spell Critical Damage',
    implemented: 1,
    isBuff: 1,
    description: 'Spell Modifier',
    base: 'percent modifier',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  156: {
    spa: 'SE_IllusionCopy',
    effectName: 'Illusion:  Target',
    implemented: 1,
    isBuff: 0,
    description: 'Illusion',
    base: 'Seen 0,1,30',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Unknown what base values represent.'
  },
  157: {
    spa: 'SE_SpellDamageShield',
    effectName: 'Spell Damage Shield',
    implemented: 1,
    isBuff: 1,
    description: 'Damage Shield',
    base: 'amount damage shield (negative)',
    limit: 'none',
    value: 'unknown',
    bonusCalc: '',
    notes: 'Spells must have \'feedbackable\' field set to a value otherwise they will not be affected by spell damage shields.'
  },
  158: {
    spa: 'SE_Reflect',
    effectName: 'Reflect Spell',
    implemented: 1,
    isBuff: 1,
    description: 'Beneficial Uncategorized',
    base: 'percent chance',
    limit: 'resist modifier',
    value: 'percent of base damage modifier',
    bonusCalc: '',
    notes: 'Spells must have \'reflectable\' field set to a value otherwise they will not be reflected. Resist modifer, positive value reduces the resist rate, negative value increases the resist rate. Percent of base damage modifer, max greater than 100 for damage mod (120 = 20 pct increase in damage) |  max less than 100 for damage mod (80 = 20 pct decrease in damage)'
  },
  159: {
    spa: 'SE_AllStats',
    effectName: 'All Stats',
    implemented: 1,
    isBuff: 1,
    description: 'STATS',
    base: 'amount',
    limit: 'none',
    value: 'max amount',
    bonusCalc: '',
    notes: 'Effect currently handled entirely client side.'
  },
  160: {
    spa: 'SE_MakeDrunk',
    effectName: 'Drunk',
    implemented: 1,
    isBuff: 1,
    description: 'Detrimental Uncategorized',
    base: 'amount',
    limit: 'none',
    value: 'max amount',
    bonusCalc: '',
    notes: ''
  },
  161: {
    spa: 'SE_MitigateSpellDamage',
    effectName: 'Mitigate Spell Damage Rune',
    implemented: 1,
    isBuff: 1,
    description: 'Rune',
    base: 'percent mitigation',
    limit: 'max damage absorbed per hit',
    value: 'rune amount',
    bonusCalc: '',
    notes: 'Special: If this effect is placed on item as worn effect or as an AA, it will provide stackable percent spell mitigation for the base value.'
  },
  162: {
    spa: 'SE_MitigateMeleeDamage',
    effectName: 'Mitigate Melee Damage Rune',
    implemented: 1,
    isBuff: 1,
    description: 'Rune',
    base: 'percent mitigation',
    limit: 'max damage absorbed per hit',
    value: 'rune amount',
    bonusCalc: '',
    notes: ''
  },
  163: {
    spa: 'SE_NegateAttacks',
    effectName: 'Absorb Damage',
    implemented: 1,
    isBuff: 1,
    description: 'Rune',
    base: 'amount of blocked hits',
    limit: 'none',
    value: 'max amount of damage blocked per hit',
    bonusCalc: '',
    notes: ''
  },
  164: {
    spa: 'SE_AppraiseLDonChest',
    effectName: 'Sense LDoN Chest',
    implemented: 1,
    isBuff: 0,
    description: 'LDON',
    base: '',
    limit: '',
    value: '',
    bonusCalc: '',
    notes: ''
  },
  165: {
    spa: 'SE_DisarmLDoNTrap',
    effectName: 'Disarm LDoN Trap',
    implemented: 1,
    isBuff: 0,
    description: 'LDON',
    base: '',
    limit: '',
    value: '',
    bonusCalc: '',
    notes: ''
  },
  166: {
    spa: 'SE_UnlockLDoNChest',
    effectName: 'Unlock LDoN Chest',
    implemented: 1,
    isBuff: 0,
    description: 'LDON',
    base: '',
    limit: '',
    value: '',
    bonusCalc: '',
    notes: ''
  },
  167: {
    spa: 'SE_PetPowerIncrease',
    effectName: 'Focus: Pet Power',
    implemented: 1,
    isBuff: 1,
    description: 'FOCUS',
    base: 'power value',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Pet power can be scaled automatically if \'petpower\' field in pets table is set to 0 or -1, if the power field is set to anything it will look to find the cooresponding pet in the table with same power for that \'type\'.'
  },
  168: {
    spa: 'SE_MeleeMitigation',
    effectName: 'Defensive',
    implemented: 1,
    isBuff: 1,
    description: 'Defensive Bonus',
    base: 'percent modifer',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Negative base value decreases damage taken | Positive base value increases damage taken'
  },
  169: {
    spa: 'SE_CriticalHitChance',
    effectName: 'Critical Melee Chance',
    implemented: 1,
    isBuff: 1,
    description: 'Offensive Bonus',
    base: 'percent modifer',
    limit: 'skill type (-1 = all skill types)',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  170: {
    spa: 'SE_SpellCritChance',
    effectName: 'Spell Critical Chance',
    implemented: 1,
    isBuff: 1,
    description: 'Spell Modifer',
    base: 'percent modifier',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: 'Must have a chance to perform critical hits in order to have a chance to crippling blow.'
  },
  171: {
    spa: 'SE_CrippBlowChance',
    effectName: 'Crippling Blow Chance',
    implemented: 1,
    isBuff: 1,
    description: 'Offensive Bonus',
    base: 'percent modifer',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  172: {
    spa: 'SE_AvoidMeleeChance',
    effectName: 'Evasion',
    implemented: 1,
    isBuff: 1,
    description: 'Defensive Bonus',
    base: 'percent modifer',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  173: {
    spa: 'SE_RiposteChance',
    effectName: 'Riposte',
    implemented: 1,
    isBuff: 1,
    description: 'Defensive Bonus',
    base: 'percent modifer',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  174: {
    spa: 'SE_DodgeChance',
    effectName: 'Dodge',
    implemented: 1,
    isBuff: 1,
    description: 'Defensive Bonus',
    base: 'percent modifer',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  175: {
    spa: 'SE_ParryChance',
    effectName: 'Parry',
    implemented: 1,
    isBuff: 1,
    description: 'Defensive Bonus',
    base: 'percent modifer',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  176: {
    spa: 'SE_DualWieldChance',
    effectName: 'Dual Wield',
    implemented: 1,
    isBuff: 1,
    description: 'Offensive Bonus',
    base: 'percent modifer',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  177: {
    spa: 'SE_DoubleAttackChance',
    effectName: 'Double Attack',
    implemented: 1,
    isBuff: 1,
    description: 'Offensive Bonus',
    base: 'percent modifer',
    limit: 'none',
    value: 'none',
    bonusCalc: 'Highest',
    notes: 'Positive value will heal you | Negative value will damage you'
  },
  178: {
    spa: 'SE_MeleeLifetap',
    effectName: 'Melee Lifetap',
    implemented: 1,
    isBuff: 1,
    description: 'Offensive Bonus',
    base: 'percentage',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  179: {
    spa: 'SE_AllInstrumentMod',
    effectName: 'All Instrument Modifier',
    implemented: 1,
    isBuff: 1,
    description: 'Songs',
    base: 'modifier percentage',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  180: {
    spa: 'SE_ResistSpellChance',
    effectName: 'Resist Spell Chance',
    implemented: 1,
    isBuff: 1,
    description: 'Resist',
    base: 'percent modifer',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  181: {
    spa: 'SE_ResistFearChance',
    effectName: 'Resist Fear Spell Chance',
    implemented: 1,
    isBuff: 1,
    description: 'Resist',
    base: 'percent modifer',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  182: {
    spa: 'SE_HundredHands',
    effectName: 'Attack Delay Reducation',
    implemented: 1,
    isBuff: 1,
    description: 'Offensive Bonus',
    base: '',
    limit: '',
    value: '',
    bonusCalc: '',
    notes: ''
  },
  183: {
    spa: 'SE_MeleeSkillCheck',
    effectName: 'Melee Skill Chance',
    implemented: 1,
    isBuff: 1,
    description: 'Offensive Bonus',
    base: '',
    limit: '',
    value: '',
    bonusCalc: '',
    notes: ''
  },
  184: {
    spa: 'SE_HitChance',
    effectName: 'Chance to Hit',
    implemented: 1,
    isBuff: 1,
    description: 'Offensive Bonus',
    base: 'percent modifer',
    limit: 'skill type (-1 = all skill types)',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  185: {
    spa: 'SE_DamageModifier',
    effectName: 'Skills Damage Modifier',
    implemented: 1,
    isBuff: 1,
    description: 'Offensive Bonus',
    base: 'percent modifer',
    limit: 'skill type (-1 = all skill types)',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  186: {
    spa: 'SE_MinDamageModifier',
    effectName: 'Skills Minimum Damage Modifier',
    implemented: 1,
    isBuff: 1,
    description: 'Offensive Bonus',
    base: 'percent modifer',
    limit: 'skill type (-1 = all skill types)',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  187: {
    spa: 'SE_BalanceMana',
    effectName: 'Balance Party Mana',
    implemented: 1,
    isBuff: 0,
    description: 'Mana',
    base: 'percent modifer',
    limit: 'max mana taken from player',
    value: 'none',
    bonusCalc: '',
    notes: 'Positive base value increases damage being distributed | Negative base value decreases the damage being distributed'
  },
  188: {
    spa: 'SE_IncreaseBlockChance',
    effectName: 'Chance to block',
    implemented: 1,
    isBuff: 1,
    description: 'Defensive Bonus',
    base: 'percent modifer',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  189: {
    spa: 'SE_CurrentEndurance',
    effectName: 'Endurance',
    implemented: 1,
    isBuff: 1,
    description: 'Endurance',
    base: 'amount',
    limit: 'none',
    value: 'max amount',
    bonusCalc: '',
    notes: ''
  },
  190: {
    spa: 'SE_EndurancePool',
    effectName: 'Max Endurance',
    implemented: 1,
    isBuff: 1,
    description: 'Endurance',
    base: 'amount',
    limit: 'none',
    value: 'max amount',
    bonusCalc: '',
    notes: ''
  },
  191: {
    spa: 'SE_Amnesia',
    effectName: 'Amnesia',
    implemented: 1,
    isBuff: 1,
    description: 'Detrimental Uncategorized',
    base: '1 (increase for stacking overwrite)',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  192: {
    spa: 'SE_Hate',
    effectName: 'Hate',
    implemented: 1,
    isBuff: 1,
    description: 'Aggro',
    base: 'amount',
    limit: 'none',
    value: 'max amount',
    bonusCalc: '',
    notes: ''
  },
  193: {
    spa: 'SE_SkillAttack',
    effectName: 'Skill Attack',
    implemented: 1,
    isBuff: 0,
    description: '',
    base: '',
    limit: '',
    value: '',
    bonusCalc: '',
    notes: ''
  },
  194: {
    spa: 'SE_FadingMemories',
    effectName: 'Fade',
    implemented: 1,
    isBuff: 0,
    description: 'Aggro',
    base: 'success chance',
    limit: 'none',
    value: 'target max level',
    bonusCalc: '',
    notes: 'max value for the target max level is not supported on eqemu at this due to it not actually work on live.'
  },
  195: {
    spa: 'SE_StunResist',
    effectName: 'Stun Resist',
    implemented: 1,
    isBuff: 1,
    description: 'Defensive Bonus',
    base: 'percent modifier',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  196: {
    spa: 'SE_StrikeThrough',
    effectName: 'Strikethrough',
    implemented: 1,
    isBuff: 1,
    description: 'Offensive Bonus',
    base: 'percent modifier',
    limit: 'none',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  197: {
    spa: 'SE_SkillDamageTaken',
    effectName: 'Skill Damage Taken',
    implemented: 1,
    isBuff: 1,
    description: 'Defensive Bonus',
    base: 'percent modifier',
    limit: 'skill type (-1 = all skill types)',
    value: 'none',
    bonusCalc: '',
    notes: ''
  },
  198: {
    spa: 'SE_CurrentEnduranceOnce',
    effectName: 'Instant Endurance',
    implemented: 1,
    isBuff: 0,
    description: 'Endurance',
    base: 'amount',
    limit: 'none',
    value: 'max amount',
    bonusCalc: '',
    notes: 'Negative base value decreases damage taken | Positive base value increases damage taken'
  },
};
