export const BODYTYPES = {
  "0": "Unknown",
  "1": "Humanoid",
  "2": "Lycanthrope",
  "3": "Undead",
  "4": "Giant",
  "5": "Construct",
  "6": "Extra planar",
  "7": "Magical",
  "8": "Summoned undead",
  "9": "Raid Kael Giant",
  "10": "Raid Coldain",
  "11": "No target",
  "12": "Vampire",
  "13": "Atenha Ra",
  "14": "Greater Akheva",
  "15": "Khati Sha",
  "16": "Lord Inquisitor Seru",
  "17": "Grieg Veneficus",
  "18": "Draz Nurakk",
  "19": "Zek",
  "20": "Luggald",
  "21": "Animal",
  "22": "Insect",
  "23": "Monster",
  "24": "Summoned",
  "25": "Plant",
  "26": "Dragon",
  "27": "Summoned Elemental",
  "28": "Warder",
  "29": "Dragon v2",
  "30": "Velious Dragon",
  "31": "Familiar",
  "32": "Dragon v3",
  "33": "Boxes",
  "34": "Muramite",
  "60": "No Target v2",
  "63": "Swarm pet",
  "64": "Monster Summon",
  "65": "Invsible Man",
  "67": "Special"
}
