export const DB_STR_TYPES = {
  0: "Banner Description",
  1: "AA Name",
  2: "Hotkey Line 1",
  3: "Hotkey Line 2",
  4: "AA Desc",
  5: "Spell Effect Type",
  6: "Spell Description",
  7: "Lore Group",
  8: "Race Description",
  9: "Class Description",
  10: "Stat Description",
  11: "Race",
  12: "Races",
  13: "Classes",
  14: "Deity Description",
  15: "City Description",
  16: "Augmentation Type",
  17: "Currency",
  18: "Currencies",
  19: "AA Category",
  20: "Expansion",
  21: "Mercenary Type",
  22: "Mercenary Tier",
  23: "Mercenary Description",
  24: "Mercenary Stance",
  25: "Mercenary Stance Description #1",
  26: "Mercenary Stance Description #2",
  27: "Unknown",
  28: "Button Description",
  29: "Unknown",
  30: "Button Description 2",
  31: "Help Description",
  32: "Button Description 3",
  33: "Button Description 4",
  34: "Achievement",
  35: "Achievement 2",
  36: "Mercenary Class",
  37: "Unknown",
  38: "Unknown",
  71: "Token",
};
