export const DB_SKILLS = {
  "-1": "Hit",
  "0": "1H Blunt",
  "1": "1H Slashing",
  "2": "2H Blunt",
  "3": "2H Slashing",
  "4": "Abjuration",
  "5": "Alteration",
  "6": "Apply Poison",
  "7": "Archery",
  "8": "Backstab",
  "9": "Bind Wound",
  "10": "Bash",
  "11": "Block",
  "12": "Brass Instruments",
  "13": "Channeling",
  "14": "Conjuration",
  "15": "Defense",
  "16": "Disarm",
  "17": "Disarm Traps",
  "18": "Divination",
  "19": "Dodge",
  "20": "Double Attack",
  "21": "Dragon Punch",
  "22": "Duel Wield",
  "23": "Eagle Strike",
  "24": "Evocation",
  "25": "Feign Death",
  "26": "Flying Kick",
  "27": "Forage",
  "28": "Hand To Hand",
  "29": "Hide",
  "30": "Kick",
  "31": "Meditate",
  "32": "Mend",
  "33": "Offense",
  "34": "Parry",
  "35": "Pick Lock",
  "36": "1H Piercing",
  "37": "Riposte",
  "38": "Round Kick",
  "39": "Safe Fall",
  "40": "Sense Heading",
  "41": "Singing",
  "42": "Sneak",
  "43": "Specialize Abjure",
  "44": "Specialize Alteration",
  "45": "Specialize Conjuration",
  "46": "Specialize Divination",
  "47": "Specialize Evocation",
  "48": "Pick Pockets",
  "49": "Stringed Instruments",
  "50": "Swimming",
  "51": "Throwing",
  "52": "Tiger Claw",
  "53": "Tracking",
  "54": "Wind Instruments",
  "55": "Fishing",
  "56": "Poison Making",
  "57": "Tinkering",
  "58": "Research",
  "59": "Alchemy",
  "60": "Baking",
  "61": "Tailoring",
  "62": "Sense Traps",
  "63": "Blacksmithing",
  "64": "Fletching",
  "65": "Brewing",
  "66": "Alcohol Tolerance",
  "67": "Begging",
  "68": "Jewelry Making",
  "69": "Pottery",
  "70": "Percussion Instruments",
  "71": "Intimidation",
  "72": "Berserking",
  "73": "Taunt",
  "74": "Frenzy",
  "75": "Remove Trap",
  "76": "Triple Attack",
  "77": "2H Piercing",
  "98": "Melee",
  "105": "Harm Touch",
  "107": "Lay Hand",
  "111": "Slam",
  "114": "Inspect Chest",
  "115": "Open Chest",
  "116": "Reveal Trap Chest"
}

export const DB_ITEM_SKILLS = {
  "0": "One Hand Slash",
  "1": "Two Hands Slash",
  "2": "Piercing",
  "3": "One Hand Blunt",
  "4": "Two Hands Blunt",
  "45": "Hand to hand"
}

export const ITEM_WEAPONS = {
  "0": "1HS",
  "1": "2HS",
  "2": "1HP",
  "3": "1HB",
  "4": "2HB",
  "35": "2HP",
}

export const DB_BARD_SKILLS = {
  "23": "Woodwind",
  "24": "Strings",
  "25": "Brass",
  "26": "Percussions",
  "50": "Singing",
  "51": "All instruments"
}
