/* tslint:disable */
/* eslint-disable */
/**
 * Spire
 * Spire API documentation
 *
 * The version of the OpenAPI document: 3.0
 * Contact: akkadius1@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CrudcontrollersBulkFetchByIdsGetRequest } from '../models';
// @ts-ignore
import { ModelsAaRankPrereq } from '../models';
/**
 * AaRankPrereqApi - axios parameter creator
 * @export
 */
export const AaRankPrereqApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Creates AaRankPrereq
         * @param {ModelsAaRankPrereq} aaRankPrereq AaRankPrereq
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAaRankPrereq: async (aaRankPrereq: ModelsAaRankPrereq, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'aaRankPrereq' is not null or undefined
            if (aaRankPrereq === null || aaRankPrereq === undefined) {
                throw new RequiredError('aaRankPrereq','Required parameter aaRankPrereq was null or undefined when calling createAaRankPrereq.');
            }
            const localVarPath = `/aa_rank_prereq`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const nonString = typeof aaRankPrereq !== 'string';
            const needsSerialization = nonString && configuration && configuration.isJsonMime
                ? configuration.isJsonMime(localVarRequestOptions.headers['Content-Type'])
                : nonString;
            localVarRequestOptions.data =  needsSerialization
                ? JSON.stringify(aaRankPrereq !== undefined ? aaRankPrereq : {})
                : (aaRankPrereq || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deletes AaRankPrereq
         * @param {number} id rankId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAaRankPrereq: async (id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling deleteAaRankPrereq.');
            }
            const localVarPath = `/aa_rank_prereq/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets AaRankPrereq
         * @param {number} id Id
         * @param {string} [includes] Relationships [all] for all [number] for depth of relationships to load or [.] separated relationship names 
         * @param {string} [select] Column names [.] separated to fetch specific fields in response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAaRankPrereq: async (id: number, includes?: string, select?: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling getAaRankPrereq.');
            }
            const localVarPath = `/aa_rank_prereq/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (includes !== undefined) {
                localVarQueryParameter['includes'] = includes;
            }

            if (select !== undefined) {
                localVarQueryParameter['select'] = select;
            }


    
            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets AaRankPrereqs in bulk
         * @param {CrudcontrollersBulkFetchByIdsGetRequest} body body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAaRankPrereqsBulk: async (body: CrudcontrollersBulkFetchByIdsGetRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling getAaRankPrereqsBulk.');
            }
            const localVarPath = `/aa_rank_prereqs/bulk`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const nonString = typeof body !== 'string';
            const needsSerialization = nonString && configuration && configuration.isJsonMime
                ? configuration.isJsonMime(localVarRequestOptions.headers['Content-Type'])
                : nonString;
            localVarRequestOptions.data =  needsSerialization
                ? JSON.stringify(body !== undefined ? body : {})
                : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Lists AaRankPrereqs
         * @param {string} [includes] Relationships [all] for all [number] for depth of relationships to load or [.] separated relationship names 
         * @param {string} [where] Filter on specific fields. Multiple conditions [.] separated Example: col_like_value.col2__val2
         * @param {string} [whereOr] Filter on specific fields (Chained ors). Multiple conditions [.] separated Example: col_like_value.col2__val2
         * @param {string} [groupBy] Group by field. Multiple conditions [.] separated Example: field1.field2
         * @param {string} [limit] Rows to limit in response (Default: 10,000)
         * @param {string} [orderBy] Order by [field]
         * @param {string} [orderDirection] Order by field direction
         * @param {string} [select] Column names [.] separated to fetch specific fields in response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAaRankPrereqs: async (includes?: string, where?: string, whereOr?: string, groupBy?: string, limit?: string, orderBy?: string, orderDirection?: string, select?: string, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/aa_rank_prereqs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (includes !== undefined) {
                localVarQueryParameter['includes'] = includes;
            }

            if (where !== undefined) {
                localVarQueryParameter['where'] = where;
            }

            if (whereOr !== undefined) {
                localVarQueryParameter['whereOr'] = whereOr;
            }

            if (groupBy !== undefined) {
                localVarQueryParameter['groupBy'] = groupBy;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (orderBy !== undefined) {
                localVarQueryParameter['orderBy'] = orderBy;
            }

            if (orderDirection !== undefined) {
                localVarQueryParameter['orderDirection'] = orderDirection;
            }

            if (select !== undefined) {
                localVarQueryParameter['select'] = select;
            }


    
            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Updates AaRankPrereq
         * @param {number} id Id
         * @param {ModelsAaRankPrereq} aaRankPrereq AaRankPrereq
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAaRankPrereq: async (id: number, aaRankPrereq: ModelsAaRankPrereq, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling updateAaRankPrereq.');
            }
            // verify required parameter 'aaRankPrereq' is not null or undefined
            if (aaRankPrereq === null || aaRankPrereq === undefined) {
                throw new RequiredError('aaRankPrereq','Required parameter aaRankPrereq was null or undefined when calling updateAaRankPrereq.');
            }
            const localVarPath = `/aa_rank_prereq/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const nonString = typeof aaRankPrereq !== 'string';
            const needsSerialization = nonString && configuration && configuration.isJsonMime
                ? configuration.isJsonMime(localVarRequestOptions.headers['Content-Type'])
                : nonString;
            localVarRequestOptions.data =  needsSerialization
                ? JSON.stringify(aaRankPrereq !== undefined ? aaRankPrereq : {})
                : (aaRankPrereq || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AaRankPrereqApi - functional programming interface
 * @export
 */
export const AaRankPrereqApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Creates AaRankPrereq
         * @param {ModelsAaRankPrereq} aaRankPrereq AaRankPrereq
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createAaRankPrereq(aaRankPrereq: ModelsAaRankPrereq, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ModelsAaRankPrereq>>> {
            const localVarAxiosArgs = await AaRankPrereqApiAxiosParamCreator(configuration).createAaRankPrereq(aaRankPrereq, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Deletes AaRankPrereq
         * @param {number} id rankId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteAaRankPrereq(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await AaRankPrereqApiAxiosParamCreator(configuration).deleteAaRankPrereq(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Gets AaRankPrereq
         * @param {number} id Id
         * @param {string} [includes] Relationships [all] for all [number] for depth of relationships to load or [.] separated relationship names 
         * @param {string} [select] Column names [.] separated to fetch specific fields in response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAaRankPrereq(id: number, includes?: string, select?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ModelsAaRankPrereq>>> {
            const localVarAxiosArgs = await AaRankPrereqApiAxiosParamCreator(configuration).getAaRankPrereq(id, includes, select, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Gets AaRankPrereqs in bulk
         * @param {CrudcontrollersBulkFetchByIdsGetRequest} body body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAaRankPrereqsBulk(body: CrudcontrollersBulkFetchByIdsGetRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ModelsAaRankPrereq>>> {
            const localVarAxiosArgs = await AaRankPrereqApiAxiosParamCreator(configuration).getAaRankPrereqsBulk(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Lists AaRankPrereqs
         * @param {string} [includes] Relationships [all] for all [number] for depth of relationships to load or [.] separated relationship names 
         * @param {string} [where] Filter on specific fields. Multiple conditions [.] separated Example: col_like_value.col2__val2
         * @param {string} [whereOr] Filter on specific fields (Chained ors). Multiple conditions [.] separated Example: col_like_value.col2__val2
         * @param {string} [groupBy] Group by field. Multiple conditions [.] separated Example: field1.field2
         * @param {string} [limit] Rows to limit in response (Default: 10,000)
         * @param {string} [orderBy] Order by [field]
         * @param {string} [orderDirection] Order by field direction
         * @param {string} [select] Column names [.] separated to fetch specific fields in response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listAaRankPrereqs(includes?: string, where?: string, whereOr?: string, groupBy?: string, limit?: string, orderBy?: string, orderDirection?: string, select?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ModelsAaRankPrereq>>> {
            const localVarAxiosArgs = await AaRankPrereqApiAxiosParamCreator(configuration).listAaRankPrereqs(includes, where, whereOr, groupBy, limit, orderBy, orderDirection, select, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Updates AaRankPrereq
         * @param {number} id Id
         * @param {ModelsAaRankPrereq} aaRankPrereq AaRankPrereq
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateAaRankPrereq(id: number, aaRankPrereq: ModelsAaRankPrereq, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ModelsAaRankPrereq>>> {
            const localVarAxiosArgs = await AaRankPrereqApiAxiosParamCreator(configuration).updateAaRankPrereq(id, aaRankPrereq, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * AaRankPrereqApi - factory interface
 * @export
 */
export const AaRankPrereqApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Creates AaRankPrereq
         * @param {ModelsAaRankPrereq} aaRankPrereq AaRankPrereq
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAaRankPrereq(aaRankPrereq: ModelsAaRankPrereq, options?: any): AxiosPromise<Array<ModelsAaRankPrereq>> {
            return AaRankPrereqApiFp(configuration).createAaRankPrereq(aaRankPrereq, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deletes AaRankPrereq
         * @param {number} id rankId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAaRankPrereq(id: number, options?: any): AxiosPromise<string> {
            return AaRankPrereqApiFp(configuration).deleteAaRankPrereq(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets AaRankPrereq
         * @param {number} id Id
         * @param {string} [includes] Relationships [all] for all [number] for depth of relationships to load or [.] separated relationship names 
         * @param {string} [select] Column names [.] separated to fetch specific fields in response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAaRankPrereq(id: number, includes?: string, select?: string, options?: any): AxiosPromise<Array<ModelsAaRankPrereq>> {
            return AaRankPrereqApiFp(configuration).getAaRankPrereq(id, includes, select, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets AaRankPrereqs in bulk
         * @param {CrudcontrollersBulkFetchByIdsGetRequest} body body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAaRankPrereqsBulk(body: CrudcontrollersBulkFetchByIdsGetRequest, options?: any): AxiosPromise<Array<ModelsAaRankPrereq>> {
            return AaRankPrereqApiFp(configuration).getAaRankPrereqsBulk(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Lists AaRankPrereqs
         * @param {string} [includes] Relationships [all] for all [number] for depth of relationships to load or [.] separated relationship names 
         * @param {string} [where] Filter on specific fields. Multiple conditions [.] separated Example: col_like_value.col2__val2
         * @param {string} [whereOr] Filter on specific fields (Chained ors). Multiple conditions [.] separated Example: col_like_value.col2__val2
         * @param {string} [groupBy] Group by field. Multiple conditions [.] separated Example: field1.field2
         * @param {string} [limit] Rows to limit in response (Default: 10,000)
         * @param {string} [orderBy] Order by [field]
         * @param {string} [orderDirection] Order by field direction
         * @param {string} [select] Column names [.] separated to fetch specific fields in response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAaRankPrereqs(includes?: string, where?: string, whereOr?: string, groupBy?: string, limit?: string, orderBy?: string, orderDirection?: string, select?: string, options?: any): AxiosPromise<Array<ModelsAaRankPrereq>> {
            return AaRankPrereqApiFp(configuration).listAaRankPrereqs(includes, where, whereOr, groupBy, limit, orderBy, orderDirection, select, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Updates AaRankPrereq
         * @param {number} id Id
         * @param {ModelsAaRankPrereq} aaRankPrereq AaRankPrereq
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAaRankPrereq(id: number, aaRankPrereq: ModelsAaRankPrereq, options?: any): AxiosPromise<Array<ModelsAaRankPrereq>> {
            return AaRankPrereqApiFp(configuration).updateAaRankPrereq(id, aaRankPrereq, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createAaRankPrereq operation in AaRankPrereqApi.
 * @export
 * @interface AaRankPrereqApiCreateAaRankPrereqRequest
 */
export interface AaRankPrereqApiCreateAaRankPrereqRequest {
    /**
     * AaRankPrereq
     * @type {ModelsAaRankPrereq}
     * @memberof AaRankPrereqApiCreateAaRankPrereq
     */
    readonly aaRankPrereq: ModelsAaRankPrereq
}

/**
 * Request parameters for deleteAaRankPrereq operation in AaRankPrereqApi.
 * @export
 * @interface AaRankPrereqApiDeleteAaRankPrereqRequest
 */
export interface AaRankPrereqApiDeleteAaRankPrereqRequest {
    /**
     * rankId
     * @type {number}
     * @memberof AaRankPrereqApiDeleteAaRankPrereq
     */
    readonly id: number
}

/**
 * Request parameters for getAaRankPrereq operation in AaRankPrereqApi.
 * @export
 * @interface AaRankPrereqApiGetAaRankPrereqRequest
 */
export interface AaRankPrereqApiGetAaRankPrereqRequest {
    /**
     * Id
     * @type {number}
     * @memberof AaRankPrereqApiGetAaRankPrereq
     */
    readonly id: number

    /**
     * Relationships [all] for all [number] for depth of relationships to load or [.] separated relationship names 
     * @type {string}
     * @memberof AaRankPrereqApiGetAaRankPrereq
     */
    readonly includes?: string

    /**
     * Column names [.] separated to fetch specific fields in response
     * @type {string}
     * @memberof AaRankPrereqApiGetAaRankPrereq
     */
    readonly select?: string
}

/**
 * Request parameters for getAaRankPrereqsBulk operation in AaRankPrereqApi.
 * @export
 * @interface AaRankPrereqApiGetAaRankPrereqsBulkRequest
 */
export interface AaRankPrereqApiGetAaRankPrereqsBulkRequest {
    /**
     * body
     * @type {CrudcontrollersBulkFetchByIdsGetRequest}
     * @memberof AaRankPrereqApiGetAaRankPrereqsBulk
     */
    readonly body: CrudcontrollersBulkFetchByIdsGetRequest
}

/**
 * Request parameters for listAaRankPrereqs operation in AaRankPrereqApi.
 * @export
 * @interface AaRankPrereqApiListAaRankPrereqsRequest
 */
export interface AaRankPrereqApiListAaRankPrereqsRequest {
    /**
     * Relationships [all] for all [number] for depth of relationships to load or [.] separated relationship names 
     * @type {string}
     * @memberof AaRankPrereqApiListAaRankPrereqs
     */
    readonly includes?: string

    /**
     * Filter on specific fields. Multiple conditions [.] separated Example: col_like_value.col2__val2
     * @type {string}
     * @memberof AaRankPrereqApiListAaRankPrereqs
     */
    readonly where?: string

    /**
     * Filter on specific fields (Chained ors). Multiple conditions [.] separated Example: col_like_value.col2__val2
     * @type {string}
     * @memberof AaRankPrereqApiListAaRankPrereqs
     */
    readonly whereOr?: string

    /**
     * Group by field. Multiple conditions [.] separated Example: field1.field2
     * @type {string}
     * @memberof AaRankPrereqApiListAaRankPrereqs
     */
    readonly groupBy?: string

    /**
     * Rows to limit in response (Default: 10,000)
     * @type {string}
     * @memberof AaRankPrereqApiListAaRankPrereqs
     */
    readonly limit?: string

    /**
     * Order by [field]
     * @type {string}
     * @memberof AaRankPrereqApiListAaRankPrereqs
     */
    readonly orderBy?: string

    /**
     * Order by field direction
     * @type {string}
     * @memberof AaRankPrereqApiListAaRankPrereqs
     */
    readonly orderDirection?: string

    /**
     * Column names [.] separated to fetch specific fields in response
     * @type {string}
     * @memberof AaRankPrereqApiListAaRankPrereqs
     */
    readonly select?: string
}

/**
 * Request parameters for updateAaRankPrereq operation in AaRankPrereqApi.
 * @export
 * @interface AaRankPrereqApiUpdateAaRankPrereqRequest
 */
export interface AaRankPrereqApiUpdateAaRankPrereqRequest {
    /**
     * Id
     * @type {number}
     * @memberof AaRankPrereqApiUpdateAaRankPrereq
     */
    readonly id: number

    /**
     * AaRankPrereq
     * @type {ModelsAaRankPrereq}
     * @memberof AaRankPrereqApiUpdateAaRankPrereq
     */
    readonly aaRankPrereq: ModelsAaRankPrereq
}

/**
 * AaRankPrereqApi - object-oriented interface
 * @export
 * @class AaRankPrereqApi
 * @extends {BaseAPI}
 */
export class AaRankPrereqApi extends BaseAPI {
    /**
     * 
     * @summary Creates AaRankPrereq
     * @param {AaRankPrereqApiCreateAaRankPrereqRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AaRankPrereqApi
     */
    public createAaRankPrereq(requestParameters: AaRankPrereqApiCreateAaRankPrereqRequest, options?: any) {
        return AaRankPrereqApiFp(this.configuration).createAaRankPrereq(requestParameters.aaRankPrereq, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Deletes AaRankPrereq
     * @param {AaRankPrereqApiDeleteAaRankPrereqRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AaRankPrereqApi
     */
    public deleteAaRankPrereq(requestParameters: AaRankPrereqApiDeleteAaRankPrereqRequest, options?: any) {
        return AaRankPrereqApiFp(this.configuration).deleteAaRankPrereq(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Gets AaRankPrereq
     * @param {AaRankPrereqApiGetAaRankPrereqRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AaRankPrereqApi
     */
    public getAaRankPrereq(requestParameters: AaRankPrereqApiGetAaRankPrereqRequest, options?: any) {
        return AaRankPrereqApiFp(this.configuration).getAaRankPrereq(requestParameters.id, requestParameters.includes, requestParameters.select, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Gets AaRankPrereqs in bulk
     * @param {AaRankPrereqApiGetAaRankPrereqsBulkRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AaRankPrereqApi
     */
    public getAaRankPrereqsBulk(requestParameters: AaRankPrereqApiGetAaRankPrereqsBulkRequest, options?: any) {
        return AaRankPrereqApiFp(this.configuration).getAaRankPrereqsBulk(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Lists AaRankPrereqs
     * @param {AaRankPrereqApiListAaRankPrereqsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AaRankPrereqApi
     */
    public listAaRankPrereqs(requestParameters: AaRankPrereqApiListAaRankPrereqsRequest = {}, options?: any) {
        return AaRankPrereqApiFp(this.configuration).listAaRankPrereqs(requestParameters.includes, requestParameters.where, requestParameters.whereOr, requestParameters.groupBy, requestParameters.limit, requestParameters.orderBy, requestParameters.orderDirection, requestParameters.select, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Updates AaRankPrereq
     * @param {AaRankPrereqApiUpdateAaRankPrereqRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AaRankPrereqApi
     */
    public updateAaRankPrereq(requestParameters: AaRankPrereqApiUpdateAaRankPrereqRequest, options?: any) {
        return AaRankPrereqApiFp(this.configuration).updateAaRankPrereq(requestParameters.id, requestParameters.aaRankPrereq, options).then((request) => request(this.axios, this.basePath));
    }
}
