/* tslint:disable */
/* eslint-disable */
/**
 * Spire
 * Spire API documentation
 *
 * The version of the OpenAPI document: 3.0
 * Contact: akkadius1@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CrudcontrollersBulkFetchByIdsGetRequest } from '../models';
// @ts-ignore
import { ModelsBaseDatum } from '../models';
/**
 * BaseDatumApi - axios parameter creator
 * @export
 */
export const BaseDatumApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Creates BaseDatum
         * @param {ModelsBaseDatum} baseDatum BaseDatum
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBaseDatum: async (baseDatum: ModelsBaseDatum, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'baseDatum' is not null or undefined
            if (baseDatum === null || baseDatum === undefined) {
                throw new RequiredError('baseDatum','Required parameter baseDatum was null or undefined when calling createBaseDatum.');
            }
            const localVarPath = `/base_datum`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const nonString = typeof baseDatum !== 'string';
            const needsSerialization = nonString && configuration && configuration.isJsonMime
                ? configuration.isJsonMime(localVarRequestOptions.headers['Content-Type'])
                : nonString;
            localVarRequestOptions.data =  needsSerialization
                ? JSON.stringify(baseDatum !== undefined ? baseDatum : {})
                : (baseDatum || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deletes BaseDatum
         * @param {number} id level
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteBaseDatum: async (id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling deleteBaseDatum.');
            }
            const localVarPath = `/base_datum/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets BaseData in bulk
         * @param {CrudcontrollersBulkFetchByIdsGetRequest} body body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBaseDataBulk: async (body: CrudcontrollersBulkFetchByIdsGetRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling getBaseDataBulk.');
            }
            const localVarPath = `/base_data/bulk`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const nonString = typeof body !== 'string';
            const needsSerialization = nonString && configuration && configuration.isJsonMime
                ? configuration.isJsonMime(localVarRequestOptions.headers['Content-Type'])
                : nonString;
            localVarRequestOptions.data =  needsSerialization
                ? JSON.stringify(body !== undefined ? body : {})
                : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets BaseDatum
         * @param {number} id Id
         * @param {string} [includes] Relationships [all] for all [number] for depth of relationships to load or [.] separated relationship names 
         * @param {string} [select] Column names [.] separated to fetch specific fields in response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBaseDatum: async (id: number, includes?: string, select?: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling getBaseDatum.');
            }
            const localVarPath = `/base_datum/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (includes !== undefined) {
                localVarQueryParameter['includes'] = includes;
            }

            if (select !== undefined) {
                localVarQueryParameter['select'] = select;
            }


    
            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Lists BaseData
         * @param {string} [includes] Relationships [all] for all [number] for depth of relationships to load or [.] separated relationship names 
         * @param {string} [where] Filter on specific fields. Multiple conditions [.] separated Example: col_like_value.col2__val2
         * @param {string} [whereOr] Filter on specific fields (Chained ors). Multiple conditions [.] separated Example: col_like_value.col2__val2
         * @param {string} [groupBy] Group by field. Multiple conditions [.] separated Example: field1.field2
         * @param {string} [limit] Rows to limit in response (Default: 10,000)
         * @param {string} [orderBy] Order by [field]
         * @param {string} [orderDirection] Order by field direction
         * @param {string} [select] Column names [.] separated to fetch specific fields in response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBaseData: async (includes?: string, where?: string, whereOr?: string, groupBy?: string, limit?: string, orderBy?: string, orderDirection?: string, select?: string, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/base_data`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (includes !== undefined) {
                localVarQueryParameter['includes'] = includes;
            }

            if (where !== undefined) {
                localVarQueryParameter['where'] = where;
            }

            if (whereOr !== undefined) {
                localVarQueryParameter['whereOr'] = whereOr;
            }

            if (groupBy !== undefined) {
                localVarQueryParameter['groupBy'] = groupBy;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (orderBy !== undefined) {
                localVarQueryParameter['orderBy'] = orderBy;
            }

            if (orderDirection !== undefined) {
                localVarQueryParameter['orderDirection'] = orderDirection;
            }

            if (select !== undefined) {
                localVarQueryParameter['select'] = select;
            }


    
            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Updates BaseDatum
         * @param {number} id Id
         * @param {ModelsBaseDatum} baseDatum BaseDatum
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateBaseDatum: async (id: number, baseDatum: ModelsBaseDatum, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling updateBaseDatum.');
            }
            // verify required parameter 'baseDatum' is not null or undefined
            if (baseDatum === null || baseDatum === undefined) {
                throw new RequiredError('baseDatum','Required parameter baseDatum was null or undefined when calling updateBaseDatum.');
            }
            const localVarPath = `/base_datum/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            const queryParameters = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                queryParameters.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                queryParameters.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(queryParameters)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const nonString = typeof baseDatum !== 'string';
            const needsSerialization = nonString && configuration && configuration.isJsonMime
                ? configuration.isJsonMime(localVarRequestOptions.headers['Content-Type'])
                : nonString;
            localVarRequestOptions.data =  needsSerialization
                ? JSON.stringify(baseDatum !== undefined ? baseDatum : {})
                : (baseDatum || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BaseDatumApi - functional programming interface
 * @export
 */
export const BaseDatumApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Creates BaseDatum
         * @param {ModelsBaseDatum} baseDatum BaseDatum
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createBaseDatum(baseDatum: ModelsBaseDatum, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ModelsBaseDatum>>> {
            const localVarAxiosArgs = await BaseDatumApiAxiosParamCreator(configuration).createBaseDatum(baseDatum, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Deletes BaseDatum
         * @param {number} id level
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteBaseDatum(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await BaseDatumApiAxiosParamCreator(configuration).deleteBaseDatum(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Gets BaseData in bulk
         * @param {CrudcontrollersBulkFetchByIdsGetRequest} body body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBaseDataBulk(body: CrudcontrollersBulkFetchByIdsGetRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ModelsBaseDatum>>> {
            const localVarAxiosArgs = await BaseDatumApiAxiosParamCreator(configuration).getBaseDataBulk(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Gets BaseDatum
         * @param {number} id Id
         * @param {string} [includes] Relationships [all] for all [number] for depth of relationships to load or [.] separated relationship names 
         * @param {string} [select] Column names [.] separated to fetch specific fields in response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBaseDatum(id: number, includes?: string, select?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ModelsBaseDatum>>> {
            const localVarAxiosArgs = await BaseDatumApiAxiosParamCreator(configuration).getBaseDatum(id, includes, select, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Lists BaseData
         * @param {string} [includes] Relationships [all] for all [number] for depth of relationships to load or [.] separated relationship names 
         * @param {string} [where] Filter on specific fields. Multiple conditions [.] separated Example: col_like_value.col2__val2
         * @param {string} [whereOr] Filter on specific fields (Chained ors). Multiple conditions [.] separated Example: col_like_value.col2__val2
         * @param {string} [groupBy] Group by field. Multiple conditions [.] separated Example: field1.field2
         * @param {string} [limit] Rows to limit in response (Default: 10,000)
         * @param {string} [orderBy] Order by [field]
         * @param {string} [orderDirection] Order by field direction
         * @param {string} [select] Column names [.] separated to fetch specific fields in response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listBaseData(includes?: string, where?: string, whereOr?: string, groupBy?: string, limit?: string, orderBy?: string, orderDirection?: string, select?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ModelsBaseDatum>>> {
            const localVarAxiosArgs = await BaseDatumApiAxiosParamCreator(configuration).listBaseData(includes, where, whereOr, groupBy, limit, orderBy, orderDirection, select, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Updates BaseDatum
         * @param {number} id Id
         * @param {ModelsBaseDatum} baseDatum BaseDatum
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateBaseDatum(id: number, baseDatum: ModelsBaseDatum, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ModelsBaseDatum>>> {
            const localVarAxiosArgs = await BaseDatumApiAxiosParamCreator(configuration).updateBaseDatum(id, baseDatum, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: (configuration?.basePath || basePath) + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * BaseDatumApi - factory interface
 * @export
 */
export const BaseDatumApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Creates BaseDatum
         * @param {ModelsBaseDatum} baseDatum BaseDatum
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBaseDatum(baseDatum: ModelsBaseDatum, options?: any): AxiosPromise<Array<ModelsBaseDatum>> {
            return BaseDatumApiFp(configuration).createBaseDatum(baseDatum, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deletes BaseDatum
         * @param {number} id level
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteBaseDatum(id: number, options?: any): AxiosPromise<string> {
            return BaseDatumApiFp(configuration).deleteBaseDatum(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets BaseData in bulk
         * @param {CrudcontrollersBulkFetchByIdsGetRequest} body body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBaseDataBulk(body: CrudcontrollersBulkFetchByIdsGetRequest, options?: any): AxiosPromise<Array<ModelsBaseDatum>> {
            return BaseDatumApiFp(configuration).getBaseDataBulk(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets BaseDatum
         * @param {number} id Id
         * @param {string} [includes] Relationships [all] for all [number] for depth of relationships to load or [.] separated relationship names 
         * @param {string} [select] Column names [.] separated to fetch specific fields in response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBaseDatum(id: number, includes?: string, select?: string, options?: any): AxiosPromise<Array<ModelsBaseDatum>> {
            return BaseDatumApiFp(configuration).getBaseDatum(id, includes, select, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Lists BaseData
         * @param {string} [includes] Relationships [all] for all [number] for depth of relationships to load or [.] separated relationship names 
         * @param {string} [where] Filter on specific fields. Multiple conditions [.] separated Example: col_like_value.col2__val2
         * @param {string} [whereOr] Filter on specific fields (Chained ors). Multiple conditions [.] separated Example: col_like_value.col2__val2
         * @param {string} [groupBy] Group by field. Multiple conditions [.] separated Example: field1.field2
         * @param {string} [limit] Rows to limit in response (Default: 10,000)
         * @param {string} [orderBy] Order by [field]
         * @param {string} [orderDirection] Order by field direction
         * @param {string} [select] Column names [.] separated to fetch specific fields in response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBaseData(includes?: string, where?: string, whereOr?: string, groupBy?: string, limit?: string, orderBy?: string, orderDirection?: string, select?: string, options?: any): AxiosPromise<Array<ModelsBaseDatum>> {
            return BaseDatumApiFp(configuration).listBaseData(includes, where, whereOr, groupBy, limit, orderBy, orderDirection, select, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Updates BaseDatum
         * @param {number} id Id
         * @param {ModelsBaseDatum} baseDatum BaseDatum
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateBaseDatum(id: number, baseDatum: ModelsBaseDatum, options?: any): AxiosPromise<Array<ModelsBaseDatum>> {
            return BaseDatumApiFp(configuration).updateBaseDatum(id, baseDatum, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createBaseDatum operation in BaseDatumApi.
 * @export
 * @interface BaseDatumApiCreateBaseDatumRequest
 */
export interface BaseDatumApiCreateBaseDatumRequest {
    /**
     * BaseDatum
     * @type {ModelsBaseDatum}
     * @memberof BaseDatumApiCreateBaseDatum
     */
    readonly baseDatum: ModelsBaseDatum
}

/**
 * Request parameters for deleteBaseDatum operation in BaseDatumApi.
 * @export
 * @interface BaseDatumApiDeleteBaseDatumRequest
 */
export interface BaseDatumApiDeleteBaseDatumRequest {
    /**
     * level
     * @type {number}
     * @memberof BaseDatumApiDeleteBaseDatum
     */
    readonly id: number
}

/**
 * Request parameters for getBaseDataBulk operation in BaseDatumApi.
 * @export
 * @interface BaseDatumApiGetBaseDataBulkRequest
 */
export interface BaseDatumApiGetBaseDataBulkRequest {
    /**
     * body
     * @type {CrudcontrollersBulkFetchByIdsGetRequest}
     * @memberof BaseDatumApiGetBaseDataBulk
     */
    readonly body: CrudcontrollersBulkFetchByIdsGetRequest
}

/**
 * Request parameters for getBaseDatum operation in BaseDatumApi.
 * @export
 * @interface BaseDatumApiGetBaseDatumRequest
 */
export interface BaseDatumApiGetBaseDatumRequest {
    /**
     * Id
     * @type {number}
     * @memberof BaseDatumApiGetBaseDatum
     */
    readonly id: number

    /**
     * Relationships [all] for all [number] for depth of relationships to load or [.] separated relationship names 
     * @type {string}
     * @memberof BaseDatumApiGetBaseDatum
     */
    readonly includes?: string

    /**
     * Column names [.] separated to fetch specific fields in response
     * @type {string}
     * @memberof BaseDatumApiGetBaseDatum
     */
    readonly select?: string
}

/**
 * Request parameters for listBaseData operation in BaseDatumApi.
 * @export
 * @interface BaseDatumApiListBaseDataRequest
 */
export interface BaseDatumApiListBaseDataRequest {
    /**
     * Relationships [all] for all [number] for depth of relationships to load or [.] separated relationship names 
     * @type {string}
     * @memberof BaseDatumApiListBaseData
     */
    readonly includes?: string

    /**
     * Filter on specific fields. Multiple conditions [.] separated Example: col_like_value.col2__val2
     * @type {string}
     * @memberof BaseDatumApiListBaseData
     */
    readonly where?: string

    /**
     * Filter on specific fields (Chained ors). Multiple conditions [.] separated Example: col_like_value.col2__val2
     * @type {string}
     * @memberof BaseDatumApiListBaseData
     */
    readonly whereOr?: string

    /**
     * Group by field. Multiple conditions [.] separated Example: field1.field2
     * @type {string}
     * @memberof BaseDatumApiListBaseData
     */
    readonly groupBy?: string

    /**
     * Rows to limit in response (Default: 10,000)
     * @type {string}
     * @memberof BaseDatumApiListBaseData
     */
    readonly limit?: string

    /**
     * Order by [field]
     * @type {string}
     * @memberof BaseDatumApiListBaseData
     */
    readonly orderBy?: string

    /**
     * Order by field direction
     * @type {string}
     * @memberof BaseDatumApiListBaseData
     */
    readonly orderDirection?: string

    /**
     * Column names [.] separated to fetch specific fields in response
     * @type {string}
     * @memberof BaseDatumApiListBaseData
     */
    readonly select?: string
}

/**
 * Request parameters for updateBaseDatum operation in BaseDatumApi.
 * @export
 * @interface BaseDatumApiUpdateBaseDatumRequest
 */
export interface BaseDatumApiUpdateBaseDatumRequest {
    /**
     * Id
     * @type {number}
     * @memberof BaseDatumApiUpdateBaseDatum
     */
    readonly id: number

    /**
     * BaseDatum
     * @type {ModelsBaseDatum}
     * @memberof BaseDatumApiUpdateBaseDatum
     */
    readonly baseDatum: ModelsBaseDatum
}

/**
 * BaseDatumApi - object-oriented interface
 * @export
 * @class BaseDatumApi
 * @extends {BaseAPI}
 */
export class BaseDatumApi extends BaseAPI {
    /**
     * 
     * @summary Creates BaseDatum
     * @param {BaseDatumApiCreateBaseDatumRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BaseDatumApi
     */
    public createBaseDatum(requestParameters: BaseDatumApiCreateBaseDatumRequest, options?: any) {
        return BaseDatumApiFp(this.configuration).createBaseDatum(requestParameters.baseDatum, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Deletes BaseDatum
     * @param {BaseDatumApiDeleteBaseDatumRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BaseDatumApi
     */
    public deleteBaseDatum(requestParameters: BaseDatumApiDeleteBaseDatumRequest, options?: any) {
        return BaseDatumApiFp(this.configuration).deleteBaseDatum(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Gets BaseData in bulk
     * @param {BaseDatumApiGetBaseDataBulkRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BaseDatumApi
     */
    public getBaseDataBulk(requestParameters: BaseDatumApiGetBaseDataBulkRequest, options?: any) {
        return BaseDatumApiFp(this.configuration).getBaseDataBulk(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Gets BaseDatum
     * @param {BaseDatumApiGetBaseDatumRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BaseDatumApi
     */
    public getBaseDatum(requestParameters: BaseDatumApiGetBaseDatumRequest, options?: any) {
        return BaseDatumApiFp(this.configuration).getBaseDatum(requestParameters.id, requestParameters.includes, requestParameters.select, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Lists BaseData
     * @param {BaseDatumApiListBaseDataRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BaseDatumApi
     */
    public listBaseData(requestParameters: BaseDatumApiListBaseDataRequest = {}, options?: any) {
        return BaseDatumApiFp(this.configuration).listBaseData(requestParameters.includes, requestParameters.where, requestParameters.whereOr, requestParameters.groupBy, requestParameters.limit, requestParameters.orderBy, requestParameters.orderDirection, requestParameters.select, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Updates BaseDatum
     * @param {BaseDatumApiUpdateBaseDatumRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BaseDatumApi
     */
    public updateBaseDatum(requestParameters: BaseDatumApiUpdateBaseDatumRequest, options?: any) {
        return BaseDatumApiFp(this.configuration).updateBaseDatum(requestParameters.id, requestParameters.baseDatum, options).then((request) => request(this.axios, this.basePath));
    }
}
