export const ROUTE = {
  CLIENT_FILES: "/client-files",
  EMITTER_VIEWER: "/emitter-viewer",
  ITEM_EDIT: "/item/%s",
  ITEM_ICON_VIEWER: "/item-icon-viewer",
  ITEM_VIEWER: "/item-viewer",
  ITEMS_LIST: "/items",
  NPCS_EDIT: "/zone/npcs/:zone",
  NPC_EDIT: "/npc/:npc",
  PLAYER_ANIMATION_VIEWER: "/player-animation-viewer",
  QUEST_API_EXPLORER: "/quest-api-explorer",
  RACE_VIEWER: "/race-viewer",
  SPELL_ANIMATION_VIEWER: "/spell-animation-viewer",
  SPELL_EDIT: "/spell/%s",
  SPELLS_LIST: "/spells",
  STRINGS_DATABASE: "/strings-database",
  TASK_EDIT: "/tasks/%s",
  TASKS: "/tasks",
  MERCHANTS: "/merchants",
  ZONES: "/zones",
};
